### ISSUE TITLE
Feature Request: Symlink/Junction by Default

### ISSUE THREAD

**Issue by JustinGrote** [twpayne/chezmoi#1005]
## Is your feature request related to a problem? Please describe.

I get frustrated when I edit my file locally using a tool out of habit and chezmoi overwrites it. I made an alias to automate the process of removing the file, ignoring it, then symlinking it, but I was thinking this should be something chezmoi can do itself with a setting, that when doing an apply just drop a symlink out there rather than copy the file.

## Describe the solution you'd like

A configuration option as well as a command line switch to `init` to make symlinks (and ntfs junctions on windows since they dont require admin rights) the default method of "deploying" dotfiles.

## Describe alternatives you've considered

The alias discussed earlier to automate the conversion process, but it's not foolproof and doesn't work with net-new files I forgot to update

## Additional context

If flagged as `up-for-grabs` I'd be willing to attempt a PR if there's willingness to merge.

**Comment by twpayne** [comment]
Thanks for reporting this :)

Please first have a look at #980 which explains why chezmoi does not use symlinks in the same way that (for example) GNU Stow does, but chezmoi still has first class support for symlinks.

chezmoi's medium term solution to not losing your local edits to your dofiles is twofold:
1. With chezmoi2 (#987), chezmoi detects if the dotfile was modified since chezmoi last wrote it and warns you before overwriting.
2. chemzoi2 will also add a couple of commands/flags that will cause chezmoi to watch for file changes and immediately update your dotfiles when you save the file - just like editing a file through a symlink.

I've never heard of NTFS junctions before. If I understand correctly, they're basically symlinks to directories. Do they need special handling that isn't covered by the symlink use case?

**Comment by JustinGrote** [comment]
@twpayne on windows they're basically symlinks that don't require admin rights, and they can't cross filesystems (they are closer to hardlinks). You can do symlinks in Windows but they require admin rights.

#2 covers my use case most likely so I'll start testing with chezmoi2. Thanks for your detailed info.

**Comment by zb140** [comment]
Just to add a small clarification, you can make symlinks in Windows 10 without admin rights if you have developer mode enabled. Also, junctions can only point to directories.  In Unix terms, I tend to think of them more like bind mounts rather than links.
