### ISSUE TITLE
Is it possible to ignore a single line in a target file?

### ISSUE THREAD

**Issue by Daniel157** [twpayne/chezmoi#1046]
## What exactly are you trying to do?

I'm assembling my config file for kubectl (```$HOME/.kube/config```) using chezmoi. The config file consists of credentials for different Kubernetes clusters. Here you can see an example, how a config file for kubectl typically looks like: https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

In this config file, there is one line called ```current-context```. This line indicates the cluster, that I'm currently interacting with. This line changes all the time (depending on which cluster I'm currently working with).
I would like chezmoi to simply ignore this line. It should not overwrite/remove this line each time I call ```chezmoi apply```.

Is it possible to achieve this somehow?

## What have you tried so far?

I would imagine that it should be possible to do something like this in my template file:

```
current-context: {{ ignore }}
```

However, I couldn't find something like this.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of `chezmoi doctor`

```
$ chezmoi doctor
     ok: version 1.8.11, commit 2e5a76c23de034344f7a9fa89cd3088cd9b52ac7, built at 2021-02-05T00:46:35Z, built by goreleaser
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/daniel/.local/share/chezmoi (source directory, perm 700)
     ok: /home/daniel (destination directory, perm 755)
     ok: /home/daniel/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/bin/zsh (shell)
     ok: /usr/bin/nano (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.25.1)
     ok: /usr/bin/gpg (GnuPG, version 2.2.19)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

**Comment by twpayne** [comment]
Thanks for the clear and complete feature request @Daniel157!

`$HOME/.kube/config` is particularly tricky to manage because it's a combination of a database of clusters (with clusters being added, updated, and removed fairly regularly) and temporary state (e.g. your current cluster), all of which is regularly read and re-written by a wide variety of tools.

A few quick thoughts:

### Idea 1: env vars and templates to communicate current cluster (possible now)

Overview:

Make `$HOME/.kube/config` a template:

    chezmoi chattr +template ~/.kube/config

Before running chezmoi, save the current context in an environment variable by running

    export CHEZMOI_K8S_CURRENT_CONTEXT=$(kubectl config current-context)

Edit `dot_kube/config.tmpl` in the source state and change the `current-context:` line to retrieve the current context from the environment variable using the [`env`](http://masterminds.github.io/sprig/os.html) template function:

    current-context: {{ env "CHEZMOI_K8S_CURRENT_CONTEXT" }}

This of course requires you to set the `$CHEZMOI_K8S_CURRENT_CONTEXT` env var each time before you run chezmoi, but this is tiresome. You can of course wrap chezmoi in a shell script to automate this.

### Idea 2: Add an `output` function to chezmoi

If there was an `output` function that returned the output of an arbitrary command, then you could achieve the above with a template only:

    current-context: {{ output "kubectl" "config" "current-context" | trim }}

This doesn't exist yet, but I'll add it to chezmoi v2.

### Idea 3: use a `modify_` script in chezmoi v2

* #847 is a similar request, the conclusion was to allow the user to write scripts that modified an existing config file. The script receives the current contents on stdin and writes the target contents to stdout. This is fully integrated into commands like `chezmoi diff`.
* #1027 implements this, but for chezmoi v2, not the current stable version.
* #1039 is tracking progress towards the release of chezmoi v2.
* `modify_` scripts are more useful when you're changing a small part of the config file. Note that in the case of creating a config file for the first time on a new machine, stdin will be empty so the script has to generate the full contents of the file.

**Comment by Daniel157** [comment]
Thanks for the fast response! I like the idea with the output function a lot. That seems quite straightforward and solves the problem. And also thanks for implementing this for chezmoi2!

**Comment by cstoitner** [comment]
One downside of using modify_ scripts or output functions is that the source file has to be a script/template and so making changes to the target file directly always requires to merge it to the source script/template later. As noted in #847 some GUI applications write non-config stuff in their config files, and these config files are usually edited through the GUI, so this workflow is still going to be quite cumbersome.

I am wondering if we could also have a script that takes the target file as input and transforms it to the actually target state chezmoi will see. Such a script could simply strip out all the non-config stuff from the file and than chezmoi add, status and diff would just work, no merging required. The downside would be that these non-config things would be lost after chezmoi apply. Another problem might be that this requires 2 files in the chezmoi source (the actually source file (or template) and the target-to-actual-target conversion script).

**Comment by lcrockett** [comment]
I also ran into the situation where i'd like to manage part of a file due to the application (k9s) using a configuration file to write both configuration and state. I've managed to solve this using a `modify_` script which seems to work as expected.

One annoyance however is that with each combination of running `chezmoi apply` and having used the application before the `apply` (and therefore the target file has been modified) `chezmoi` asks if i'd like to overwrite the file as it has been modified since the last `apply`. I haven't come across any provisions to solve this within `chezmoi`, however I propose a file similar to `.chezmoiignore`. Something like `.chezmoioverwrite` in which we can specify files that will always be overwritten without requiring prompting the user during a `chezmoi apply`. If you'd like a separate issue for this specific feature request, let me know.

Considering the desire for examples was mentioned in #847; see below.

```bash
~/.local/share/chezmoi $ cat exact_dot_k9s/modify_config.yml
#!/usr/bin/env bash

cat << EOF
k9s:
  refreshRate: 1
  maxConnRetry: 5
  enableMouse: true
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 500
    buffer: 5000
    sinceSeconds: 3600
    fullScreenLogs: false
    textWrap: false
    showTime: true
EOF

if [[ -e "$HOME/.k9s/config.yml" ]] && yq --exit-status eval '.k9s | has ("currentContext")' ~/.k9s/config.yml &>/dev/null; then
    printf '%s\n' "  currentContext: $(yq --indent 2 eval '.k9s.currentContext' ~/.k9s/config.yml)"
else
    printf '%s\n' '  currentContext:'
fi

if [[ -e "$HOME/.k9s/config.yml" ]] && yq --exit-status eval '.k9s | has ("currentCluster")' ~/.k9s/config.yml &>/dev/null; then
    printf '%s\n' "  currentCluster: $(yq --indent 2 eval '.k9s.currentCluster' ~/.k9s/config.yml)"
else
    printf '%s\n' '  currentCluster:'
fi

if [[ -e "$HOME/.k9s/config.yml" ]] && yq --exit-status eval '.k9s | has ("clusters")' ~/.k9s/config.yml &>/dev/null; then
    printf '%s\n' '  clusters:'
    yq --indent 2 eval '(.k9s.clusters)' ~/.k9s/config.yml | sed -e 's/^/    /'
else
  printf '%s\n' '  clusters: ""'
fi

cat << EOF
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
EOF

# vi: filetype=sh
```

**Comment by twpayne** [comment]
Thanks for the examples, hopefully the original question has been answered now.
