### ISSUE TITLE
timeout error with 'chezmoi apply' while editing file

### ISSUE THREAD

**Issue by ianisl** [twpayne/chezmoi#1092]
## Describe the bug / to reproduce

When editing a file (for instance ~/.vimrc) via `chezmoi edit`, `chezmoi apply` throws a "chezmoi: timeout" error if called while the file is still open in the editor.

If the edited file is closed, `chezmoi apply` runs without issues.

## Expected behavior

`chezmoi apply` should work when the edited file is still open for editing.

## Output of command with `--verbose`

```
$ chezmoi apply --verbose
chezmoi: timeout
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.0.3, commit c500b8a6fee41e66309fcf8ad2f5e94d73e5bed7, built at 2021-03-22T00:40:59Z, built by goreleaser
ok        os-arch              linux/amd64
warning   config-file          /home/<username>/.config/chezmoi/chezmoi.toml does not exist
ok        source-dir           /home/<username>/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries found in /home/<username>/.local/share/chezmoi
ok        dest-dir             /home/<username>is a directory
ok        shell                found /bin/bash
ok        editor               found /usr/bin/vim
ok        git-cli              found /usr/bin/git, version 2.17.1
ok        merge-cli            found /usr/bin/vimdiff
ok        gnupg-cli            found /usr/bin/gpg, version 2.2.4
warning   1password-cli        op not found in $PATH
warning   bitwarden-cli        bw not found in $PATH
warning   gopass-cli           gopass not found in $PATH
warning   keepassxc-cli        keepassxc-cli not found in $PATH
warning   keepassxc-db         not set
warning   lastpass-cli         lpass not found in $PATH
ok        pass-cli             found /usr/bin/pass, version 1.7.1
warning   vault-cli            vault not found in $PATH
warning   secret-cli           not set

```

## Additional context

I am running chezmoi inside an Ubuntu VM (18.04 LTS) and tmux. 
This behavior was not observed in chezmoi v1.

**Comment by twpayne** [comment]
Thanks for reporting this. This is almost certainly due to chezmoi locking its state file (where it records the checksums of the files it has written and which `run_once_` scripts have been run). `chezmoi edit` takes the lock which then causes `chezmoi apply` to time out trying to acquire it. I'll have a think on how to fix this. It might be as simple as `chezmoi edit` dropping the lock while the editor is running.

**Comment by ianisl** [comment]
Thanks for the quick answer (and btw, thanks for chezmoi!).
I wanted to add that I just noticed that the bug also occurs when running another `chezmoi edit` command (on a different file of course), not just `chezmoi apply`. This may affect other commands as well.

**Comment by fwSmit** [comment]
I ran into this bug as well, since I'm using `chezmoi edit` often in combination with `chezmoi apply --source-path`. For me it also stays locked after exiting with no obvious way to recover. Does removing the `chezmoistate.boltdb` work?
I would also recommend making the lock a separate file that can be easily removed. When for example the system crashes with bad timing you don't want chezmoi to stay locked either.

**Comment by mateuszkwiatkowski** [comment]
I also ran into this after I added oh-my-zsh installation to run_once script. Oh-my-zsh installation script dropped me into a new sub-shell and all chezmoi commands were broken until I left this sub-shell. I added `--unattended` option to installation script as [documented ](https://github.com/ohmyzsh/ohmyzsh#unattended-install) and it solved this issue for me.
