### ISSUE TITLE
Is it possible to "organize" `before_` scripts?

### ISSUE THREAD

**Issue by zb140** [twpayne/chezmoi#1097]
## What exactly are you trying to do?

Since before v2, I've had a folder of setup scripts that would install software and do some configuration actions, mostly written in Powershell (so they can be shared between OSes), plus a separate bootstrap script that would install my password manager and (on Linux) install Powershell.  Last night I decided to try to migrate the bootstrap script to a `once_before_` script.

## What have you tried so far?

I created `run_once_before_bootstrap-linux.sh` inside the same `setup` directory where my other scripts are stored.  The issue I ran into is that [`TargetStateScript.Apply`](https://github.com/twpayne/chezmoi/blob/master/internal/chezmoi/targetstateentry.go#L195) wants to set the CWD for the script to `~/setup`, which (of course) doesn't exist, since the whole point of `before_` is that it's before the main files are applied. 

## Additional context

Putting my `before_` script directly in the source directory works, of course, but I'd prefer not to have to do that, especially in the event that I end up with several of them.  Maybe it would be possible for `Apply` or `RunScript` to detect that the desired working directory doesn't exist and just use the destination dir instead?  I tried playing around with that a bit myself, but I couldn't quickly figure out how to determine what the destination was from inside `Apply`.  Of course, I'd love to hear any other thoughts!  I had a crazy idea to abuse the templating system by storing the setup code in `.chezmoitemplates/setup` and just templating it into a single top-level script, but that just feels differently dirty, rather than actually any better :smile:

**Comment by twpayne** [comment]
Great catch! I hadn't anticipated this, but what you say makes total sense.

> Maybe it would be possible for `Apply` or `RunScript` to detect that the desired working directory doesn't exist and just use the destination dir instead?

Yes, I think that's a reasonable default.





> I tried playing around with that a bit myself, but I couldn't quickly figure out how to determine what the destination was from inside `Apply`.

I would modify `RealSystem.RunScript`, and specifically [this line](https://github.com/twpayne/chezmoi/blob/master/internal/chezmoi/realsystem.go#L103). Since we don't know the user's home directory at this point in the code, I would work up the directory tree and execute the script in the first directory that exists, i.e. first try `dir`, then `dir.Dir()`, and so on.

Please also add tests in [`testdata/scripts/scriptdir_unix.txt`](https://github.com/twpayne/chezmoi/blob/master/testdata/scripts/scriptsubdir_unix.txt) and [`testdata/scripts/scriptdir_windows.txt`](https://github.com/twpayne/chezmoi/blob/master/testdata/scripts/scriptsubdir_windows.txt).

**Comment by zb140** [comment]
Sounds like a good idea; I'll put something together.
