### ISSUE TITLE
Files starting with .# in source are not actually ignored (chezmoi version v2.0.4)

### ISSUE THREAD

**Issue by tuh8888** [twpayne/chezmoi#1161]
## Describe the bug

Chezmoi is not actually ignoring files that start with a . that are found in source. From the [reference page](https://www.chezmoi.io/docs/reference/):

> chezmoi ignores all files and directories in the source directory that begin with a . with the exception of files and directories that begin with .chezmoi.

For me, this is particularly annoying when editing my source dotfiles from Emacs since it creates lockfiles called `.#filename.ext` which are symlinks.

## To reproduce

  1. Opened source directory file in emacs. `emacs ~/.local/share/chezmoi/dot_aliases` 
  2. Made edit. 
  3. Did not save buffer. 
  4. `chezmoi diff` &rarr; `chezmoi: stat /home/user/.local/share/chezmoi/.#dot_aliases: no such file or directory`

## Expected behavior

Chezmoi should fully ignore (i.e. not touch) all files starting with `.`, including Emacs lockfiles.

## Output of command with `--verbose`

```
$ chezmoi diff --verbose
chezmoi: stat /home/user/.local/share/chezmoi/.#dot_aliases: no such file or directory
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
```

## Additional context

I've written about a solution from the Emacs side [here](https://github.com/tuh8888/chezmoi.el#lock-files) which disables lockfile creation. However, these lockfiles serve a purpose, and I am not sure why chezmoi needs to be touching these files if it is supposed to be ignoring them.

**Comment by twpayne** [comment]
Thanks for the detailed report!

What's happening here is that emacs is being a bit naughty by using symlinks that point to non-existent files (i.e. invalid symlinks) as lockfiles and chezmoi is following the symlink before it's deciding whether to ignore the file or not, hence the "no such file or directory" error from chezmoi.

The fix is for chezmoi to check the file's name before following it if is a symlink. PR coming up...
