### ISSUE TITLE
64 bit install for chezmoi v2.0.10 uses ARM architecture

### ISSUE THREAD

**Issue by Tyrubias** [twpayne/chezmoi#1164]
When  `chezmoi` was updated to `v2.0.10`, the `amd64` installer was replaced by a ARM installer. This leaves chezmoi unable to be run on most Windows computers.

**Comment by twpayne** [comment]
Thanks for reporting this and happy to hear the chezmoi is being installed with Scoop :)

I'm reasonably sure that this is due to a bug in goreleaser. I've opened https://github.com/goreleaser/goreleaser/issues/2171.

In the short term I've also patched the Scoop bucket to use the Windows `amd64` build (https://github.com/twpayne/scoop-bucket/commit/279aa0bfd54c6b0511738ca15ef4d421fd95ec4f). Would you be able to test that installing chezmoi via Scoop now works?

**Comment by twpayne** [comment]
Hopefully https://github.com/goreleaser/goreleaser/pull/2172 will fix the underlying issue.

**Comment by Tyrubias** [comment]
Thank you so much! I'll check tonight and confirm it works.

**Comment by Tyrubias** [comment]
Installing now works! Thank you again.
