### ISSUE TITLE
New template function: print

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1217]
## Is your feature request related to a problem? Please describe.

I'm using a chezmoi configuration as stated at https://github.com/twpayne/chezmoi/issues/1154#issue-857212645, and now we have a new option to use as `chezmoi init --data=false` which I can use if I want to reset my previously set data.

However, for those who don't know, I'd like to print a tip while setting up chezmoi, so they know how to reset their data if needed.

## Describe the solution you'd like

A new function which I could use like:

```
{{- $email := get . "email" -}}
{{- if not $email -}}
{{- $email = promptString "email" -}}
{{- end -}}

{{- print "Use `chezmoi data` to view your information, and use `chezmoi init --data=false` to re-enter it." -}}

[data]
email = "{{ $email }}"
```

## Describe alternatives you've considered

dotfiles/run_always_echo_tip.sh

```sh
#!/bin/sh

echo "Use `chezmoi data` to view your information, and use `chezmoi init --data=false` to re-enter it."
```

## Additional context

Actually I'm quite happy with the alternative approach, but I just wanted to raise this so we can discuss if it's a good idea or not.

**Comment by twpayne** [comment]
I think it's a useful addition. Currently the only way to communicate with the user is through the prompt to the `prompt*` functions, and it's reasonable that users might want to print more information.

Currently `text/template` has a `printf` function which returns a formatted string, so I'd be tempted to call the function `printToStdout` to make it clear that it prints to stdout rather than returning a value. There is some relation here to the `stdinIsATTY` function.

How does `printToStdout` sound?

**Comment by felipecrs** [comment]
It sounds good to me. Other options are:

consoleLog
echo

But your suggestion seems better due to the relationship with the other function you said.
