### ISSUE TITLE
Git repository as destination

### ISSUE THREAD

**Issue by georgebushfourtwenty** [twpayne/chezmoi#1221]
## What exactly are you trying to do?
Suppose I need to track a directory `dir1`.
```
cd dir
chezmoi add --recursive --destination . .
```
Now take another directory `dir2`. This time, `dir2` is a git repository.
I don't want to track `dir2/.git` or any of the files which are ignored by the `dir2` repository.

// Describe in as much detail as possible.

## What have you tried so far?
```
cd dir2
chezmoi add --recursive --destination . .
chezmoi forget --destination . .git
chezmoi forget --destination . <all git-ignored files>
```
Is there a simpler solution?
// Describe what you have tried so far.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose`

```
$ chezmoi command --verbose
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
```

**Comment by twpayne** [comment]
Thanks for the clear problem statement :)

Is the git repo that you want to add hosted on GitHub? If so, consider importing the files from an archive generated by GitHub (which doesn't include `.git`) instead of adding the files from the local filesystem. See [how to import archives](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#import-archives) for an example.

Alternatively, if you need to import from a local git repo, then consider using git to generate the archive and then importing this into git. This would look something like (warning: untested code, exact commands may differ slightly):

    ( cd dir2 && git archive --output=/tmp/dir2.tar master )
    mkdir $(chezmoi source-path)/dir2
    chezmoi import --destination=$HOME/dir2 /tmp/dir2.tar

Would this be sufficient for you?

**Comment by georgebushfourtwenty** [comment]
Thank you, I suppose it is sufficient.

**Comment by twpayne** [comment]
Great! For info, it would be possible for chezmoi to perform this archive creation and import transparently, for example by adding a `--from-git` flag to `chezmoi add` so you could do something like:

    chezmoi add --from-git dir2

However, I'm considering adding a richer system for importing files (see #662), so I'd prefer to include this sort of functionality into that, rather than add a new flag to `chezmoi add` at this point in time.

**Comment by georgebushfourtwenty** [comment]
That's great! My only is concern is about making a copy of the git repository because it can be huge.
