### ISSUE TITLE
Add --prompt flag to add command

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#123]
[CGamesPlay on Hacker News suggested](https://news.ycombinator.com/item?id=18904367):

> New files in tracked directories should be listed with the ability to import them individually (presently you can only do `chezmoi add -r` and deal with the consequences).

**Comment by CGamesPlay** [comment]
So, after thinking about this more, I think what is really needed is a "reverse-apply" command. Something like this:

- If `apply` would overwrite a file in the target state, instead update the source state. Not sure how to handle templated files, but an error message with diff would probably be sufficient.
- If `apply` would delete a file in an `exact_` directory in the target state, instead add the file to the source state.

Combining this with #124 would basically let me run this operation whenever I want to sync my preferences to other machines using something like this:

- Modify files in the target state (e.g. install some package with fisher or Vundle).
- Use those settings locally for a while to confirm I like them.
- Do the reverse apply operation to pick up changes in chezmoi.
- Make any changes to the source state that I need to (e.g. maybe I need this change to be in a template block instead of a flat file).

**Comment by kkirsche** [comment]
I believe this has been added now. Should this be closed?

**Comment by twpayne** [comment]
The prompt flag has been added, but I still need to think through @CGamesPlay's suggestions before working out whether to close this issue.

**Comment by twpayne** [comment]
I think the recently-added [`re-add` command](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#re-add) matches @CGamesPlay's great idea.
