### ISSUE TITLE
Add option for symmetric encryption for age

### ISSUE THREAD

**Issue by trinklup** [twpayne/chezmoi#1242]
Transferring a key in order to decrypt dotfiles is often inconvenient. Symmetric encryption solves that by using only a single password to encrypt and decrypt files. Symmetric encryption for gpg was implemented in #333. It would be nice to have the feature for age as well.

**Comment by twpayne** [comment]
Thanks for the suggestion! This is done in #1244. I'll create a new release of chezmoi in a few days.

**Comment by trinklup** [comment]
@twpayne: Thank you so much for implementing this. But, since it is required to specify a key to be able to encrypt and decrypt, doesn't it defeat the purpose of using symmetric encryption? If I have to transfer dotfiles to a new machine, all I have to do is type a passphrase. For example, I can use `age --encrypt -p < file > file.age` to encrypt a file and `age --decrypt < file.age > file` to decrypt it without requiring anything other than a passphrase.

**Comment by twpayne** [comment]
Ah, I see: the desire is for encryption with a passphrase (which happens to be symmetric) rather than symmetric encryption with a private key.

This is now implemented in #1245, but I think usability will suffer a little here. Specifically, you'll need to enter the passphrase not only when you add a file with `chezmoi add --encrypt` but whenever chezmoi needs to decrypt it, which is likely more often than you think. For example, chezmoi needs to decrypt the file whenever you run `chezmoi apply`, `chezmoi diff`, or `chezmoi status`, as well as in many other cases. Consequently you'll be requested for your passphrase a lot.

You can use the `--exclude=encrypted` option to many of these commands to make chezmoi skip encrypted files, but this requires extra typing (or some shell aliases) instead.
