### ISSUE TITLE
Unknown groupid issue on OS X

### ISSUE THREAD

**Issue by peterloron** [twpayne/chezmoi#125]
I'm running chezmoi 1.0.0 (via homebrew) on MacOS X 10.14.2. When I try to add a file, I get this error:

`chezmoi: group: unknown groupid 1493692218`

Our machines are joined to an AD domain. I looked at issue #65 and #72, however it looks like this may only resolve the issue on Linux.

Anything I can do to assist, please let me know. Thanks!

**Comment by twpayne** [comment]
Thanks for the bug report!

The underlying issue is that `os/user.LookupGroupId` is only reliable when CGO is enabled. `chezmoi` is built with [`goreleaser`](https://goreleaser.com) (awesome project!) which does [not support CGO](https://goreleaser.com/cgo/) when cross-compiling. `chezmoi` uses `goreleaser` on travis-ci.org (running Linux) and so can use CGO when building Linux binaries, but not macOS binaries.

I've updated the code to silently ignore errors from `os/user.LookupGroupId` if CGO is disabled. This means that the `.chezmoi.group` template variable will not be available, but frankly it's unlikely that you're using it anyway :)

I'll do a new release including this fix within the next 12 hours.

Thanks again for the detailed bug report!

**Comment by peterloron** [comment]
Awesome! Thanks!
