### ISSUE TITLE
map has not entry for key "idLike"

### ISSUE THREAD

**Issue by ram02z** [twpayne/chezmoi#1297]
## Describe the bug

I have a run_once_* script in my chezmoi configuration, which works well for Debian and Arch. However, when I tried it on Void Linux, I get the error from the title. When I run `chezmoi data`, it would appear that `idLike` is missing from the table, which makes sense. Below is the relevant script.
https://github.com/ram02z/dotfiles/blob/master/run_once_package_setup.sh.tmpl#L11-L17

## To reproduce

Try to run the my script on Void Linux.

## Expected behavior

The script runs without the error. Alternatively, I really only need a solution that will allow me to check if a distro is Debian based, since I work on both Debian and Ubuntu and have different configurations for the two.

## Additional context

Chezmoi version v2.1.0

**Comment by twpayne** [comment]
This is an unfortunate intersection of `chezmoi data` producing different data on different machines (`idLike` is only included in `.chezmoi.osRelease` if it is present in `/etc/os-release`) and chezmoi using Go's `text/template` language in its strictest mode by default.

Some work-arounds:

1. Use a less strict mode for templates, e.g. set `template.options = ["missingkey=zero"]` in chezmoi's configuration file. More info [here](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#template-execution).
2. Use the [`get` template function](https://masterminds.github.io/sprig/dicts.html) instead of dotted notation, i.e. replace `if (eq .chezmoi.osRelease.idLike "arch")` with `if (eq (get .chezmoi.osRelease "idLike") "arch")`.

⚠️ Above is untested, but should work.

**Comment by ram02z** [comment]
@twpayne I like the concept of the second workaround, however, I am met with the following template error: `wrong type for value; expected map[string]interface {}; got map[string]string`

**Comment by twpayne** [comment]
The second workaround should now work thanks to #1298. I'll release a new version of chezmoi in the next few hours.
