### ISSUE TITLE
Dynamic Template Variable Generation

### ISSUE THREAD

**Issue by adamchristiansen** [twpayne/chezmoi#1342]
## Is your feature request related to a problem? Please describe.

There should be a way to dynamically generate data for use in templates. This is useful for a number of things, but I will illustrate with a simple example that I will carry through the rest of the proposal. Consider a very simple case where templates are used to generate a color scheme. Maybe there is something like this in a `.chezmoidata.yaml` file:

```yaml
color:
  red: "ff0000"
  green: "00ff00"
  blue: "00ff00"
```

This is fine for a simple case, but lets say I have many colors and some other data, and I want them in HEX, RGB, and whatever other formats, so I want this structure transformed into something like:

```yaml
color:
  red:
    hex:
      rgb: "ff0000"
      bgr: "0000ff"
      r: "ff"
      g: "00"
      b: "00"
    rgb:
      r: 255
      g: 0
      b: 0
    dec:
      r: 1.000
      g: 0.000
      b: 0.000
  green:
    # Same thing
  blue:
    # Same thing
```

Now I have access to the variable `.color.red.dec.r`, for config files that require colors in decimal RGB in separate components (e.g. iTerm2).

Managing this gets out of hand very quickly, especially since most color schemes have at least 16 colors. This is even more cumbersome if I use multiple color schemes and I want to swap them on a whim. I am proposing a solution where these values can be generated automatically by only changing one line in the `.chezmoidata.<format>` file.

## Describe the solution you'd like

I think there should be a way to dynamically generate data.

### Option 1: Generate Template Variables From a Script

This is what I think is the most elegant solution. For example, I could have in my `.chezmoidata.yaml`:

```yaml
colorscheme: my-awesome-colorscheme
```

When `chezmoi` runs, it looks for a script with the `data_` attribute (the attribute name could be something else), and runs all of those first using the variables loaded from the `chezmoi` configs. Suppose there is a file named `run_data_50-colors.sh.tmpl` with contents like:

```sh
#!/usr/bin/env sh

colorscheme={{- .colorscheme | quote -}}

# Do something with $colorscheme and print data on stdout
# that is included in the chezmoi data
```

This script would then print out the very long YAML that I wrote in the second code block, and that data would be added as template variables in `chezmoi`, and on conflicts, overwriting any that were previously defined.

This strategy could be useful for a whole bunch of other things, such as getting information about the system. Maybe you have a script which queries `/etc/os-release` on Linux to get some OS information, or queries the available hardware and sets template variables based on that so you can template out which network interfaces are available, and so on.

### Option 2: Process `.chezmoidata.<format>` as a Template

Allow `.chezmoidata.<format>` to have the `.tmpl` suffix so that it can include other files. For example, its contents may look like:

```yaml
{{ include (joinPath .chezmoi.sourceDir ".colorschemes/my-awesome-colorscheme.yaml") }}
``` 

This is less powerful since it does not have that ability to run arbitrary scripts. A major limitation of this approach is that you cannot use scripts with the `before_` attribute to dynamically generate data to include, since the `.chezmoidata.<format>` file must be evaluated before any scripts can be run.

### Alternative 1: Manually Edit `.chezmoidata.<format>`

The procedure goes something like this:

1. Run my own script to generate config data.
2. Copy the data and paste it in `.chezmoidata.<format>`.
3. Repeat from step 1 for every data generation script I have.

This is obviously cumbersome and not ideal.

> Alternatively, I could edit `~/.config/chezmoi/chezmoi.<format>`.

### Alternative 2: Script to Edit `.chezmoidata.<format>`.

In this approach, I would have a script that edits the value of `.chezmoidata.<format>`. to define my own variables for templates. I would have to invoke this manually every time that I make a change to to my data generation scripts, rather than `chezmoi` being able to automatically discover the new variables. The procedure would look something like this:

1. Edit my `.colorschemes/generate-my-awesome-colorscheme.sh`
2. Run `.colorschemes/generate-my-awesome-colorscheme.sh` so that it modifies `.chezmoidata.<format>`.
3. Run any `chezmoi` command, such as `chezmoi data`, and it sees the new variables.
4. Repeat from step 1 if anything changes in my variable generation script.

> Alternatively, the script could modify `~/.config/chezmoi/chezmoi.<format>`.

**Comment by twpayne** [comment]
Thank you for the very well thought through proposal!

A couple of alternative approaches:

## Use the `output` and `fromJson` template functions to generate data

These two existing template functions can be used to generate template data dynamically. Consider something like:

```
{{- $red := output "generate-color-formats" .color.red | fromJson -}}
decimalRed = {{ $red.dec.r }}
```

where `generate-color-formats` is a program that takes a hex-encoded color as an argument and writes JSON-encoded structured data about that color to the standard output. For example, given the argument `#ff0000`, `generate-color-formats` would produce:

```json
{
  "hex": {
    "rgb": "ff0000",
    "bgr": "0000ff",
    "r": "ff",
    "g": "00",
    "b": "00"
  },
  "rgb": {
    "r": 255,
    "g": 0,
    "b": 0
  },
  "dec": {
    "r": 1.000,
    "g": 0.000,
    "b": 0.000
  }
}
```

`output` returns the output of the command as a string, and `fromJson` parses that string as a structured JSON value and returns it. Assigning the result to a variable (`$red` in the example) allows the result to be re-used.

A possible downside of this approach is that you might need to bootstrap the installation of the `generate-color-formats` command before it is called, and easy re-use across multiple template might be a tricky. The [`.chezmoitemplates` directory](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#chezmoitemplates) might be helpful here.

## Add some template functions for handling color to chezmoi

Colors are a common part of dotfiles, and it may be that it's worth adding some specific template functions to handle them. For example, the `generate-color-formats` script described above could be a `colorFormats` template function so you could write something like:

    decimalRed = {{ colorFormats .color.red | .dec.r }}

Thoughts?

**Comment by AdamChristiansen** [comment]
Thank for these ideas. I'll address suggestion 2 first and then 1.

### Add some template functions for handling color to chezmoi

This could be useful for simple color scheme implementations. I would say overall it's not as powerful as the first option. I think it's a fine idea if you don't mind crowding the templating namespace, however, I personally would not use it to solve my problem.

### Use the `output` and `fromJson` template functions to generate data

This is pretty good and a clever solution that never crossed my mind. I'll provide a minimal working example of what I did. Here's was my `~/local/share/chezmoi` directory looks like:

```
.chezmoidata.yaml
colorsample.tmpl
_color/
|   generate.py
|   my-colorscheme.json
|   my-other-colorescheme.json
|   ...
```

The `_color/*-colorscheme.json` files contain an object with keys that just have the hex colors as strings. The `_color/generate.py` script operates over one of these and makes the blown up format that I am trying to use (e.g. with access to `.color.red.rgb.r` and so on).

The `.chezmoidata.yaml` file has a line like:

```yaml
colorscheme: my-other-colorscheme
```

Then in `colorsample.tmpl`, I have something like

```
{{- $color := output "python3" (joinPath .chezmoi.sourceDir "_color/generate.py") .colorscheme | fromJson -}}

red = {{ $color.red.hex.rgb }}
```

When I run a `chezmoi apply`, I then get a file in my home directory called `colorsample` and the contents are `red = ff0000` just as I expect.

### What I would really like

This solution works and I will use it, however, I think it could be a bit nicer. It would be nice to be able to have a `.chezmoitemplates/color` file with the contents

```
{{- $color := output "python3" (joinPath .chezmoi.sourceDir "_color/generate.py") .colorscheme | fromJson -}}
```

and have the variable `$color` be exporter. That way I can use the following in my `colorsample.tmpl` file:

```
{{- template "color" . -}}

red = {{ $color.red.hex.rgb }}
```

so I don't need to include the very long invocation of `python3 ...` in every file that wants access to the `$color` variable - I simply include the template. That way if the invocation of the variable generation script ever changes, it only needs to be updated in one place and no other files need to know about the change.

This must be limitation of Go templates, right? I am not familiar with Go so I can't say for sure. Is there a way to include a template and have it evaluated **after** inclusion, rather than have the template evaluated first and then the result is included in the generated file?

**Comment by AdamChristiansen** [comment]
In case anyone is trying to do something similar, here's a update with a cleaner approach that I have implemented.

I created a script named `run_before_00-generate-colors.sh.tmpl`, that creates the file `_color/color.json` with my full color scheme definition as described above. Then in any file that requires access to colors, I stick

```
{{- $color := include "_color/color.json" | mustFromJson -}}
```

on the first line. This abstracts the color generation to the file `run_before_00-generate-colors.sh.tmpl`, so the templates do not need to know anything about the color generation procedure other than the path to include. To see in detail what this looks like, you can check my [dotfiles](https://github.com/AdamChristiansen/dotfiles).

I think this issue can be considered solved, unless there is interest in implementing some features that came out of this discussion.
