### ISSUE TITLE
import from existing repository

### ISSUE THREAD

**Issue by greg-minshall** [twpayne/chezmoi#1442]
i have some of my tracked dotfiles in a git repository, some in an RCS repository (in both cases, intermixed with other files).  i'd like to import them to chezmoi, along with their history.

i've googled, read some of the docs, read the FAQ, and not found the answer.

apologies if in the HOWTO, "Import Archives"  (probably along with spitting out the dotfiles into their own git/RCS repositories) is the answer.  i didn't quite understand that "import archives" was doing, the contents of the .tar.gz file did't enlighten me, etc.

cheers.

**Comment by twpayne** [comment]
> i'd like to import them to chezmoi, along with their history.

"along with their history" makes this is a version control problem rather than a chezmoi problem :) chezmoi defers all its version control to git.

If you want to import your dotfiles into chezmoi *without history* then the easiest way to do this is to run your current dotfile manager, and then run `chezmoi add -f $DOTFILE` on each dotfile that you want chezmoi to manage. The `-f` copes with dotfile managers that use symlinks (see [why you shouldn't use symlinks for your dotfiles](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md#why-doesnt-chezmoi-use-symlinks-like-gnu-stow)).

> i have some of my tracked dotfiles in a git repository, some in an RCS repository (in both cases, intermixed with other files).

As you do want to preserve history, and your dotfiles are spread over multiple separate repositories, I would suggest the following steps:

1. [Convert your RCS dotfile repos into git repos using an appropriate tool](https://duckduckgo.com/?q=rcs+to+git+converter). Now you should have multiple git repos.
2. [Merge your multiple git repos into one](https://duckduckgo.com/?q=merge+multiple+git+repos).
3. Manually modify the resulting git repo to be in [chezmoi's format](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#source-state-attributes), by for example:
    * Renaming files you want to keep, for example running `git mv .bashrc dot_bashrc`.
    * Adding the intermixed files that you don't want to keep to [`.chezmoiignore`](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#chezmoiignore) to prevent chezmoi from manifesting them in your home directory.

After following these steps, you should have a single chezmoi-compatible dotfiles repo with all the history from your multiple previous repos.

> apologies if in the HOWTO, "Import Archives" (probably along with spitting out the dotfiles into their own git/RCS repositories) is the answer. i didn't quite understand that "import archives" was doing, the contents of the .tar.gz file did't enlighten me, etc.

chezmoi's `import` command snapshots the current contents of an archive in to the source state. It doesn't deal with any kind of history.

Hope this helps, please re-open if needed.

**Comment by greg-minshall** [comment]
@twpayne thanks.  if i run into insurmountable mole hills, i'll report back.  :)  cheers!
