### ISSUE TITLE
Should `~/.config/chezmoi` be tracked?

### ISSUE THREAD

**Issue by hybras** [twpayne/chezmoi#1490]
I did `chez add ~/.config` and then `chez forget $stuff_i_dont_want_to_track`. I didn't realize chez's own config was in there (which makes sense, my mistake). I see a config file and a db. Which of these should chezmoi track?

## Where else have you checked for solutions?

* [X] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [X] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

**Comment by twpayne** [comment]
Neither of these should be tracked by chezmoi.

The config file should be generated from a config file template, [see this how-to entry](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#create-a-config-file-on-a-new-machine-automatically).

The database contains chezmoi's local state, e.g. which `run_once_` scripts have been run and checksums of the files managed by chezmoi so chezmoi can detect if they have been modified since chezmoi last wrote them.

**Comment by twpayne** [comment]
Hope this answers your question, please re-open if needed.

**Comment by hybras** [comment]
thank you
