### ISSUE TITLE
No git repo created when doing `chezmoi init` in fish shell.

### ISSUE THREAD

**Issue by kaddkaka** [twpayne/chezmoi#1629]
## What exactly are you trying to do?

I'm trying to use chezmoi for the first time and following the [Quickstart](https://github.com/twpayne/chezmoi/blob/master/docs/QUICKSTART.md) with the `fish` shell. After the `chezmoi cd` a new shell is started at path `.local/share/chezmoi` but there is no git repo created and no `.git` folder there.

It works if I perform `chezmoi init` command in bash. Quote from the Reference for `init`:

> First, if the source directory is not already contain a repository, then if repo is given it is checked out into the source directory, otherwise a new repository is initialized in the source directory.

**Comment by felipecrs** [comment]
![image](https://user-images.githubusercontent.com/29582865/141817417-89d2d145-ba7f-44bd-a582-b3fb51b06711.png)

I can't replicate your issue with by using https://github.com/dideler/docker-fish-shell. Are you doing anything else special? If not, can you try to do the same with the docker image mentioned so that we isolate if your issue is only in your environment?

```
$ docker run --rm -it dideler/fish-shell
$ apt update && apt install curl -y
$ curl -fsLS git.io/chezmoi | sh -
$ chezmoi init
$ chezmoi cd
$ ls -la
```

**Comment by twpayne** [comment]
This sounds like it is working as intended and documented, i.e. `chezmoi init` creates a git repo in the source directory and `chezmoi cd` changes to the source directory but does not create a git repo.

Please re-open if I missed something.

**Comment by kaddkaka** [comment]
@twpayne the problem was that `chezmoi init` didn't create the git repo. But I will see if I can reproduce the issue with a docker as per above comment.
