### ISSUE TITLE
Why not `~/Library/Application\ Support/chezmoi` as default path on osx?

### ISSUE THREAD

**Issue by ZerdoX-x** [twpayne/chezmoi#1630]
## What exactly are you trying to do?
Trying to install and use chezmoi my first time

## What have you tried so far?
Adding alias:
`chezmoi="chezmoi --source ~/Library/Application\ Support/chezmoi"`

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of `chezmoi doctor`

```console
RESULT   CHECK                MESSAGE
ok       version              v2.7.5, commit 53bb61524468afe3262d6d8089fdc6912dbccb34, built at 2021-11-07T17:04:07Z, built by Homebrew
ok       os-arch              darwin/arm64
ok       executable           /opt/homebrew/bin/chezmoi
ok       config-file          no config file found
error    source-dir           open ~/.local/share/chezmoi: no such file or directory
ok       suspicious-entries   ~/.local/share/chezmoi: no such file or directory
error    working-tree         open ~/.local/share/chezmoi: no such file or directory
ok       dest-dir             ~ is a directory
ok       shell                found /bin/zsh
ok       edit-command         found /usr/bin/vi
ok       umask                022
ok       git-command          found /usr/bin/git, version 2.30.1
ok       merge-command        found /usr/bin/vimdiff
ok       age-command          age not found in $PATH
ok       gpg-command          found /opt/homebrew/bin/gpg, version 2.3.3
info     pinentry-command     not set
info     1password-command    op not found in $PATH
info     bitwarden-command    bw not found in $PATH
info     gopass-command       gopass not found in $PATH
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-command     lpass not found in $PATH
info     pass-command         pass not found in $PATH
info     vault-command        vault not found in $PATH
info     secret-command       not set
```

## Additional context
https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html

I know that `.local/share` is a part from XDG base dir specs on linux, but osx has it's own specs and chezmoi supports osx, then why it doesn't store files by using places that os provide?

**Comment by twpayne** [comment]
Thank you for opening this issue and thank you for the good point!

The simple reason is that so many command line applications on macOS (e.g. git) follow the XDG specification instead of the macOS specifications, that I didn't think about following the macOS specifications.

This is potentially fairly easy to fix: basically, on macOS, chezmoi should check `~/Library/Application\ Support/chezmoi` first.

A question. chezmoi currently has multiple config directories:
* `~/.local/share/chezmoi` contains the source state which is the same across multiple machines.
* `~/.config/chezmoi` contains the machine-specific configuration.
* `~/.cache/chezmoi` contains cached data.
If chezmoi were to follow the macOS Library Directory Details, in which two directories should it put the source state and the machine-specific configuration? They should not be the same directory.

**Comment by twpayne** [comment]
Closing this for now due to lack of response. Please re-open if needed.

**Comment by twpayne** [comment]
A recent post on this topic: https://becca.ooo/blog/macos-dotfiles/
