### ISSUE TITLE
Allow templates to be used in `.chezmoidata`

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1663]
## Is your feature request related to a problem? Please describe.

`.chezmoidata` is the only way to store data between apply calls, as `data` from the config file is only generated during `init` command. It would be super if templates could be used inside of `.chezmoidata`, so that we can persist some information more dynamically.

## Describe the solution you'd like

`.chezmoidata` to support templating.

## Describe alternatives you've considered

The only one I found for now was to create files, as @MuXiu1997 suggested at [here](https://github.com/twpayne/chezmoi/issues/1619#issuecomment-976099389). But it's kind a workaround, it has the caveat of not being cross platform, and relying on two script calls.

## Additional context

One example of a use case is well described at https://github.com/twpayne/chezmoi/issues/1619#issuecomment-974688405. Another one, would be something describe at https://github.com/twpayne/chezmoi/issues/1662#issuecomment-976483008, with, for example, a variable inside of data called `lastTimeExecuted: 1234`.

**Comment by MuXiu1997** [comment]
I'm not sure it's easy to implement this.
Maybe we can provide template functions `cacheSet <key> <value>` and `cacheGet <key> [default]` who share the cache in one command declaration cycle, I think this would be easy to implement

**Comment by MuXiu1997** [comment]
I prefer to introduce new features rather than change the existing design

`.chezmoicomputed.<format>`
e.g. `.chezmoicomputed.yaml`
```yaml
dockerVersion: 
  value: {{ xxxxxxxxxxx }}
  refreshPeriod: 24h
```

just like `.chezmoiexternal.<format>`
chezmoi will cache value. The duration refreshPeriod field specifies how often chezmoi will re-compute the value
force: `--refresh-computed`

**Comment by felipecrs** [comment]
This is cool, but I think it's too tailored for a single use case. Allowing templates to be used in `.chezmoidata` could be useful for much more cases.

But what you are saying is right. We can consider `.chezmoidynamicdata.yaml`, which would differ from `.chezmoidata` in 2 things:

1. Templates can be used
2. `.chezmoitemplates` is read before it (currently it's the opposite)

However, 1. adding support for templates in `.chezmoidata` should not be a breaking change by itself. And 2. I wonder what's the use case of reading `.chezmoidata.yaml` before `.chezmoitemplate`. The current test does not seem meaningful:

https://github.com/twpayne/chezmoi/pull/1645/files#diff-7689b198c98fdb2188a204891487161b277a157cc39ba2b451b70b54780ef90cR13-R31

**Comment by twpayne** [comment]
> `.chezmoidata` is the only way to store data between apply calls.

This statement is not correct. `.chezmoidata` is for data that is shared across all machines, which is why it is in the source state. In contrast, the `data` section of the config file is for data that is specific to single machine. Running `chezmoi apply` most definitely should not modify the source state.

> The current test does not seem meaningful:

The test linked to demonstrates:
1. Data stored in `.chezmoidata.toml`.
2. A template in `.chezmoitemplates`.
3. `.chezmoiignore` being a template that uses the template from`.chezmoitemplates` passing in the data from `.chezmoidata.toml`.
Overall, this demonstrates that `.chezmoiignore` can use templates from `.chezmoitemplates`, which was not the case before the PR.

If you want to store data between `apply` calls then you can do so anywhere in the filesystem using the `output` template function to invoke a non-idempotent command that has the side effects of writing/reading the data. This is a horrible hack.

Fundamentally I think https://github.com/twpayne/chezmoi/issues/1662#issuecomment-977486224 applies here:

> chezmoi uses `text/template` as a *templating* language. `text/template` is *not* a full programming language.

**Comment by felipecrs** [comment]
> This is a horrible hack.

So perhaps a new set of functions, like proposed by @MuXiu1997 at some point for `getCacheKey` or `setCacheKey`, which would store data during apply calls and would provide a way to set variables globally at runtime. What do you think?

**Comment by twpayne** [comment]
> So perhaps a new set of functions, like proposed by @MuXiu1997 [at some point](https://github.com/twpayne/chezmoi/issues/1619#issuecomment-976532769) for `cacheGet` or `cacheSet`, which would store data during apply calls and would provide a way to set variables globally at runtime. What do you think?
> 
> Or perhaps just a `.global` dict which we could use as needed.

Global mutable state leads to tight coupling and fragile, hard-to-debug systems. If people want to add their own hacks around this then that's fine, but I'm not going to add such functionality to chezmoi.
