### ISSUE TITLE
Handle directory symlinks

### ISSUE THREAD

**Issue by jhillyerd** [twpayne/chezmoi#17]
I was impressed that chezmoi handled symlinked files placed by my previous dotfile manager.  But it seems to have trouble with directory symlinks:
```
$ ls -l ~/.config/omf
lrwxrwxrwx 1 james users 25 Nov 10 16:16 /home/james/.config/omf -> /home/james/.dotfiles/omf

$ ls -ld ~/.dotfiles/omf
drwxr-xr-x 3 james users 4096 Nov 12 22:27 /home/james/.dotfiles/omf

$ chezmoi add -r ~/.config/omf
Error: .config/omf: not a regular file or directory
Usage:
...
2018/11/24 11:28:51 .config/omf: not a regular file or directory

$ chezmoi add -r ~/.config/omf/
Error: .config/omf: not a regular file or directory
Usage:
...
2018/11/24 11:28:53 .config/omf: not a regular file or directory
```

**Comment by jhillyerd** [comment]
Workaround: `find .config/omf/ -type f -exec chezmoi add '{}' \;`

**Comment by jhillyerd** [comment]
Also gets confused when applying to a symlinked directory (i3 is a symlink to another directory):
```
2018/11/24 11:48:14 mkdir /home/james/.config/i3: file exists
```

I think it's best that this does fail, but the error should explain why.

**Comment by twpayne** [comment]
Ah, symlinks aren't handled at the moment, so anything that does work works by coincidence, not design. This is party because the filesystem abstraction library (`github.com/absfs/afero`) doesn't support them in its in-memory filesystem which `chezmoi` uses for its tests.

I'll switch the tests over to using temporary files which means that I should then be able to add and test proper symlink support.
