### ISSUE TITLE
Documentation about source directory is a bit confusing

### ISSUE THREAD

**Issue by jpambrun** [twpayne/chezmoi#171]
The documentation about source directory is confusing, we can read:

```
The source directory is where chezmoi stores the source state, by default ~/.config/share/chezmoi
```

then

```
> chezmoi add ~/.bashrc
This will create the source directory ~/.local/share/chezmoi
```

then later

```
Managing your ~/.chezmoi directory with version control
```

which I assume also references the source directory.

I didn't try chezmoi yet, but I am unsure where the source is going to be between `~/.config/share/chezmoi`, `~/.local/share/chezmoi` or `~/.chezmoi` and it makes understanding the documentation difficult.

**Comment by twpayne** [comment]
Thanks so much for the feedback! You're right. The back story is that `chezmoi` used to use `~/.chezmoi` to store its source state, but since version 1.0.0 has followed the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) exclusively and so stores the source state in `~/.local/share/chezmoi`. The documentation is out of date here. I'll fix it.
