### ISSUE TITLE
After use "chezmoi -v apply", can I recovery my file?

### ISSUE THREAD

**Issue by wowow005** [twpayne/chezmoi#1779]
I add some new file, than use "chezmoi -v apply" to overwrite original file from Github's remote repositories.

How to recovery this modification? 

Git's log don't have this operation...

**Comment by wowow005** [comment]
Is there a way to recover?

**Comment by twpayne** [comment]
As you used `chezmoi -v apply`, the modification is visible in the output of the command. You will have seen the difference between the new and original files. chezmoi will also have warned you that the contents of the file had changed since chezmoi last wrote it.

If you no longer have the output of the run of `chezmoi -v apply` that changed the file, you will need to restore the original file from backup.

**Comment by wowow005** [comment]
So how to modify local file ? Only use `chezmoi edit`? Use other way to modify local dotfile, than use `chezmoi -v apply` will overwrite original file from Github's remote repositories? It's right?

**Comment by twpayne** [comment]
See [this FAQ entry](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md#how-do-i-edit-my-dotfiles-with-chezmoi) and [this FAQ entry](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md#why-do-i-get-a-blank-buffer-when-running-chezmoi-edit).
