### ISSUE TITLE
Improve `chezmoi apply` with shortcuts and overview

### ISSUE THREAD

**Issue by gdevenyi** [twpayne/chezmoi#1809]
## Is your feature request related to a problem? Please describe.

Currently, `chezmoi apply` gives a prompt like this:
```
$ chezmoi apply
.bashrc has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]?
```

After testing, it became apparent that short forms, `o` work for the commands, but its not made obvious in the prompt.

## Describe the solution you'd like

Change the prompt to highlight the short command
```
.bashrc has changed since chezmoi last wrote it [(d)iff,(o)verwrite,(a)ll-overwrite,(s)kip,(q)uit]? o
```

And also, list the changed files before the first prompt, so that the "all-overwrite" command can be actually informative

## Describe alternatives you've considered

Leave as is.

**Comment by twpayne** [comment]
> After testing, it became apparent that short forms, `o` work for the commands, but its not made obvious in the prompt.

Any unambiguous abbreviation is accepted. Single-letter abbreviations happen to work here because of carefully chosen options, i.e. it's `overwrite` and `all-overwrite` rather than the more grammatically correct `overwrite` and `overwrite-all`. The use of single-letter unambiguous responses to prompts is conventional in UNIX tools, so it is not documented, but I would happily accept a PR that adds a description of this behavior to the reference manual. 

> And also, list the changed files before the first prompt, so that the "all-overwrite" command can be actually informative

This changes a simple iterative process (check each changed file one-by-one and prompt for each as they are encountered) into a more complicated multi-stage process (accumulate all changed files, print their names and/or diffs, then prompt for an action for the first changed file). I'd also happily accept a PR that implements this.

**Comment by twpayne** [comment]
Closing this in anticipation of contributions.
