### ISSUE TITLE
Support .xz for external archives

### ISSUE THREAD

**Issue by zbiljic** [twpayne/chezmoi#1883]
## Is your feature request related to a problem? Please describe.

I was planing to add some external package (from GitHub), which was archived using XZ compression. At that point I realized there is no support for it.

## Describe the solution you'd like

It'd be nice to have support for `.xz` archives as well.

## Describe alternatives you've considered

Another possibility for this to be solved (on Debian at least) is to install `xz-utils` package (if one is not already present).
While this does alternative removes problem, my plan was to have "slim" setup for my `dotfiles`, which does not update or adds additional packages to system (i.e. only directly executable binaries).

## Additional context

Also, I have already implemented this change [here](https://github.com/twpayne/chezmoi/compare/master...zbiljic:feature/archive-format-xz?expand=1), however I figured it would be prudent to ask before creating PR for this.

Note that there is separate commit where `go mod tidy` is performed, because external dependency was added in order to support this change. If that was done on the `master` branch, it can be removed from changeset.

**Comment by twpayne** [comment]
> Also, I have already implemented this change [here](https://github.com/twpayne/chezmoi/compare/master...zbiljic:feature/archive-format-xz?expand=1), however I figured it would be prudent to ask before creating PR for this.

Thank you for this! Your change looks excellent, and I particularly appreciate you following chezmoi's existing style. Please do open a PR. I have a couple of very minor nits and suggestions.





> Note that there is separate commit where `go mod tidy` is performed, because external dependency was added in order to support this change. If that was done on the `master` branch, it can be removed from changeset.

The large number of deletions in `go.sum` are slightly misleading here, as many of the lines are present because of cross-compiling for other OSes and architectures, which are added when you run `make test-release` on a Linux system (you'll need [GoReleaser](https://goreleaser.com/) installed and non-Linux hosts are not supported). So, I'd prefer it if the PR only includes the _additions_ to `go.mod` and `go.sum`. We can discuss this in your PR though.

Thanks again - this is excellent.

**Comment by zbiljic** [comment]
Thanks for accepting this (and this great tool).

Regarding last comment, personally I have pretty similar workflow for Go projects, and also use GoReleaser. In this instance I did run `make smoketest` and `make test-release`, however in this second case I manually disabled some targets (because I got some `runtime/cgo` related errors on Darwin, and did not think this change should matter as it is pure Go dependency); I totally missed that was the part that messed with `go.sum`.
