### ISSUE TITLE
Installing chezmoi from ~/bin results in ~/bin/bin/chezmoi

### ISSUE THREAD

**Issue by glibsm** [twpayne/chezmoi#1895]
I ran the install script from `~/bin` (not knowing anything about how it works). It looks like the install assumes to be run from home dir? It resulted in a nested `/bin/bin` directory as shown here:

```
~/bin
❯ sh -c "$(curl -fsLS chezmoi.io/get)"
info found version 2.12.0 for latest/darwin/amd64
info installed ./bin/chezmoi
~/bin
❯ ls ~/bin/bin
chezmoi
```

I'm not sure if there is a good solution to that. Perhaps check if `cwd == ~/bin` then just put the binary into `.` 🤷

**Comment by twpayne** [comment]
Hmm, this definitely needs thought. In the short term:

The install script has a `-b` option that allows the installation directory to be specified directly, which may help.

On macOS, chezmoi is also available through Homebrew and MacPorts, so if you're using either of these package managers then I'd recommend using `brew install chezmoi` or `port install chezmoi` instead. They'll also help keep chezmoi up to date on your machine.

**Comment by twpayne** [comment]
Crazy idea: the install script could look through all the directories in the user's `$PATH` and install chezmoi in the first directory found that is a subdirectory of the user's home directory. If no such directory is found, chezmoi could fall back to installing in `./bin`.

This shouldn't break too many users, but will lead to duplicate installs if the user already has chezmoi installed in a different subdirectory of `$HOME`. For example, if the user's `$PATH` is `$HOME/.local/bin:$HOME/bin` and chezmoi is already installed in `$HOME/bin` then this will lead to duplicate installs in `$HOME/.local/bin` and `$HOME/bin`.

Refined idea:
1. Scan through the user's `$PATH` to find chezmoi in any subdirectories of `$HOME`.
2. If chezmoi exists in that directory, then replace it.
3. Otherwise, install chezmoi in the first directory in the the user's `$PATH` which is a subdirectory of `$HOME`.
4. If no such directory exists, then install chezmoi in `./bin`.

How does this sound?

**Comment by dbowling** [comment]
Throwing out another idea. Set a command-line option for assigning `BINDIR` to `tmpdir`. That would make the binary go away after the install is completed for those of us who use chezmoi to bootstrap and manage their homebrew environment during the initial install.

Right now, I'm adding ~/bin to the path as part of a run_once_before script, and cleaning it up after I `brew install chezmoi`.

**Comment by glibsm** [comment]
Given chezmoi is available on a lot of package managers, I think it could make a lot of sense to keep `sh -c "$(curl -fsLS chezmoi.io/get)"` very simple.

To be honest, what I actually expected was more or less for `chezmoi.io/get` to just resolve to the latest release on github page and place the binary in the current directory without a whole lot of additional work.

It's unlikely that every workflow is going to be satisfied, but what @dbowling mentions is also an interesting piece of feedback. For example, when setting up a new mac there is a chicken and egg between dotfiles, and brew (including no Go until after brew install, most likely).

In general I'm not a huge fan of running `sh -c ....` as part of quickstart docs. I'd rather do something like `curl/wget <direct_binary> ~/bin`

**Comment by twpayne** [comment]
A few thoughts/observations:
* Existing users rely on the current default behavior (installing in `./bin`), so we can't change that. But, of course we can add new options or new scripts.
* chezmoi's releases are currently created with [GoReleaser](https://goreleaser.com/) which, as far as I can tell, only supports releasing binaries in a package or archive form (i.e. it does not have a method to release raw binaries). This is why `chezmoi.io/get` includes an archive unpack step (and a checksum verification step).
* Of course, it is technically possible to add raw binaries to chezmoi's releases on GitHub. Their names will need to be unique (e.g. `chezmoi-linux-amd64`, `chezmoi-darwin-arm64`, etc.) to avoid naming conflicts, but this means that an extra renaming step will be needed as part of the install to rename the final binary to `chezmoi`.

> I'd rather do something like `curl/wget <direct_binary> ~/bin`

Could you be specific on how the value of the`<direct_binary>` part is created? My best efforts so far have resulted in two calls to `curl`/`wget` (one to determine the `<direct_binary>` URL for the current OS/architecture, the second to do a combined download and rename, and this is without any checksum verification step). All this results in significantly more complex code than that existing one-line install. Happy to hear about improvements.

**Comment by twpayne** [comment]
> The curlbash is handy, but certainly comes with downside. If there had been a clear example in the readme, I would have opted to specify the platform myself and just download and run it.

chezmoi has [detailed installation instructions that cover a wide variety of platforms](https://www.chezmoi.io/install/), so I would argue that there is a clear example in the readme.

> I'd rather do something like `curl/wget <direct_binary> ~/bin`

#1945 adds direct binaries to chezmoi's releases. #1943 adds a `chezmoi license` command so that the license is distributed within the chezmoi binary itself.

Hopefully this is enough to resolve this issue. Please re-open if needed.
