### ISSUE TITLE
Network drive as destDir not working

### ISSUE THREAD

**Issue by bernie-reilly** [twpayne/chezmoi#1964]
## What exactly are you trying to do?
My company uses a network drive as a users home folder for Windows 10.  I added this to my `chezmoi.toml` file.
`destDir = "H:"`
I can't add files to chezmoi, this is what it looks like

```
PS H:\> chezmoi add .\.gitconfig
chezmoi: H:/.gitconfig: not in H:/
```
I have super double checked and .gitconfig is in my H drive folder.

```
PS H:\> ls .\.gitconfig
    Directory: H:\
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          3/9/2022   9:21 AM            856 .gitconfig
```

## What have you tried so far?

I have tried dos and powershell.  It does work if I use my user home folder on my C drive without `desDir` set in my config file.
I have also tried different ways of listing my H drive
```
destDir = "H:/"
destDir = "H:\"
destDir = "H:\\"
destDir = "H"
```

## Where else have you checked for solutions?

I've googled the issue and I can't find any solutions.  I have also read through the user guide and reference guide.

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
PS H:\> chezmoi --verbose add .\.gitconfig
chezmoi: H:/.gitconfig: not in H:/
```

## Output of `chezmoi doctor`

<details>

```console
PS H:\> chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.14.0, commit 7a2edbef28cc946972799ec287f78cb3b867ead4, built at 2022-03-09T21:44:20Z, built by goreleaser
ok        latest-version       v2.14.0
ok        os-arch              windows/amd64
ok        systeminfo           Microsoft Windows 10 Enterprise (10.0.19042 N/A Build 19042)
ok        go-version           go1.17.8 (gc)
ok        executable           C:/users/m315724/.local/bin/chezmoi.exe
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.toml
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             H:/ is a directory
ok        shell-command        found C:/WINDOWS/system32/cmd.exe
ok        shell-args           'C:\\WINDOWS\\system32\\cmd.exe'
ok        cd-command           found C:/WINDOWS/system32/cmd.exe
ok        cd-args              'C:\\WINDOWS\\system32\\cmd.exe'
ok        edit-command         found ~/AppData/Local/Programs/Microsoft VS Code/bin/code.cmd
ok        edit-args            code --wait
info      diff-command         not set
ok        git-command          found ~/AppData/Local/Programs/Git/cmd/git.exe, version 2.35.1
warning   merge-command        vimdiff not found in $PATH
info      age-command          age not found in $PATH
info      gpg-command          gpg not found in $PATH
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

**Comment by twpayne** [comment]
I won't have access to a Windows machine to investigate this for at least ten days. Maybe another chezmoi user using Windows can help.

**Comment by sm1999** [comment]
Tried to reproduce it. Apparently setting `destDir` to any other location outside the user's home directory gives this error.
From chezmoi doctor output does `H:` linked to `C:/users/m315724/` anyway ?

**Comment by bernie-reilly** [comment]
No, `H:` and `C:/users/m315724/` are different and not linked in anyway.  So would this be a bug then?

**Comment by zb140** [comment]
I can do some digging this evening and see what I can figure out.

**Comment by zb140** [comment]
So, it turns out that this issue is not specifically about network drives; it would happen any time `destDir` is set to the root of _any_ drive -- say, for example, if you've got a second hard drive `D:/` set up as your "home".

The immediate source of the error message is this check: https://github.com/twpayne/chezmoi/blob/master/pkg/chezmoi/abspath.go#L150, which is adding an extra `/` to the end of the path. The `HasPrefix` check on line 153 then checks if `H:/` has a prefix of `H://`, which of course it doesn't :smile:  I think the goal of the check is to make sure that paths that are not the root directory always end in a `/`.  @twpayne if that's correct, what do you think about adding an `AbsPath.IsRoot()`? On Mac/Linux it could just do `path == "/"` like today, and on Windows something more like `filepath.VolumeName(path) + "/" == path`.

Unfortunately, fixing this by itself isn't enough to actually fix the issue. The next problem is that this line will panic: https://github.com/twpayne/chezmoi/blob/master/pkg/chezmoi/sourcestate.go#L524.  The reason for that is that `parentAbsPath` ultimately comes from calling `path.Dir()` on `destAbsPath`, and it turns out that if you call it with a path like `H:/file`, it will return just `H:` (i.e.,  no slash) whereas `s.destDirAbsPath` _will_ have a slash, which causes the mismatch.

One potential fix for the issue would be for `AbsPath.Dir` to do something more like:
```go
// Dir returns p's directory.
func (p AbsPath) Dir() AbsPath {
	path, _ := NormalizePath(path.Dir(p.absPath))
	return path
}
```
This fixes the issue because `NormalizePath` in turn calls `filepath.Abs`, which puts a `\` on the end. (I know it's not great as a complete solution because it completely swallows the error :smile:)

It may also be possible to fix it by also applying the "sometimes add a slash" logic in `TrimDirPrefix` but a) I haven't tried it, and b) I'm not as big a fan of that solution on a philosophical level because I think it's buggy behavior on Go's part to not include the slash in the first place.  `H:` by itself is just a volume specifier, not a directory, so I don't think it's really a proper return value for `path.Dir()`. But reasonable minds can differ, and I'm happy to be told I'm wrong about that.

Anyway, putting those two fixes together will allow setting `destDir` to the root directory of a drive in Windows.  @twpayne, I ran out of time to do it tonight, but I'm happy to clean up my experimentations and put together a PR for whichever parts of this you think would be good additions.

**Comment by twpayne** [comment]
Thanks very much for this investigation @zb140 :)

I'd like to refactor how chezmoi handles paths to make this more robust, so please hold off fixing this for now.

**Comment by zb140** [comment]
Sounds good! Let me know if there's anything I can do to help.
