### ISSUE TITLE
URL redirection in .chezmoiexternal

### ISSUE THREAD

**Issue by dhruvinsh** [twpayne/chezmoi#2007]
## What exactly are you trying to do?

In .chezmoiexternal I am trying to get bitwarden cli

``` yaml
[".local/bin/bw"]
  type = "file"
  url = "https://vault.bitwarden.com/download/?app=cli&platform=linux"
  executable = true
  [".local/bin/bw".filter]
    command = "unzip"
```
But the url needs automatic redirection but it seems that it is not supported natively. Is it possible with external directive?

## What have you tried so far?

I can definitely have before/after script to set it up with wget but just wondering if we can achieve the same with .chezmoiexternal 

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.

**Comment by twpayne** [comment]
chezmoi follows URL redirects. The problem in your case is that you're using `unzip` as a filter, but `unzip` doesn't support reading zip archive from the standard input and so cannot be used as a filter.

I would recommend either downloading a tarball instead of a zip archive (`tar` can read from the standard input) or using a script to download and unzip the archive.
