### ISSUE TITLE
alternate files? custom attributes in files names?

### ISSUE THREAD

**Issue by niksfirefly** [twpayne/chezmoi#205]
What do you  think about simple alternate files based on file suffix like in yadm
https://thelocehiliosan.github.io/yadm/docs/alternates
or custom files attributes/suffixes bound to some actions defined in .yaml config file?

I think yadm solution is very pretty and self explanatory

regards

**Comment by twpayne** [comment]
This is an interesting idea. It's definitely easier than using templates if the files are significantly different across machines. Let me ponder on the idea for a while, but I suspect I'll end up adding this.

**Comment by niksfirefly** [comment]
Is there any chance you implement this idea?
I see many advantages of chezmoi but this is the best and killer yadm option :)

**Comment by twpayne** [comment]
Yes, I'd like to implement this. I'm not sure when I'll have time though.

**Comment by twpayne** [comment]
After some thought, I think this can be achieved in chezmoi right now. The trick is to use a templated symlink.

Say you have two `.bashrc`, one for `darwin` and one for `linux`. You'd create the following in your source directory (warning: not tested, but should work):

`symlink_dot_bashrc.tmpl`:
```
.bashrc_{{ .chezmoi.os }}
```

`dot_bashrc_darwin`:
```
# .bashrc on darwin
```

`dot_bashrc_linux`:
```
# .bashrc on linux
```

`.chezmoiignore`
```
{{ if ne .chezmoi.os "darwin" }}
.bashrc_darwin
{{ end }}
{{ if ne .chezmoi.os }}
.bashrc_linux
{{ end }}
```

This setup means that `.bashrc` will be a symlink to `.bashrc_darwin` on `darwin` and `.bashrc_linux`, and that only one OS-specific `.bashrc_os` file will be installed on each OS.

Advantages of this system:

* Separate dotfiles for different machines.
* Fully customizable symlinks using whichever variables you want (yadm only allows a few predefined variables).
* Works with chezmoi's existing machinery now.

Disadvantages:

* Requires more manual setup compared to yadm (but you only have to do this once per file).
* Uses symlinks rather than writing real files.

On balance, I think this is a better solution than yadm's, so I don't plan to implement the original proposal in this PR. I'm happy to hear different perspectives however :)
