### ISSUE TITLE
Add OS version information for more platforms in built-in `data`

### ISSUE THREAD

**Issue by bradenhilton** [twpayne/chezmoi#2085]
## Is your feature request related to a problem? Please describe.

I'm in the process of writing some scripts (notably package installation scripts) for Windows which differ depending on the OS version.

Of course, it's possible to determine the version within the script itself, but it would certainly be nice to have this built into chezmoi if at all possible. I believe there is an existing precedent with `osRelease` being provided on Linux, though I do also acknowledge that the existence of `os-release` made this more trivial than on other platforms.

I'm less familiar with macOS so I will defer to those who are more knowledgeable.

## Describe the solution you'd like

https://stackoverflow.com/a/44376544/11000543 offers a solution for getting the Product Name, Major and Minor versions as well as the Build Number on Windows using [`golang.org/x/sys/windows/registry`](https://pkg.go.dev/golang.org/x/sys@v0.0.0-20220520151302-bc2c85ada10a/windows/registry).

[sindresorhus/windows-release](https://github.com/sindresorhus/windows-release/blob/edb4b7b5efc4c92bcd32d41701f6f727dff0c485/index.js) is a Node.js solution demonstrating a simple version mapping which even includes Windows Server.

Perhaps this could be used to populate a fake `osRelease`? Or maybe introduce `windowsRelease`/`darwinRelease` or `osInfo`etc.

## Describe alternatives you've considered

Populating version information within `data` in chezmoi's config by using various `{{ output ... }}`'s etc.

This is obviously sufficient enough, but it only benefits me unless I share the template and people go out of their way to find and use it. We can prevent a lot of reinventing the wheel.

Do you think this is something which should be provided by chezmoi?

## Additional context

N/A

**Comment by twpayne** [comment]
> [sindresorhus/windows-release](https://github.com/sindresorhus/windows-release/blob/edb4b7b5efc4c92bcd32d41701f6f727dff0c485/index.js) is a Node.js solution demonstrating a simple version mapping which even includes Windows Server.

For info, I haven't copied this version mapping logic into chezmoi in #2086 because:
1. It's horrific. My Windows 11 machine reports that it's running Windows 10. You need to inspect multiple registry keys to find out what version of Windows you're actually running.
2. I have no easy to way to validate that the logic in sindresorhus/windows-release is correct .
3. Version mapping can be done in text/template logic by the user for the Windows versions they care about.
4. Version mapping will probably change in the future, and affected users can change their templates immediately. This is better than making them wait for a new version of chezmoi with updated version mapping logic.
