### ISSUE TITLE
Generic secret function improvements

### ISSUE THREAD

**Issue by lcrockett** [twpayne/chezmoi#2290]
## Is your feature request related to a problem? Please describe.

This feature request is not related to a problem.

## Describe the solution you'd like

I have recently integrated `chezmoi` with [`Team Password Manager`](https://teampasswordmanager.com) using `BASH`. This works great using the generic secret function. However a few improvements came to mind that might be considered.

1. While i'm able to specify the command for a generic secret helper, i'm not able to specify arguments to this command. A use case could be specifying `--output json` as an argument to the secret helper, isolating it from the secret lookup arguments that can be specified using `{{ secret "argument" "argument" "etc" }}`. I've ran into an issue where I was unable to specify `--output json` as an argument to the command, whereas encapsulating the secret command in a shell wrapper that specified `--output json` as an argument and passes on other secret lookup arguments (`$@`) did work. Most likely this was due to the fact that the `--output json` flag was supposed to come last and secret lookup arguments first. However, specifying the json flag last within the `{{ secret }}` block didn't work either.

2. It seems like error handling could use an exit handling improvement. Once the secret helper exits with code > `0` (perhaps the secret backend is not working, or the secret endpoint is unavailable) `chezmoi` stops entirely. I'd think it would be beneficial if we could control that behaviour. For instance, if the secret helper exits with a pre-determined code, `chezmoi` skips changing / comparing the secret value and continues on. Or via any other means, as long as `chezmoi` does not promptly stops once a secret helper exits ungracefully. For now i'm printing a bogus value and exiting gracefully with exit code `0` if the secret helper cannot function as intended. This does however change the secret value in files managed by `chezmoi` to the bogus value, which in this case is deemed more practical than changing the secret value to nothing as `chezmoi` would do if the secret helper didn't output anything -and- exits ungracefully. This problem is IMO mostly amplified when using a secret helper that retrieves secrets from a remote endpoint as the majority of the other secret helpers use local databases. A use case for this scenario could be where one is changing the `chezmoi` source directory and triggering a `chezmoi apply` for testing purposes while being offline, or where the secret endpoint is simply unavailable and a `chezmoi apply` would render all secrets to be changed because of it, essentially blocking one from running a `chezmoi apply`.

3. I see it as beneficial if `chezmoi` would support multiple generic secret backends. As far as I can tell I can only specify 1 custom generic secret function. It would be great if one could specify multiple in order to pull secrets from multiple different secret backends via custom secret helpers. For instance pulling secrets from `secret tool blabla` using `{{ secret-blabla }}` and pulling secrets from `secret tool bloblo` using `{{ secret-bloblo }}`. If this needs more detail, I would be happy to elaborate.

## Describe alternatives you've considered

No alternatives have been considered.

## Additional context

No additional context applicable.

**Comment by twpayne** [comment]
I think most of the problems you describe can be fixed by wrapping the password manager with a script. This would allow, for example:

* Using the first argument to select the password manager (e.g. you'd write `{{ secret "blabla" ... }}` to use blabla and `{{ secret "bloblo" ... }}` to use bloblo.
* Adding extra args (e.g. `--output=json`) in the right place.
* Handling any strange exit codes from the password manager.

Note that chezmoi passes arguments as-is to the script. Specifically, the string `--output json` gets passed as a single argument containing a space. You might want to pass `--output=json` as a single argument or `--output` `json` (two separate arguments) instead.

#2295 adds a `secret.args` configuration variable, which was missing.

**Comment by lcrockett** [comment]
Cheers on #2295.

You are correct to state a script could handle most of the described scenarios. I figured it would be beneficial if `chezmoi` had first class support for this. A script will do just as fine however.

One thing that i'm not seeing a script being able to solve easily is a breakdown in communication between the script and the secret backend. A script would either only be able to exit ungracefully, or output nothing, or output some bogus data. Either one of these scenario's will either make `chezmoi` abort, or overwrite managed secrets with an empty / bogus value.

Would `chezmoi` be able to support a scenario where a secret helper script would be able to signal `chezmoi` of a connectivity error ensuring `chezmoi` won't touch that particular secret value ? I was thinking of exiting ungracefully with a specific exit code that `chezmoi` can pick up and then decide to ignore handling that secret. For instance exit code 69 or 75, inspired by FreeBSD's `sysexits`, see page [here](https://www.freebsd.org/cgi/man.cgi?sektion=3&query=sysexits).

**Comment by twpayne** [comment]
> Would `chezmoi` be able to support a scenario where a secret helper script would be able to signal `chezmoi` of a connectivity error ensuring `chezmoi` won't touch that particular secret value ?

This would require chemzoi to store previous secret values returned by the helper script. As they are secrets, they should be stored securely. chezmoi delegates secret storage to a password manager.

The problem of unreliable communication between the script and the secret backend can also be solved by the script. The script can use a local password manager to store received secrets and return those when the secret backend cannot be reached.

Overall, I don't think this problem is common enough to warrant significant complexity increases to the implementation of chezmoi's `secret` template function, especially as a flexible workaround (using a wrapper script) already exists.

**Comment by lcrockett** [comment]
Alright. Thanks for the insights and possibility to use arguments with a secret helper. Cheers !
