### ISSUE TITLE
Warning of suspicious-entries for diff.pager in chezmoi.toml

### ISSUE THREAD

**Issue by benjaminbauer** [twpayne/chezmoi#2417]
## Describe the bug

When I run `chezmoi doctor`, I get a warning:
```
ok        version              v2.24.0, commit 72d9846a7ae51fd3398727d48815fc2f13a681f9, built at 2022-09-25T17:18:10Z, built by Homebrew
...
warning   suspicious-entries   ~/.local/share/chezmoi/dot_config/chezmoi/chezmoi.toml
...
```

## To reproduce
The contents of my `chezmoi.toml`:
```
[diff]
  pager = "delta"
```

## Expected behavior

This is not a suspicious entry imo, I copied it from the [docs](https://www.chezmoi.io/user-guide/tools/diff/#show-human-friendly-diffs-for-binary-files)

**Comment by twpayne** [comment]
This is suspicious because if you want chezmoi to manage its own configuration file you should use a [config file template](https://www.chezmoi.io/user-guide/setup/#create-a-config-file-on-a-new-machine-automatically).

If you use chezmoi to create `~/.config/chezmoi/chezmoi.toml` then the first time you run chezmoi then the config file won't yet exist, and subsequent runs on chezmoi will use the old contents of the config file. Using a config file template avoids these problems.
