### ISSUE TITLE
How Do I import oh-my-zsh plugins?

### ISSUE THREAD

**Issue by alzedd** [twpayne/chezmoi#256]
Say for example, I need to add denysdovhan/spaceship-prompt. How do I import it after importing oh-my-zsh?

**Comment by twpayne** [comment]
The easiest way is to re-add the entire `~/.oh-my-zsh/plugins` directory:

```
chezmoi add -r -x ~/.oh-my-zsh/plugins
```

Note that the `-x` is makes the add "exact", i.e. `chezmoi` will make the directory contents match exactly by removing files if necessary, not just adding and updating them.

**Comment by alzedd** [comment]
Ah ok, so I should add all the omz dir and not importing it  as a tarball (like in the readme)

**Comment by twpayne** [comment]
Both work. I used omz as an example for the `import` command in the README, but use whichever method you prefer.

I recommend turning off omz's update mechanism and updating omz manually so you can ensure that it gets updated in chezmoi too.

**Comment by twpayne** [comment]
I hope that answers your question. Please re-open this issue if needed.

**Comment by kitos9112** [comment]
Hello @twpayne - sorry for bumping this closed issue but I found it useful though. I guess it'd be worth updating the how-to guide regarding how to add custom plugins or maintain modifications on git submodules, like OMZ.

**Comment by twpayne** [comment]
Re-opening this as the doc still needs to be updated.

**Comment by redtux** [comment]
Hi, another omz user here aiming to use chezmoi. 👋🏼 

I can confirm the following command is working fine:

```
chezmoi add -r --exact ~/.oh-my-zsh
```

Note 1: Before that I have tried the two commands in [Include a subdirectory from another repository, like Oh My Zsh](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#include-a-subdirectory-from-another-repository-like-oh-my-zsh), but I always get the following error (no matter whether `~/.oh-my-zsh` exists or not):

```
chezmoi: /home/redtux/.oh-my-zsh/.editorconfig: parent directory not in source state
```

Note 2: Apart from this, the `-x` argument mentioned above might have changed its meaning, standing for `--exclude` instead of `--exact` (which has no short argument in version 2.0.10).

**Comment by kitos9112** [comment]
I didn't opt for include `oh-my-zsh` in my dotfiles in the end, every time I roll out a new installation (or update an existing one), it gets cloned/pull-rebased from github as part of a script that chezmoi runs on every apply.
Customisations to the OMZ framework live in a separate folder that gets automatically sourced in my .zshrc file and tracked in my source directory though.
