### ISSUE TITLE
`chezmoi cd` to cd into `.chezmoiroot`'s specified subdirectory

### ISSUE THREAD

**Issue by mournfully** [twpayne/chezmoi#2646]
## Is your feature request related to a problem? Please describe.

Whenever I do `chezmoi cd` to jump to my `$HOME` directory's source state. I have to do an additional `cd HOME` to actually get there. It's a small thing, but I feel that after setting up `.chezmoiroot`, the root of the git repository is rarely ever needed. 

## Describe the solution you'd like

If `.chezmoiroot` exists in the root of the source directory then I'd like `chezmoi cd` to change to the directory specified in `.chezmoiroot` instead of simply going to the root of the git repository.

```shell
$ cat ~/.local/share/chezmoi/.chezmoiroot
HOME

$ chezmoi cd
% pwd
~/.local/share/chezmoi/HOME
% exit
```

## Describe alternatives you've considered

- The alternative without this feature would be to `chezmoi cd` into the root of the source directory and then `cd` into the subdirectory chezmoi reads the source state from. 
- If changing `chezmoi cd`'s default behavior is too drastic, perhaps an option to change it could be added to chezmoi's config.

**Comment by halostatue** [comment]
I think for this change to happen, we would want to add a couple of flags for when the default behaviour changes, something like `chezmoi cd --root` (for `.chezmoiroot`) and `chemzoi cd --source` (for the current behaviour) with the default starting as `chezmoi cd --source` and for some future version of chezmoi (2.50, 3, whatever) it would behave as `chezmoi cd --root`).

There are two other alternatives. One already exists, and that’s `chezmoi cd PATH`. My `.vim` directory is managed by chezmoi, so `chezmoi cd ~/.vim` takes me to `$CHEZMOIROOT/private_dot_vim`. That might be a suitable substitute if you’re going to a subdirectory.

On the other hand, `chezmoi cd ~` does not work (`chezmoi: /Users/austin: not in source state`, which while true, is not useful since it *would* be `$CHEZMOIROOT`, unless there’s a different destination). That might be a simpler enhancement with little backwards compatibility issues or migration plan required. Would that work for you?

**Comment by mournfully** [comment]
I don't think adding flags `--root` and `--source` or a `~` arg to `chezmoi cd` will work for me. Since, I'm mostly just interested in reducing how much I have to type. That and I'd rather not mess with `args` as I quite like their current implementation.

Anywho, I did find this relevant [chezmoi issue](https://github.com/twpayne/chezmoi/issues/2578) which lead me to it's corresponding [commit](https://github.com/twpayne/chezmoi/pull/2579/commits/5475b71941dbbbfd48e9dfa33f25b5cedf53ce03), and after looking through the [code](https://github.com/twpayne/chezmoi/blob/master/pkg/cmd/cdcmd.go). I'm fairly certain that `.chezmoiroot` just changes `sourceDir`. So, I think this is the simplest way to implement what I want?

```diff
diff --git a/pkg/cmd/cdcmd.go b/pkg/cmd/cdcmd.go
index 856760cc..6dd3f00e 100644
--- a/pkg/cmd/cdcmd.go
+++ b/pkg/cmd/cdcmd.go
@@ -38,7 +38,7 @@ func (c *Config) runCDCmd(cmd *cobra.Command, args []string) error {
        }
        var dir chezmoi.AbsPath
        if len(args) == 0 {
-               dir = c.WorkingTreeAbsPath
+               dir = c.SourceDirAbsPath
        } else {
                sourceState, err := c.getSourceState(cmd.Context())
                if err != nil {
```

In other words when there are no args, I want `chezmoi cd` to take me to `sourceDir` and not `workingTree`. _Hmm, I realize I've referenced `sourceDir*` and `workingTree*` quite a bit, so here's what they actually represent:_

```shell
$ chezmoi data | grep "sourceDir\|workingTree"
    "sourceDir": "/home/local/.local/share/chezmoi/HOME",
    "workingTree": "/home/local/.local/share/chezmoi"
```

I also do agree that changing `chezmoi cd`'s default behavior might not be such a great idea. So, perhaps to make this behavior opt-in only. We could add a `boolean` variable to chezmoi's config file? Or if a `.chezmoiroot` file is found? And, after all that I think we'd just have to update the [docs](https://github.com/twpayne/chezmoi/blob/master/assets/chezmoi.io/docs/reference/commands/cd.md) and [unit test](https://github.com/twpayne/chezmoi/blob/master/pkg/cmd/testdata/scripts/cd_unix.txtar).

**Comment by halostatue** [comment]
It’s not ultimately my call, but I think that having a configuration option here is the *wrong* thing to do (the more configuration options present, the more complex testing becomes and the bigger chance of a regression in refactoring). I don’t have a `.chezmoiroot` file, but even if I did, I would not want the behaviour of `chezmoi cd` to change before Chezmoi 3 (that is, I consider this a breaking change).

I still think that the best way to do this would be special-casing `chezmoi cd ~`, because the current behaviour (reporting that the value behind `~` isn’t in state) isn’t very useful, but to me the only viable way to migrate this would be through the `--root` and `--source` flags that I suggested.

**Comment by mournfully** [comment]
Fair enough. I also tested out my proposed diff and it doesn't seem to work. So, I think I'll just remove my `.chezmoiroot` file instead. Feel free, to close this issue.

**Comment by twpayne** [comment]
Thanks for the discussion. I agree with @halostatue that special casing `chezmoi cd ~` is the right approach here, as it maintains backwards compatibility while also providing the functionality that @mournfully requests (bar two extra characters to type). #2648 implements this.
