### ISSUE TITLE
recipe for renaming config files

### ISSUE THREAD

**Issue by hydrargyrum** [twpayne/chezmoi#2710]
## What exactly are you trying to do?

Rename a config file

### Naive
Just `git mv old new` in the source tree, then `chezmoi apply` leaves target tree with `old` and `new`

So in addition I put a `run_after_rename_new.sh` in source tree:
```
#!/bin/sh -e
mv -f old new
```

But I'm not sure it's the best way to do it (at least it renames and keeps local target modifications to `old`).

Maybe a recipe should be added in docs.

### Alternative
The `git mv` step, then add an empty `remove_old` file to source tree, but that would lose local modifications to `old`.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

**Comment by hydrargyrum** [comment]
Or maybe add a `rename_` file type like `symlink_` that instructs to rename a file (if it exists) to the new name

**Comment by twpayne** [comment]
[`.chezmoiremove`](https://www.chezmoi.io/reference/special-files-and-directories/chezmoiremove/) and the `remove_` attribute exist for this purpose.

The current process is:
1. Add the config file in its new location (e.g. using `git mv` as you identify).
2. Add the old name to `.chezmoiremove` or add the `remove_` attribute to the old filename.
3. Run `chezmoi apply` on all your machines, so that they're all up to date.
4. Once all your machines are all up-to-date with the new name, remove the entry from `.chezmoiremove` or the `remove_` file.

> ### Alternative
> The `git mv` step, then add an empty `remove_old` file to source tree, but that would lose local modifications to `old`.

With chezmoi, you shouldn't have local modifications to files, as the next time you run `chezmoi apply` those local modifications will be overwritten.

> Or maybe add a `rename_` file type like `symlink_` that instructs to rename a file (if it exists) to the new name.

This is an interesting idea, thank you.

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed.
