### ISSUE TITLE
support rbw for bitwarden

### ISSUE THREAD

**Issue by classabbyamp** [twpayne/chezmoi#2836]
## Describe the solution you'd like

support for the alternative bitwarden cli [`rbw`](https://github.com/doy/rbw) (I prefer it because `bw` is not packaged on my distro, and i'd rather not use node for such a client)

The command syntax and output schema are slightly different than `bw`, so I'm not sure what would need changing for support

previous issue: #1527

## Additional context

This has not been merged or released quite yet, but the author has indicated that it will be merged, see https://github.com/doy/rbw/pull/97

here's an example of the command syntax and output schema:

```json
$ rbw get --raw test-entry
{
  "id": "adf723e1-ab03-4ff3-81aa-f5f3c2b68a5f",
  "folder": null,
  "name": "test-entry",
  "data": {
    "username": "foo",
    "password": "hunter2",
    "totp": null,
    "uris": [
      {
        "uri": "example.com",
        "match_type": null
      }
    ]
  },
  "fields": [
    {
      "name": "something",
      "value": "secret"
    }
  ],
  "notes": "blah",
  "history": [
    {
      "last_used_date": "2022-08-18T23:24:47.994Z",
      "password": "hunter2"
    }
  ]
}
```

**Comment by halostatue** [comment]
This sounds good. As noted with the previous issue, we will need to know two things for each command that is used with `bw`:

1. The equivalent `rbw` invocation; and
2. The difference in output for `rbw` vs `bw`.

If things are *similar* enough, we could possibly make it so that specifying `bitwarden.command = "rbw"` changes the invocation and parsing (as happened with the 1Password v1 to v2 transition) so that only the standard functions are changed.

If you could make a draft PR with a second test file set up like `pkg/cmd/testdata/scripts/bitwarden.txtar` that instead provides `rbw` and `rbw.cmd` (like `pkg/cmd/testdata/scripts/onepassword.txtar` and `pkg/cmd/testdata/scripts/onepassword2.txtar`) with the appropriate test shape data and simulated command-line would go a very long way toward helping us get this done. It will depend on the merging of doy/rbw#97.

**Comment by twpayne** [comment]
Let's wait for a release of `rbw` with JSON output. https://github.com/doy/rbw/pull/97 has just been merged, so I don't imagine it will be long.

If the output formats of `rbw` and `bw` are different then we should use different template functions for them. This is simpler and more robust than trying to intermingle the logic to handle both.

In the short term you can use a [custom password manager](https://www.chezmoi.io/user-guide/password-managers/custom/) by setting `secret.command` to `rbw` and using the `secretJSON` template function.
