### ISSUE TITLE
Best Practice: Where to store a list of packages?

### ISSUE THREAD

**Issue by heliostatic** [twpayne/chezmoi#2868]
## What exactly are you trying to do?

I'm using Chezmoi to install a list of packages using homebrew and cargo. For Homebrew, I have a `Brewfile` and for cargo I have `cargo-packages.txt`

In both cases, I have scripts `run_onchange_install.sh.tmpl` (e.g.) that watch for those file hashes to change. But really, I don't want to create the package lists in the target directory.

e.g.
```
#!/bin/bash
# cargo-packages.txt hash: {{ include "cargo-packages.txt" | sha256sum }}
cat {{ joinPath .chezmoi.sourceDir "cargo-packages.txt" }} | xargs -I _ cargo install-update -ia _
```

Where do other folks keep them?

## What have you tried so far?

So far I've just lived with them being created in the target directory. I've considered the `.chezmoiscripts` but they're not scripts.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Other, please give details. -- closed GH issues

**Comment by bradenhilton** [comment]
Personally, I would place the installer scripts in `.chezmoiscripts`, and I would place the package list files anywhere in the source state, and ignore them by prefixing their names with a dot `.`, or adding them to `.chezmoiignore`.

**Comment by halostatue** [comment]
I’m sort of going through this now and have done *partially* what is suggested by @bradenhilton above, https://github.com/halostatue/dotfiles.

You can see my `Setup/` directory which has scripts I have written for installation. `Setup/` is in `.chezmoiignore`, but I can run them at any time. I have a few other things which trigger certain installs in `.chezmoiscripts`, but I haven’t settled on whether I *want* these to be `run_once_before` (as they are currently) or `run_after`. The problem for some of these is that the download / (maybe build) / install process can be very slow, and it isn’t something I necessarily want on every chezmoi run. So for now, I just have them in `Setup/` and re-run them periodically (the Go binary ones are *particularly* persnickety because there is no "update if required" functionality, so *everything* has to rebuild/reinstall every time).

**Comment by twpayne** [comment]
I use an idempotent `run_onchange_` script that only changes when the list of packages to install changes. It handles [brews and casks on macOS](https://github.com/twpayne/dotfiles/blob/798742d79da7186267083e3c6b37d2250248ba1d/home/.chezmoiscripts/darwin/run_onchange_before_install-packages.sh.tmpl) and [packages and snaps on Ubuntu](https://github.com/twpayne/dotfiles/blob/798742d79da7186267083e3c6b37d2250248ba1d/home/.chezmoiscripts/linux/run_onchange_before_install-packages.sh.tmpl).

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed.
