### ISSUE TITLE
Password manager authentication skip (cli flag/argument)

### ISSUE THREAD

**Issue by Evangelospro** [twpayne/chezmoi#2888]
## Is your feature request related to a problem? Please describe.

It is a bit frustrating to have to log in to bitwarden(or any other password manager) in order to sync the state of chezmoi when the files stored on bitwarden are only in ssh keys for example which only need sync on the first time on a new machine.

## Describe the solution you'd like

I would really appreciate it if there was a command line argument that would skip password manager authentication and just sync any files that don't require the password manager.

**Comment by twpayne** [comment]
chezmoi needs to interrogate your password manager to know if the file's contents have changed. There is no way around this.

Most modern password managers include some kind of persistent login facility that allow you to stay logged in for at least a few minutes, so you don't have to type in your password every time. Alternatively, they might offer touch-based authentication (e.g. using a fingerprint scanner or security key) that is less onerous that typing your password.

As a work-around for password managers that do not support any of the above, you can tell chezmoi to only create a file once by adding it conditionally to your `.chezmoiignore` file, for example:

```
{{ /* only create ~/.ssh/id_rsa if it does not exist */ }}
{{ if stat (joinPath .chezmoi.homeDir ".ssh/id_rsa") }}
.ssh/id_rsa
{{ end }}
```

Of course, this means that if you change your private key you must delete `~/.ssh/id_rsa` so that chezmoi will re-create this.

**Comment by Evangelospro** [comment]
I do understand the need of asking for a password but why not have a cli flag that just doesn't bother with .tpml files that need authentication? Because someone may just want to do a quick and dirty change without signing in etc...

**Comment by twpayne** [comment]
How do you tell which `.tmpl` files need authentication?

**Comment by Evangelospro** [comment]
I don't exactly know how chezmoi handles templating but couldn't it just not call the password manager signin method if a flag is passed?

**Comment by twpayne** [comment]
> I don't exactly know how chezmoi handles templating but couldn't it just not call the password manager signin method if a flag is passed?

The signin method is managed by the password manager, not chezmoi.

**Comment by halostatue** [comment]
> I don't exactly know how chezmoi handles templating but couldn't it just not call the password manager signin method if a flag is passed?

Chezmoi does no static analysis of the templates prior to running them‡, so even we were to add some looking for the use of the dozen or so password manager functions (harder than you would think, because we would have to look for these potentially recursively), we would run against the cases where the `output` template function is called, since that could trigger a password manager command-line *directly*. Additionally, if the password manager functions were blocked with this, we would have to skip any files that use the template or include, because we could no longer trust the output of those templates to not break anything (I have ~10 files that call `onepassword*` functions: `~/.gem/geminabox`, `~/.gem/credentials`, `~/.spacemacs.d/init.el`, `~/.gitconfig`, `~/.aws/credentials`, `~/.github_keystore`, `~/.netrc`, `~/.config/gh/private_hosts.yml`, `~/.config/brew/config.sh`, `~/.config/brew/config.fish`).

In short, there’s no way that this could be done in a reasonable amount of time and the development effort wouldn't be worth it for the complexity added. The only way that I could see this working at all would be a new exclusion, `templates` (e.g., `--exclude templates`) which would refuse to process *any* template. I can’t *personally* see any value in that option, so I don’t know that would be implemented, either.

@twpayne already suggested [the right answer](https://github.com/twpayne/chezmoi/issues/2888#issuecomment-1484072733):

```
{{ /* .chezmoiignore */ }}
{{ /* only create ~/.ssh/id_rsa if it does not exist */ }}
{{ if stat (joinPath .chezmoi.homeDir ".ssh/id_rsa") }}
.ssh/id_rsa
{{ end }}
```

‡ There is some simplistic scanning for template directives, but those are *purely* pattern matching for configuring the templating engine itself.
