### ISSUE TITLE
When to use private attribute?

### ISSUE THREAD

**Issue by SimonWoodtli** [twpayne/chezmoi#2896]
I try to understand what the use case of the private attribute with `chezmoi chattr` is for? On Linux the current users /home/user already only has user scope (and root). Why would you want to limit the scope for config files? I saw that @twpayne used it on ~/.config but not on ~/.tmux.conf.

**Comment by halostatue** [comment]
My answer on when to use it is `yes` for anything in `$HOME`, so that most of my files are `0600` and `0700` for directories.

I use it sometimes on files in subdirectories, like

- `home/private_dot_aws/private_credentials.tmpl`
- `home/private_dot_config/gh/private_config.yml`
- `home/private_dot_config/gh/private_hosts.yml.tmpl`
- `home/private_dot_gem/private_credentials.tmpl`
- `home/private_dot_ssh/private_config.tmpl`

-a

**Comment by twpayne** [comment]
> On Linux the current users /home/user already only has user scope (and root).

This is not correct. The permissions depend on the Linux distribution that you are using. chezmoi also runs on many non-Linux operating systems, which also vary in their use of file permissions. The `private_` attribute exists to support all this variety.

**Comment by SimonWoodtli** [comment]
Ah I see. Well prior to asking this question I checked it on my Fedora install and I assumed all distros would chmod 0700 on $HOME. So that got me thinking why you would implement that. But you are right there are distros and other OS to consider who do not follow that permissions on $HOME.

A quick search could have already pointed me in the right direction. But frankly I am shocked that other distros allow for such permissive permissions.

https://unix.stackexchange.com/questions/315799/default-permissions-on-linux-home-directories

Anyway thanks for this great tool, it's awesome 👍

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed.
