### ISSUE TITLE
Can chezmoi be used to 'install' binaries?

### ISSUE THREAD

**Issue by eggbean** [twpayne/chezmoi#2931]
I've been using [stow](https://github.com/aspiers/stow) for years not only for dotfiles but to also install some statically-linked binaries, along with related tab completion and man files in the correct OS locations, which requires root. This way I can bootstrap a server with all my configuration and essential programs very easily with one script.

I can see that chezmoi has the advantage of being a single statically-linked binary itself, which has some advantages when bootstrapping where there is no root access (like cloud shells). It also has a lot of additional features which look interesting, but I don't understand them yet.

Before I go further I simply want to know if chezmoi can be used to install binaries, completion files and man files like stow can?

**Comment by halostatue** [comment]
Welcome to chezmoi!

Chezmoi can execute scripts during apply and use external sources to do pretty much anything. In my [dotfiles repo](https://github.com/halostatue/dotfiles) you can see:

1. Executable files in `home/private_dot_local/bin` for scripts that I want to carry around with me.
2. Scripts in `home/.chezmoiscripts` which will install Homebrew, MacPorts, Cargo, and Go binaries. I have some additional work to do, but I could also install python binaries with `pipx`, all kept in `Setup/*`.

I’ve never used stow, so I’m not really sure if that answers your question. Since you’re migrating, it’s worth knowing about a few things:

- There is a [stow-to-chezmoi.sh](https://github.com/twpayne/chezmoi/blob/master/assets/scripts/stow-to-chezmoi.sh) script which may be useful in providing an initial conversion.
- Chezmoi uses a different mechanism (templates and templated ignore) for ["packages"](https://github.com/twpayne/chezmoi/discussions/2196); it does [not support multiple sources](https://www.chezmoi.io/user-guide/frequently-asked-questions/design/#can-chezmoi-support-multiple-sources-or-multiple-source-states). There are some examples in discussions of how people have managed this, but it requires adopting a *different workflow* for managing those two states, and trying to merge the data from two different states into a single file is *not recommended*.
- Chezmoi deliberately [does not use symlinks](https://www.chezmoi.io/user-guide/frequently-asked-questions/design/#why-doesnt-chezmoi-use-symlinks-like-gnu-stow).

**Comment by twpayne** [comment]
Thank you for the excellent reply @halostatue!

Hopefully this is now resolved. Please re-open if needed.
