### ISSUE TITLE
Add an option for `add` to implicitly `encrypt` when source file is already encrypted

### ISSUE THREAD

**Issue by eugenesvk** [twpayne/chezmoi#3142]
## Is your feature request related to a problem? Please describe.

Whenever I edit files outside of chezmoi, or if those files are from GUI apps that edit those files themselves ignoring chezmoi, and I fix it by `chezmoi add /fd/myfile.cfg`, I get a warning message if the source file is encrypted, that adding will remove encryption. So I have to backtrack and add `--encrypt`, which is inconvenient

## Describe the solution you'd like

Once I've added encryption this decision should be preserved until I manually remove it instead of having to confirm it every time

## Describe alternatives you've considered

Using `re-add`, but this is a batch tool and it might override other changes in other files that I don't want to have overridden
Adding `--encrypt` manually or doing some shorter alias, though it doesn't completely solve the issue since I don't remember in advance that this file is encrypted

## Additional context

None

**Comment by halostatue** [comment]
Added "already" to title.

Would a `--preserve-attributes` flag be acceptable, since this is for use in a batch tool? That is `chezmoi add --preserve-attributes /fd/myfile.cfg`? It would be a no-op on adding new files, but when `add` acts like an individual-file `re-add`, it would automatically reuse the existing attributes.

**Comment by eugenesvk** [comment]
I might've confused you a bit, apologies: by a batch tool I meant the 're-add' command itself in that it adds all the files as a single batch :) Otherwise this is manual invokation of chezmoi add in a shell

A config would be preferable since then I wouldn't have to worry whether I'm calling an alias or chezmoi directly or doing something in a different shell (rare, but still)
But a flag would also work, I'll add it to my `ch a` alias

**Comment by twpayne** [comment]
`chezmoi add` has the very specific task of making the entry in the source directory match the entry in the destination directory, overwriting the entry in the source directory if needed.

`chezmoi re-add` is a more appropriate fit here, as it preserves the `encrypted_` attribute.

#3146 extends `chezmoi re-add` to accept an optional list of targets, which should solve the problem here.

**Comment by eugenesvk** [comment]
Thank you, I liked the simplicity of a single command as I didn't find the add/re-add distinction useful (except for mass add which could potentially be done with a `add -all`), but think that switching to using `re-add` by default should be fine
