### ISSUE TITLE
Unable to override update.args alone

### ISSUE THREAD

**Issue by vaygr** [twpayne/chezmoi#3165]
## Describe the bug

I have a case with an older git where `--autostash` is not available. I'm unable to override just args until I specify the command itself, which is excessive. This is reproducible with **2.37.0**.

## To reproduce

```toml
[update]
    args = ["pull", "--rebase"]
```

## Expected behavior

`update` command is overridden.

## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```

</details>

## Additional context

N/A

**Comment by halostatue** [comment]
I’m not sure whether [`--use-builtin-git`](https://www.chezmoi.io/reference/command-line-flags/global/#-use-builtin-git-value) would work for you or not, but it is kept rather more up to date than some system `git`s.

**Comment by vaygr** [comment]
@twpayne so this is by design? why not allow to override `update.args` without specifying `update.command`?

**Comment by twpayne** [comment]
Yes, this is by design. If `update.args` could be overridden without specifying `update.command` then the behavior when using the builtin git would be confusing, as the builtin git does not support `update.args`.

With this the design, you can choose from many different options:

Firstly, by default, whether or not you have git installed, `chezmoi update` will do the right thing, using the builtin git if necessary.

Secondly, if you want more control then you can set `update.command` and optionally `update.args` to control exactly what command chezmoi runs.

**Comment by vaygr** [comment]
Excellent, that explains why it is the way it is. Thanks!
