### ISSUE TITLE
[hg] init with URL not working out of the box

### ISSUE THREAD

**Issue by ashemedai** [twpayne/chezmoi#3233]
## Describe the bug

Chezmoi init does not seem to work out of the box for Mercurial due to the insistence of `--recurse-submodules` for non-Git commands.

## To reproduce

1. Have a `.config/chezmoi/chezmoi.yaml` file with `git: command: hg`
2. Try to do something like `chezmoi init --verbose https://example.com/dotfiles`

## Expected behavior

Chezmoi to take a slightly different code path applicable for Mercurial without having to add all kinds of, for Mercurial, non-sensical flags.

## Output of command with the `--verbose` flag

```console
% chezmoi init --verbose https://example.com/dotfiles
hg clone: option --recurse-submodules not recognized
hg clone [OPTION]... SOURCE [DEST]
```

## Output of `chezmoi doctor`

<details>

```console
RESULT    CHECK                MESSAGE
ok        version              v2.39.1, commit fe10a696fb9aad76776bce62f9fa9a4363bac62a, built at 2023-09-06T12:50:07Z, built by goreleaser
ok        latest-version       v2.39.1
ok        os-arch              freebsd/amd64 (FreeBSD 12.4-STABLE)
ok        uname                FreeBSD notexposing.example.com 12.4-STABLE FreeBSD 12.4-STABLE r373129 NEXUS  amd64
ok        go-version           go1.21.0 (gc)
ok        executable           /usr~/.local/bin/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.yaml, last modified 2023-09-13T21:38:51+02:00
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        umask                022
ok        cd-command           found /usr/local/bin/zsh
ok        cd-args              /usr/local/bin/zsh
info      diff-command         not set
ok        edit-command         found /usr/local/bin/nvim
ok        edit-args            nvim
warning   git-command          found /usr/local/bin/hg, cannot parse version from Mercurial Distributed SCM (version 6.5)
(see https://mercurial-scm.org for more information)

Copyright (C) 2005-2023 Olivia Mackall and others
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
ok     merge-command               found /usr/local/bin/vimdiff
ok     shell-command               found /usr/local/bin/zsh
ok     shell-args                  /usr/local/bin/zsh
[snip]
```

</details>

## Additional context

You can make it work with `chezmoi init --verbose --recurse-submodules=false https://example.com/dotfiles`, but it gives a bit of a bad first impression and experience.

```console
% chezmoi init --verbose --recurse-submodules=false https://example.com/dotfiles
Please enter password for encrypted keyring:
requesting all changes
adding changesets
adding manifests
adding file changes
added 1 changesets with 56 changes to 56 files
new changesets 1bf069e69e9c
updating to branch default
56 files updated, 0 files merged, 0 files removed, 0 files unresolved
```

Interested to make this work and happy to code on it. Just want to make sure that it would get accepted before I spend time on it.

**Comment by halostatue** [comment]
Can you try setting `args: ["clone"]`?

**Comment by twpayne** [comment]
Thanks for [talking before coding](https://dave.cheney.net/2019/02/18/talk-then-code)!

Note that `hg` is not a drop-in replacement for `git` so setting `git.command` to `hg` is not going to work. The `--recurse-submodules` flag is one example, but Mercurial's modus operandi is fundamentally different to git's, so this is more about adding support for Mercurial to chezmoi.

Note that early versions of chezmoi did support pluggable VCSes, including Mercurial, but this was dropped in #459 due to lack of use. A request was made for pijul support in #1801 but there was no second message from the requester.

If you're happy to work on this, then please do. I'll assign this issue to you. A few notes/suggestions:

1. Please follow [chezmoi's contributing guide](https://www.chezmoi.io/developer/contributing-changes/).
2. Adding functionality incrementally is fine. An initial PR that adds Mercurial support to [`chezmoi init`](https://www.chezmoi.io/reference/commands/init/) would be a great start. I would consider adding either a flag like `--hg` or a recognizable pattern like `hg://example.com/dotfiles` to allow the user to concisely communicate to `chezmoi init` that it's using a Mercurial repo.
3. At some point, there should probably be a `mercurial` section in chezmoi's config with `mercurial.command` and `mercurial.args` variables.
4. Optionally, follow-up PRs can add deeper Mercurial support, for example to [`chezmoi update`](https://www.chezmoi.io/reference/commands/update/), a `chezmoi hg` command equivalent to [`chezmoi git`](https://www.chezmoi.io/reference/commands/git/), and maybe eventually [autocommit and autopush functionality](https://www.chezmoi.io/user-guide/daily-operations/#automatically-commit-and-push-changes-to-your-repo). However, all extra Mercurial support is optional.

So, yes, I would happily accept PRs that add Mercurial support :)

**Comment by halostatue** [comment]
@twpayne One other thing that would be good for this would be to make it so that an empty `.git` directory doesn't mark the [root of the source repo](https://www.chezmoi.io/user-guide/advanced/customize-your-source-directory/#use-a-different-version-control-system-to-git).

Not every VCS will have a root directory marker, but IIRC, Mercurial has `.hg`.

**Comment by ashemedai** [comment]
> Can you try setting `args: ["clone"]`?

I'll try that today.

**Comment by ashemedai** [comment]
> @twpayne One other thing that would be good for this would be to make it so that an empty `.git` directory doesn't mark the [root of the source repo](https://www.chezmoi.io/user-guide/advanced/customize-your-source-directory/#use-a-different-version-control-system-to-git).
> 
> Not every VCS will have a root directory marker, but IIRC, Mercurial has `.hg`.

With Mercurial I did not have to set an empty .git directory to get the working tree properly recognised. Haven't looked at why yet.

**Comment by ashemedai** [comment]
> Note that `hg` is not a drop-in replacement for `git` so setting `git.command` to `hg` is not going to work. The `--recurse-submodules` flag is one example, but Mercurial's modus operandi is fundamentally different to git's, so this is more about adding support for Mercurial to chezmoi.

So when the documentation talked about drop-in replacement it essentially meant a non-official implementation of git? E.g. [Game of Trees](https://gameoftrees.org/).

I initially figured since a lot of the commands overlap between git and hg it would thus quality as (mostly) drop-in. So good to know.

> Note that early versions of chezmoi did support pluggable VCSes, including Mercurial, but this was dropped in #459 due to lack of use. A request was made for pijul support in #1801 but there was no second message from the requester.
> 
> If you're happy to work on this, then please do. I'll assign this issue to you. A few notes/suggestions:
> 
>     1. Please follow [chezmoi's contributing guide](https://www.chezmoi.io/developer/contributing-changes/).

✅ 

>     2. Adding functionality incrementally is fine. An initial PR that adds Mercurial support to [`chezmoi init`](https://www.chezmoi.io/reference/commands/init/) would be a great start. I would consider adding either a flag like `--hg` or a recognizable pattern like `hg://example.com/dotfiles` to allow the user to concisely communicate to `chezmoi init` that it's using a Mercurial repo.

Good point, need to see what causes the least problems going forward.

>     3. At some point, there should probably be a `mercurial` section in chezmoi's config with `mercurial.command` and `mercurial.args` variables.

✅ 

>     4. Optionally, follow-up PRs can add deeper Mercurial support, for example to [`chezmoi update`](https://www.chezmoi.io/reference/commands/update/), a `chezmoi hg` command equivalent to [`chezmoi git`](https://www.chezmoi.io/reference/commands/git/), and maybe eventually [autocommit and autopush functionality](https://www.chezmoi.io/user-guide/daily-operations/#automatically-commit-and-push-changes-to-your-repo). However, all extra Mercurial support is optional.

Yeah, that will definitely come. Doesn't make sense to only add support for, say, init and then call it a day. I would prefer to at least get basic support for all those functionalities. Of those autocommit and autopush are definitely at the end though.

**Comment by twpayne** [comment]
> So when the documentation talked about drop-in replacement it essentially meant a non-official implementation of git?

No, it's more for if the `git` command is at a non-standard path. chezmoi expects `git.command` to be git, not any other version control system.

**Comment by dertuxmalwieder** [comment]
> Note that early versions of chezmoi did support pluggable VCSes, including Mercurial, but this was dropped in https://github.com/twpayne/chezmoi/issues/459 due to lack of use.

FWIW, just to add a voice here, the inability to use chezmoi with Fossil (where I [keep my dotfiles](https://code.rosaelefanten.org/dotfiles) - GitHub is a one-way mirror for me) makes it less likely that I'll ever try it. So - CCing myself here - maybe an actually maintained multi-VCS support comes out of this again :)

**Comment by twpayne** [comment]
> FWIW, just to add a voice here, the inability to use chezmoi with Fossil (where I [keep my dotfiles](https://code.rosaelefanten.org/dotfiles) - GitHub is a one-way mirror for me) makes it less likely that I'll ever try it.

For Fossil, see also #2577. The implicit entitlement in your comment - that chezmoi should cater to your demands before you'll ever considering trying it is unwelcome. See [this discussion](https://github.com/twpayne/chezmoi/discussions/2819). 

> So - CCing myself here - maybe an actually maintained multi-VCS support comes out of this again :)

Support for non-git VCSes will require contribution and maintenance from the community as all of the core maintainers use git.

**Comment by dertuxmalwieder** [comment]
Feature requests are toxic and unwelcome, I see. Always glad to have a friendly discussion with welcoming, inviting project contributors.

I agree that something is toxic here. Goodbye then.
