### ISSUE TITLE
Show absolute path or path relative to CWD in status

### ISSUE THREAD

**Issue by Lattay** [twpayne/chezmoi#3242]
## Is your feature request related to a problem? Please describe.

When I use `chezmoi status` I always want to copy paste the path that are provided to add them, but if I am not in my home, I have to change the file.

## Describe the solution you'd like

Path could be printed as absolute path (eventually using `~`) or could be relative the the current working directory.

## Describe alternatives you've considered

Failing the first time then rewriting the command with edited path.

## Additional context

I am willing to contribute the feature myself if that's something that would be merged.

**Comment by twpayne** [comment]
Sounds good! This is a nice addition that would definitely be merged :) Thanks for [talking before coding](https://dave.cheney.net/2019/02/18/talk-then-code).

The [`chezmoi managed` command has a `--path-style` flag](https://www.chezmoi.io/reference/commands/managed/#-p-path-style-absoluterelativesource-absolutesource-relative) with the core of the implementation [here](https://github.com/twpayne/chezmoi/blob/b0862194919262e73bbf8d9b54ac561a33d65720/internal/cmd/managedcmd.go#L92-L102).

There's some `~` substitution code [here](https://github.com/twpayne/chezmoi/blob/b0862194919262e73bbf8d9b54ac561a33d65720/internal/cmd/doctorcmd.go#L431-L434), however I would be tempted to **not** substitute `~` in this case because the output of `chezmoi status` is rarely posted publicly and support for `~` depends on the program interpreting the filename. It's interpreted by many shells, for example, but not all editors.

**Comment by Lattay** [comment]
Cool, let's go.

Is there a way to set the command flags values in the config file too?
I would like to have `--path-style=absolute` the default for me, but it should be not be the default default for retro compatibility I guess.

> There's some ~ substitution code [here](https://github.com/twpayne/chezmoi/blob/b0862194919262e73bbf8d9b54ac561a33d65720/internal/cmd/doctorcmd.go#L431-L434), however I would be tempted to not substitute ~ in this case because the output of chezmoi status is rarely posted publicly and support for ~ depends on the program interpreting the filename. It's interpreted by many shells, for example, but not all editors.

I am fine with that, I won't implement substitution then.

**Comment by twpayne** [comment]
> Is there a way to set the command flags values in the config file too?

Yes, add them to [this structure](https://github.com/twpayne/chezmoi/blob/b0862194919262e73bbf8d9b54ac561a33d65720/internal/cmd/statuscmd.go#L13-L18) and to [this file](https://github.com/twpayne/chezmoi/blob/b0862194919262e73bbf8d9b54ac561a33d65720/assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml).

> I would like to have `--path-style=absolute` the default for me, but it should not be the default default for retro compatibility I guess.

Agree, makes sense.

I'm sure you've already seen the [developing locally guide](https://www.chezmoi.io/developer/developing-locally/) and the [contributing changes doc](https://www.chezmoi.io/developer/contributing-changes/).

**Comment by Lattay** [comment]
Thanks for the pointers and also thanks for the docs links, I missed them. Moving the discussion to the PR if that OK for you.

**Comment by twpayne** [comment]
Fixed by @Lattay in #3244.
