### ISSUE TITLE
Add conditions directive/frontmatter and pieces

### ISSUE THREAD

**Issue by mcexit** [twpayne/chezmoi#3327]
## Is your feature request related to a problem? Please describe.

I have a love-hate relationship with Go templates. I love the simplicity, but hate the verbosity. Nearly every config template I create starts out with a bunch of conditions. A common example is `lookPath` or `hasKey`.

## Describe the solution you'd like

This is sort of two feature requests but they make the most sense together.

First, what I mean by a conditions directive/frontmatter is it would be great to have a way to more simply list conditions for each component upfront including data variables.

### Use case for data variables

I'll start out with the most useful examples and this is accompanies #3326 nicely, but I'll pretend that doesn't get implemented here.

`./.chezmoidata/environment/firefox.jsonc`
```jsonc
/*
chezmoi:conditions:
  lookPath:
    - firefox
    - sway
*/
{
	"environment": {
		"MOZ_ENABLE_WAYLAND": 1
	}
}
```

`./.chezmoidata/environment/java.jsonc`
```jsonc
/*
chezmoi:conditions:
  lookPath:
    - java
*/
{
	"environment" {
		"JDK_JAVA_OPTIONS": "-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dsun.java2d.opengl=true"
	}
}
```

`./private_dot_config/exact_environment.d/managed.conf.tmpl`
```gotmpl
{{ range $key, $value := .environment }}
{{ key }}="{{ $value }}"
{{ end }}
```

### Use case for templates

This is useful for single templates, but where it could really come in handy is if there was a way to generate a file based on pieces from a folder with templates that each have additional conditionals.

I would like to see this cover two use cases.

#### 1. Numerical Order

The ability to assign a numerical order to each file based on the order in which they should be processed and included. This reminds me a lot of Ansible's [assemble](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/assemble_module.html) module:

`./private_dot_config/exact_environment.d/pieces_managed.conf.tmpl`
```markdown
# chezmoi:conditions:
#   lookPath:
#     - systemctl

# Can include text or templated data here that will get processed before any pieces, e.g.:
CHEZMOI_PIECED=1
```

`./private_dot_config/exact_environment.d/pieces_managed.conf/1_firefox.tmpl`
```markdown
# chezmoi:conditions:
#   lookPath:
#     - firefox
#     - sway

MOZ_ENABLE_WAYLAND=1
```

`./private_dot_config/exact_environment.d/pieces_managed.conf/2_java.tmpl`
```markdown
# chezmoi:conditions:
#   lookPath:
#     - java

JDK_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dsun.java2d.opengl=true'
```

#### 2. Post tasks

These templates run after numerical pieces have been assembled, and it doesn't matter which order they are ran in. Each one modifies the file, and then passes it on to the next.

`./private_dot_config/exact_environment.d/pieces_managed.conf/x11.tmpl`
```markdown
# chezmoi:conditions:
#   eq:
#     env:XDG_SESSION_TYPE: x11

{{ replaceAllRegex "^MOZ_ENABLE_WAYLAND=(.+)$" "${1}0" .chezmoi.pieced }}
```

In the end, you might end up with something like this:

`~/.config/environment.d/managed.conf`
```
CHEZMOI_PIECED=1
MOZ_ENABLE_WAYLAND=0
JDK_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dsun.java2d.opengl=true'
```

## Describe alternatives you've considered

I've explored other dot file managers and automation tools, but none of them are built for this.

## Additional context

The Chezmoi developers provide their wonderful open source tool to the community for free and their time is greatly valued and appreciated. I don't have any expectations that this will get implemented. However, any feedback is welcome so that if someone is interested in doing the work it is good to know in advance if the project maintainers would be open to accepting a PR.

**Comment by halostatue** [comment]
I think that these would be better examined separately, as while they may work *well* together, the cases for them would need to be made independently as they both have fairly large impact on how chezmoi works.

**Comment by halostatue** [comment]
## Condition Directives

This is a major change to how chezmoi directives work. Right now, they're a simple regular expression match with line removal. They're fast, easy to parse, and have zero impact on the output of the templates, but change how the templates engine is configured.

This would be more akin to adding front matter to templates, and would need their own parser. Your examples use a YAML-ish format that would require:

1. non-greedy parsing (reading possible conditions until we hit something that doesn't look like a condition) *or* a sigil (`chezmoi:endconditions`)
2. parsing the resulting keys and values in ways that may not be directly compatible with the template functions
3. calling the template functions referenced *outside* of the context of a template

In your Firefox example, `lookPath` doesn't *work* that way (it accepts a single argument), so the custom language described here would have a lot of heavy lifting to perform.

I personally find

```
/*
chezmoi:conditions:
  lookPath:
    - firefox
    - sway
*/
```

to be less readable than

```
{{- if and (lookPath "firefox") (lookPath "sway")) -}}
```

barring the need for the `{{- end -}}` at the end of the file, too.

In my dotfiles, I’ve got enough `lookPath` calls that I've made [`programs.tmpl`](https://github.com/halostatue/dotfiles/blob/main/home/.chezmoitemplates/programs.tmpl) that I include:

```
{{- $programs := includeTemplate "programs.tmpl" | fromJson -}}
{{- if and $programs.firefox $programs.sway -}}
…
{{- end -}}
```

**Comment by twpayne** [comment]
Thank you for the kind words and the interesting and clearly presented idea! I also struggle a lot with Go templates, but...

I am strongly opposed to the ideas presented here for multiple reasons:

1. Condition directives are an example of the [inner platform effect](https://en.wikipedia.org/wiki/Inner-platform_effect). Specifically, this is inventing a new way to write conditional expressions when chezmoi already supports conditional expressions via Go templates. As demonstrated with the `lookPath` example, the interpretation of this language is under-specified and will require a large amount of magic (or heavy lifting as @halostatue calls it).

2. Implementing `pieces_` will require a lot of specialized code to handle, but, more importantly, will be difficult to use because the user will have to reason about multiple, possibly conflicting, files simultaneously.

As an alternative, consider how the `./private_dot_config/exact_environment.d/managed.conf.tmpl` example looks using chezmoi's existing mechanisms:

```template
CHEZMOI_PIECED=1

{{- if or (lookPath "firefox") (lookPath "sway") }}
MOZ_ENABLE_WAYLAND={{ ne (env "XDG_SESSION_TYPE") "x11" | int }} 
{{- end }}

{{- if (lookPath "java") }}
JDK_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dsun.java2d.opengl=true'
{{- end }}
```

This is a single short file that clearly communicates what the contents of `~/.config/environment.d/managed.conf` should be.

For more complicated examples, as @halostatue points out, chezmoi already has the `include` and `includeTemplate` functions that allow you to assemble multiple files.

As another alternative, if the program that reads the files in `~/.config/environment` reads **all** the files in `~/.config/environment`, then you can create separate files in `./private_dot_config/exact_environment.d` for each variable that you want to set.

As a side-rant, I've had the misfortune of having had to write Ansible playbooks in the past, and Ansible's attempt to use YAML as a programming language was (and maybe still is?) and unmitigated disaster. Specifically, YAML is a data declaration language and does not have control flow. Ansible needs control flow and so tries to add it to YAML, and the result is the exact Inner-platform effect: a weak, under-specified, language with no tooling. As much as Puppet's declarative approach was a strong source of inspiration for chezmoi, Ansible is the exact opposite of what I want chezmoi to be.

So, thank you again for the well-considered proposal, but no.

**Comment by halostatue** [comment]
> The thing that nags me about Go templates is that with grouping multiple conditions, the parenthesis approach seems to be the most logically ordered but can put you into what I call parenthesis hell, where at the end you may end up with a bunch of ')))))'. Some indention and newlines help, but in the end I just feel dirty and have a bunch of extra newlines just so I can figure out where my parenthesis start and end.

That's why I pointed out the `$programs` import template approach that I use. In some ways, I did not need that (because chezmoi caches `lookPath` results), but in others I absolutely did. I can now do:

```
{{ if or $programs.in2csv $programs.soffice $programs.xlsx2csv $programs.xlsx2csvPy -}}
```

From [home/proviate_dot_config/git/attributes.tmpl:75](https://github.com/halostatue/dotfiles/blob/23c0b3bd27442f9fda1de60c33476079e8f99b42/home/private_dot_config/git/attributes.tmpl#L75).

No parenthesis in sight, and I think fairly understandable. Maybe I should change the name I use from `$programs` to `$has` (I often write a bash function `has() { command -v "$@" >/dev/null 2>&1; }`) or something similar, but the name isn't the hardest part here. In your case `{{ if and $programs.firefox $programs.sway }}`.
