### ISSUE TITLE
use 'open' KeepassXC-cli command

### ISSUE THREAD

**Issue by MathieuDR** [twpayne/chezmoi#3440]
## Is your feature request related to a problem? Please describe.

Just as issue #2002, I'm using a yubikey for my password manager together with a password.

## Describe the solution you'd like

Is the `open` command a feasible solution to create a type of session to request multiple passwords/attributes without asking for the password/Yubikey multiple times?

## Additional context

I have not a deep understanding of the inner workings of Chezmoi & KeepassXC-cli

**Comment by halostatue** [comment]
That would mostly be limited to how KeepassXC works, but I do not believe that this would be easily possible. I don't use KeepassXC but some testing shows that `keepassxc-cli open` opens a shell. Chezmoi does not hold a session open for a command-line tool, which is what would be required here. Chezmoi would need to keep a keepassxc-cli process running for the duration of the command and the command that uses that would need to know how to interact with the commands *in* the shell.

I think that if someone were to propose and/or create a PR for this sort of thing, it would be considered — but the hard part would be addressing keeping the command-line session open for executing the commands in the shell. It would *probably* need to be a separate command than the current mechanism as it would need to work via goroutines, and I don’t think anything in chezmoi does that right now.

This isn't required with tools like 1Password (`op`) because it manages an active session tied to a specific terminal instance on its own if you are using biometrics (if you are not, then you need to set `OP_SESSION` as documented; the 1Password sessions are only good for ~15 minutes). BitWarden's default command-line tool (`bw`) requires its own environment variable be set (like `OP_SESSION`, but the sessions are good until the token is explicitly invalidated) and the `rbw` third-party tool has a computer-level active session management mechanism (other terminal sessions also benefit) and has a default 1 hour inactivity expiration (configurable).

**Comment by twpayne** [comment]
For info, I'm experimenting with this idea. Programs like [`expect`](https://linux.die.net/man/1/expect) can talk to interactive programs like `keepassxc-cli open`, and I'm trying [this Go library](https://github.com/Netflix/go-expect).

**Comment by MathieuDR** [comment]
I found a workaround that might be worth noting in the documentation.

It is a bit less secure and requires a bit of setup in the database, but in my opinion, it was worth it to make it integrate much better.

1. I've setup a directory in my KeepassXC database to be exported with `KeeShare` (A native feature).
2. Export this as a .kdbx protected with only a password
3. Use this .kdbx with Chezmoi
