### ISSUE TITLE
Externals using 1Password documents

### ISSUE THREAD

**Issue by halostatue** [twpayne/chezmoi#3455]
Since 1Password can store *documents* and not just passwords, I am thinking that it would be great to have a way of obtaining externals that aren't HTTPS URLs or git repositories. I currently compose my `~/.aws/credentials` file from multiple 1Password documents, but I am thinking of moving my git identity information *into* 1Password as a file so that they can be used with `includeIf` directives:

```gitconfig
[includeIf "gitdir:~/work"]
  path = ~/.config/git/identities/work
```

I *could* use `onepasswordDocument` in a template at `~/.config/git/identities/work`, but it feels unnecessary to have a template when I could do something like:

```yaml
.config/git/identities/work:
  type: onepassword-file
  url: op://vault/filename
  account: halostatue
```

Although my interest is in 1Password, I believe that *other* password managers have file storage capabilities, so this might be extensible. The parameters for a `onepassword-file` (or whatever we call it) might not be a URL (because that is not a normal `op get op://URL`) but could be `name`, `uuid`, `vault`, `account`.

This might not be a good idea, but I thought it would be an interesting thing to consider, even if we don't end up doing it because `{{ onepasswordDocument NAME VAULT ACCOUNT }}` *does* in fact work in a template.

**Comment by twpayne** [comment]
Thank you, this is an interesting idea and definitely worth considering.

My concerns are:

1. This breaks the 1:1 mapping between files in the source directory and target files. This mapping is of course already broken with externals, but the difference is that externals currently bring in files managed by a third party, rather than files managed by the user.

2. Currently all password manager interaction is via template functions and all password managers are isolated from each other. This proposal would require the [definition of an external](https://github.com/twpayne/chezmoi/blob/a450748cf0f672dd09cdf933c21de4e2049e45de/internal/chezmoi/sourcestate.go#L90-L108) to be extended to include all fields needed by any password manager. This will lead to a very bloated structure and there might be conflicts between the requirements to support different password managers.

3. The password manager interaction code would have to be moved from independent template functions into chezmoi's core, which will bloat chezmoi's core with code that should be isolated in some kind of module.

4. Any further processing on the file's contents, e.g. extracting fields or transforming text, is not easy.

In contrast, the existing mechanism of using templates and template functions:

1. Maintains the 1:1 mapping.
2. Keeps the definition of externals short.
3. Keeps the password manager interaction code isolated.
4. Allows the user to use templates and template functions to manipulate the returned document.

So, overall, I don't think we should do this.

**Comment by halostatue** [comment]
I mostly agree with you, but there are a couple of things:

1. This is true, but has always been possible to do this for yourself by having a tarball hosted somewhere semi-private (this is how that I tested one an issue related to external attributes).
2. You are correct, but that *could* be simplified and isolated by specifying a `onepassword` structure embedded in the external structure — but you would need to add one for each supported password manager that supports attachments. Depth bloat rather than width bloat.
3. Yes, it would.
4. The intent would be that it is handled just like any other external: you *don't* get to do anything else.

It's a little more complex than this, but this would be little different than supporting a custom transport protocol for externals (currently only `git` and `http`/`https` are fully supported, but nothing says that `sftp` or `ftp` couldn't be supported) .

The main benefit to this is that I could have a `git-identities.zip` file in 1Password and pull that down as a `1password-archive` and it would unzip the file just the same as any other external archive (I know that I showed the single file approach previously). I could have three different identities in the zip file and get the benefit of unarchiving them *once*, rather than having to make three different template documents for substitution (I have work and non-work identities that I use right now and they are not currently in chezmoi because I haven't worked out how I want to handle this).

I could *always* do this in a before/after script, so it isn’t urgent. But it’s been bouncing around my head for a few days and I wanted to raise it as something to consider.

One other thought: if there were a way to run a script / executable as an external's "handler", it would be possible to allow chezmoi users to write external "protocol" handlers that would not require further support from chezmoi.

**Comment by drwicid** [comment]
As a workaround, you can configure the generic secret function to closely approximate what you want.  Add the following to your config file:
```
[secret]
   command = "op"
   args = [ "read", "--force", "--out-file" ]
```

If `op read --out-file` is successful, `op` prints the full file path to standard out and returns success.  As such, the generic secret function can read the file and insert the resultant path into a template.  Example:
```
Host example
   HostName example
   User user
   IdentityFile {{ secret (joinPath .chezmoi.homeDir ".ssh/id_rsa") "op://vault/item/id_rsa" }}
```

Another option is a `run_once_before_onepass_externals.tmpl` which could stash as many disparate 'externals' without "generating any changes" on the system based on the empty resulting template (like calling malloc without free). 
```
{{- $gobble := secret (joinPath .chezmoi.homeDir ".ssh/id_rsa") "op://vault/item/id_rsa" -}}
{{- $gobble := secret (joinPath .chezmoi.homeDir ".ssh/id_rsa.pub") "op://vault/item/id_rsa.pub" -}}
{{- $gobble := secret (joinPath .chezmoi.cacheDir "age.txt") "op://vault/item/age.txt" -}}
```

For me, usage would be very situational.  The risk of dangling secrets pulled from a password manager is more worrisome to me.

**Comment by halostatue** [comment]
The main problem with the `op read` approach is that I can't see a way to get an attached *document* unless it's encoded as a field.

I don't think that I will be pursuing this further. I think it’s a good idea, but needs a lot of work and should probably be done with the concept of a protocol handler for externals.
