### ISSUE TITLE
chezmoi does not recognize `msys2` or `cygwin` $HOME

### ISSUE THREAD

**Issue by Kreijstal** [twpayne/chezmoi#3561]
## Describe the bug

In case you are using chezmoi in cygwin or msys on windows 11 fresh install, installed by either `scoop install chezmoi` or the sh technique, if you do it on a msys2 shell, chezmoi gets confused about where the home is since the msys2 home is not the same as the windows home.. Not sure if you consider this use case important.

**Comment by halostatue** [comment]
It has been a while since I used msys2 or cygwin as it's been a while since I used Windows, but given that both msys2 and cygwin are layered on top of Windows, this is not a surprise.

There are a few [command-line parameters](https://www.chezmoi.io/reference/command-line-flags/global/) and corresponding [configuration variables](https://www.chezmoi.io/reference/configuration-file/variables/) which will help with this:

- `--cache` (`cacheDir`)
- `--config`
- `--destination` (`destDir`)
- `--persistent-state` (`persistentState`)
- `--source` (`sourceDir`)
- `--working-tree`

You would probably want to make shell scripts or aliases that run chezmoi with the `--config` parameter for your msys/cygwin configuration, and you'd probably want a different configuration than your standard Windows configuration because there will be behavioural differences even though msys and cygwin are very leaky abstractions.

If you do something like this and get it working, a post in [Show & Tell](https://github.com/twpayne/chezmoi/discussions/categories/show-and-tell) would not be inappropriate for this unusual but real use case for chezmoi.

**Comment by Kreijstal** [comment]
`./bin/chezmoi.exe -D $HOME -S $HOME/.local/share/chezmoi init --apply $USERNAME` works, or maybe the build has not gone public yet.

**Comment by bradenhilton** [comment]
@Kreijstal The fix hasn't been released yet. Is `./bin/chezmoi.exe` in your example a release version? Or did you build chezmoi from source/download the [artifact](https://github.com/twpayne/chezmoi/actions/runs/7905217301/artifacts/1245594035)?

**Comment by Kreijstal** [comment]
> @Kreijstal The fix hasn't been released yet. Is `./bin/chezmoi.exe` in your example a release version? Or did you build chezmoi from source/download the [artifact](https://github.com/twpayne/chezmoi/actions/runs/7905217301/artifacts/1245594035)?

ah yeah that was the release version, sorry, haha
