### ISSUE TITLE
Manage different platforms in a single repo

### ISSUE THREAD

**Issue by edgeboy47** [twpayne/chezmoi#3580]
## What exactly are you trying to do?

I'm trying to create and manage a single GitHub repo that has dotfiles for different OSes, Windows and Linux, as shown below.

![image](https://github.com/twpayne/chezmoi/assets/33768936/c05c7e8a-034c-4a4d-81b3-c16b379c1fab)

I want it to be such that the repo has a folder for each OS, and I can setup chezmoi to push directly to the respective folder. For example, if I am on Windows and I `chezmoi add .wezterm.lua` , and then run `chezmoi apply` and do the regular git flow to push to the repo, I would like the wezterm.lua file to go directly to the Windows folder in the repo. I realize this might be more of a git issue than a chezmoi issue, but I'm honestly not sure how to set it up or if it's even possible.

## What have you tried so far?

- I tried setting the folder of the repo as the git remote but that's not possible. 
 
If this is not possible I have the fallback solution of just creating two separate repos, one for each OS.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.

**Comment by twpayne** [comment]
This is not how chezmoi is designed to be used. chezmoi uses a single source of truth for all machines so you can share common configuration across all machines and then manage machine-to-machine differences.

However, if you insist on using a separate directory per OS then consider using a separate git branch per OS, instead of a separate git repo per OS. You will need to manually copy changes between branches.

However, I recommend using chezmoi as it is designed to be used.

**Comment by edgeboy47** [comment]
I figured as much. Thanks for the clarification.
