### ISSUE TITLE
Add support for template prefix

### ISSUE THREAD

**Issue by senekor** [twpayne/chezmoi#3767]
## Is your feature request related to a problem? Please describe.

Adding the `.tmpl` suffix to any file usually breaks editor support for that file.
This is not necessary in my experience, most templating syntax can be stuffed into string literals and comments of languages like bash and toml.
I would like to enjoy a normal editor experience when editing templates in my chezmoi repo.

## Describe the solution you'd like

Alongside the `.tmpl` suffix, it could be possible to add a `tmpl_` prefix to a file name.
Editors would then recognize the correct file type.

## Describe alternatives you've considered

None come to mind.

**Comment by halostatue** [comment]
The [Go Template extension](https://github.com/jinliming2/vscode-go-template?tab=readme-ov-file) for VS Code can perform Go template highlighting within a different syntax already, although some tweaking may be required. [chezmoi.vim](https://github.com/alker0/chezmoi.vim) does the same nested syntax highlighting for Chezmoi tmpl files (note that it has strict loading requirements so it cannot be installed like any other Vim extension). [chezmoi.el](https://github.com/tuh8888/chezmoi.el) might be able to help here, too.

This is an interesting idea which is worth examining deeper. The template extension is already an attribute modifiable with `chezmoi chattr template <target>` so this shouldn’t be too hard to *detect*, but the default behaviour would probably be to continue to append `.tmpl` instead of prepending `tmpl_`.

**Comment by senekor** [comment]
I use helix :slightly_smiling_face:

But now that you mention that other editors have support, I thought about how that support could be added to helix (it has no plugin system).
Turns out the configuration options for language detection is quite powerful:

```
[[language]]
name = "bash"
file-types = [ "sh", "bash", { glob = "*.sh.tmpl" } ]
[[language]]
name = "toml"
file-types = [ "toml", { glob = "*.toml.tmpl" } ]
```

This addition to `~/.config/helix/languages.toml` fixes 99% of the problem for me.

I think my proposal could still be of value to other people.
Having to add support manually to each editor or telling users to add specific configuration isn't the best solution.
For me personally, the problem is mostly solved.

**Comment by twpayne** [comment]
`.tmpl` was deliberately used as a suffix (instead of a `template_` prefix) because `.tmpl` files in chezmoi are Go templates, not bash scripts or TOML files or whatever, so highlighting them as bash scripts or TOML files would be incorrect.

Adding a `template_` suffix in addition to a `.tmpl` prefix would add ambiguity. chezmoi often needs to generate the source name from the target name (e.g. when running `chezmoi add --template`) so would need extra configuration for the user express their preference for prefix or suffix, in addition to tracking which (or both) are used in existing files.

The correct thing to do, as has been described, is to configure your editor to highlight template files to your preferences.

I'll add a FAQ entry at some point. In the meantime, I'll close this as "not planned".
