### ISSUE TITLE
Flag --managed to `add` all managed files

### ISSUE THREAD

**Issue by aaharr** [twpayne/chezmoi#3836]
## Is your feature request related to a problem? Please describe.

I freqently edit managed files in place, and find myself doing recursive adds to try to catch changed files I might have missed. I wind up running `status` then `add` for each file, then `diff` as a sanity check.

## Describe the solution you'd like

A lazier workflow could be a command `cm add --managed` or some such.

## Describe alternatives you've considered

Making all my config files read only so I can't edit them in place.. this seems like the wrong thing to do.
Conditionally aliasing edit to cm edit. Not sure what the condition would be exactly.
Adding hooks in my editor to detect certain files, but then my editor needs to know about managed files (more work).
Auto-committing, but this would only apply to changes that have been added no?

## Additional context
Chezmoi is a lovely tool🥇

**Comment by bradenhilton** [comment]
Have you tried [`re-add`](https://www.chezmoi.io/reference/commands/re-add/)?

**Comment by halostatue** [comment]
Or `merge-all`? Using `merge-all` is probably the better choice here given your current workflow.

**Comment by aaharr** [comment]
@bradenhilton No.. I guess I find the description confusing. Does the "re" mean recursive or "again". If recursive, why have add -r? If again, does that mean add is not idempotent? 

@halostatue Except for templates I always want the local file to overwrite what's in cm at this point. If I want to merge I'd rather do that in git but it hasn't come up yet. Unless I'm misunderstanding what merge-all does as well.

**Comment by halostatue** [comment]
> @bradenhilton No.. I guess I find the description confusing. Does the "re" mean recursive or "again". If recursive, why have add -r? If again, does that mean add is not idempotent?

It's not recursive. It’s again.

```console
$ chezmoi re-add -h
Description:
  Re-add modified files in the target state, preserving any encrypted_
  attributes. chezmoi will not overwrite templates, and all entries that are
  not files are ignored. Directories are recursed into by default.

  If no targets are specified then all modified files are re-added. If one or
  more targets are given then only those targets are re-added.
```

> @halostatue Except for templates I always want the local file to overwrite what's in cm at this point. If I want to merge I'd rather do that in git but it hasn't come up yet. Unless I'm misunderstanding what merge-all does as well.

`merge-all` is essentially the same as a git merge, but it allows you to apply merging *even to templates* because you’re doing a three-way diff/merge operation (target [what you modified outside of chezmoi], source [the chezmoi file or template], and candidate target [what chezmoi will generate, which will be the same a source for non-templates]).

I’m using chezmoi on a single machine; I am typically using `merge-all` as my workflow to get changes back into chezmoi. Because I’m not on multiple machines, there will be no rebase merging to deal with.

I’m closing this because the feature you want is `chezmoi re-add` or `chezmoi merge-all` (I personally find `chezmoi merge-all` to be a more comprehensive workflow because it works with templates, too). There's no need to add a `--managed` flag to `chezmoi add`, and it will *absolutely* do the wrong for templates, encrypted attributes, and other special cases.
