### ISSUE TITLE
FEATURE REQUEST: chezmoi mv

### ISSUE THREAD

**Issue by gdevenyi** [twpayne/chezmoi#3918]
## Is your feature request related to a problem? Please describe.

I have large collection of config files of various types currently managed by chezmoi. I would like to cleanup the dotfiles in $HOME by relying on the support of the XDG standard.

To do this, I'm using https://github.com/b3nj5m1n/xdg-ninja to analyze which config files can be moved into another location.

From what I can tell, to do this right now, I will need to manually copy the config files, ask chezmoi to forget the config file, and add a new one in the new location.

## Describe the solution you'd like

A `chezmoi mv` command, which facilitates the forget/add cycle of renaming/moving files managed by chezmoi

## Describe alternatives you've considered

Do it manually.

**Comment by twpayne** [comment]
It's a bit more complicated as you probably also want to add a line to `.chezmoiremove` to remove the old entry.

In the short term you can use `chezmoi cd` and `git mv`.

**Comment by gdevenyi** [comment]
> It's a bit more complicated as you probably also want to add a line to .chezmoiremove to remove the old entry.

Right, I didn't know that was a thing, but it makes sense that if this change were applied elsewhere it would necessitate removing the old config as well. If I end up doing it manually this will help. Thanks.

**Comment by twpayne** [comment]
Thinking more about this, this is extremely hard to implement correctly. To behave reliably, the following two commands should have a net effect of zero:

```console
$ chezmoi mv a b
$ chezmoi mv b a
```

However, if `chezmoi mv a b` also adds an entry for `a` to `.chezmoiremove`, then `chezmoi mv b a` would have to remove that exact same entry. However, if `.chezmoiremove` already contains patterns that match `a` or `b` then any such logic is unlikely to work reliably.

Since the workaround of moving files around manually with `git mv` works well, and this is a rare usecase, I'm closing this as "won't fix".
