### ISSUE TITLE
Add configs from WSL to chezmoi

### ISSUE THREAD

**Issue by alex1yaremchuk** [twpayne/chezmoi#3956]
## Is your feature request related to a problem? Please describe.
I'd like to add config files from wsl to chezmoi

## Describe the solution you'd like
Chezmoi allows file paths not only in user's root folder.

## Describe alternatives you've considered
alternative is not to track wsl files with chezmoi 

## Additional context
I think that's it

**Comment by halostatue** [comment]
chezmoi is a home manager, not a system configuration manager. See #3766, #3813, #2840, and #3063 for similar discussions. A couple of those point to #2574 and to [Can I use chezmoi to manage files outside of my home directory](https://www.chezmoi.io/user-guide/frequently-asked-questions/design/#can-i-use-chezmoi-to-manage-files-outside-my-home-directory) — but this is outside of chezmoi's sweet spot and won't be implemented.

---

To solve your problem, you are better off treating WSL instances as separate machines (which they sort of are¹) than as "aspects" within a single machine configuration. Because you can run *multiple* WSL flavours, your configuration files will differ for each such instance. This can be managed with either ⓵ separate repos for each instance (not recommended) or ⓶ judicious use of `.chezmoiignore` and various detection mechanisms. You’ll need to run `chezmoi init` and `chezmoi apply` appropriately with either solution above, but they fit well within what chezmoi does well.

One caveat to what I have written above: I don't use Windows and therefore don't use WSL. That said, I’m pretty sure of my understanding of the architecture in question.

¹  ![](https://shuod.github.io/images/SetupWSL2_WSL2_architecture.png)

**Comment by alex1yaremchuk** [comment]
Thank you for this clarification.
I'll stick to standard attitude of a single repo and .chezmoiignore config file. 

Sorry for not investigating it thoroughly before posting!
