### ISSUE TITLE
Autotemplate configuration: `data-ignores` to selectively ignore data "paths"

### ISSUE THREAD

**Issue by vergenzt** [twpayne/chezmoi#3978]
## Is your feature request related to a problem? Please describe.

I'd love to the use `--autotemplate` flag! Unfortunately as many other issues have pointed out it's a bit too greedy and has required significant manual review of the output for me thus for to be able to use. Specifically I've had issues with `{{ chezmoi.pathSeparator }}` and `{{ chezmoi.pathSeparator }}`, `{{ chezmoi.pathListSeparator }}` and some command references (like for `git` and `op`).

## Describe the solution you'd like

I'd love to be able to simply configure lists of "data ignore" patterns to control which chezmoi data paths are considered for `--autotemplate`!

The way I envision it, at runtime, a command using `--autotemplate` would end up receiving a list of `data-ignore` pattern strings, which are essentially [`.chezmoiignore`](https://www.chezmoi.io/reference/special-files-and-directories/chezmoiignore/) patterns (i.e. doublestar patterns with an optional leading `!` to invert from exclusion to inclusion), but with periods as the "path separator" (to indicate map key descent) instead of slashes.

- The periods-as-path-separator could be handled by swapping periods and slashes in both the pattern and the "path" (list of map descent keys) right before calling `doublestar.Match`.

I'd envision these patterns being settable in two places:

1. In the config file `~/.config/chezmoi/chezmoi.<format>` – perhaps at `autotemplate.data-ignores[]`, which could be a list of strings.
2. An `--autotemplate-ignore=...` flag to add a single ignore pattern for just one invocation (which takes precedence over patterns from the config file, and may be specified multiple times).

## Describe alternatives you've considered

Not using `--autotemplate`? But it seems like the feature has such potential! And I think this could go a long way toward making it useful.

One other direction of extension I'm thinking about is maybe allowing individual files to specify they should be `--autotemplate`'d automatically on `chezmoi add`? That could probably come later though if this addition works out well.

## Additional context

Love this tool!

This is related to #2873.

**Comment by halostatue** [comment]
Could you update your description to include *examples* of the ignore patterns you want to support. Instead of describing them in `.chezmoiignore` terms, describe what would be *ideal* for what you want here.

An example of how `--autotemplate` has mangled a pattern would also be useful from my perspective.

I don't believe that autotemplate should ever be used without review as it might result in secrets being accidentally committed (although the addition of `gitleaks` *does* possibly introduce the ability to run the file being templated through the `gitleaks` code and adding "secret-templating" for nominally detected secrets if the results are clear enough from programmatic usage).

**Comment by twpayne** [comment]
Autotemplating is inherently fragile, and will never be able to generate good templates as it has no syntactic understanding of the file that it is generating the template for. Furthermore, the more template variables the exist, the greater the number of unwanted substitutions.

As @halostatue says, if you use `--autotemplate` then you have to manually review and fix the generated template.

Realistically, I do not think there is any reasonable fix for this.

**Comment by vergenzt** [comment]
Hey all. The main use I'm imagining for it to start would be to simply ignore `*` and then whitelist specific config keys that I'd want to use. For me that's mainly just `chezmoi.homeDir` (because on different machines I have different usernames) and a handful of custom data paths.

**Comment by halostatue** [comment]
I’m still not sure what sort of mangling `--autotemplate` has done that you’re trying to solve with this. I don't use auto-templating (I think I may have done so once or twice, but it's been a *long* time since I’ve used it), so I’m having a hard time understanding what you’re trying to *solve* here.
