### ISSUE TITLE
Template function for "default value" (but preserve local "destination" value if set)

### ISSUE THREAD

**Issue by scruloose** [twpayne/chezmoi#4051]
## Is your feature request related to a problem? Please describe.

The recurring annoyance of programs mixing config and state in one file, which necessitates managing **parts** of a file.

My current stumbling-block is the config file for geeqie, `geeqierc.xml`, which contains the ever-popular and ill-advised mix of actual configuration key-value pairs, along with various window position and dimension state that changes all the time and is wildly different on various systems with different monitor resolutions and so forth.

## Describe the solution you'd like

Ideally, I'd love to see a template function that provides a default value for a configuration key, to be used IFF the local "destination" file doesn't already define that key, but preserves the local value if it does.

## Describe alternatives you've considered

One option would be to set a bunch of per-machine "data" points, for things like `geequie-settings-window-pos-x`, `geequie-settings-window-pos-y`, and so forth. This suffers from the problem of cluttering up my per-machine data with a bunch of mostly-meaningless state info. It also means geeqie's dynamic updates to all those state datapoints will get clobbered (with "locally reasonable" fixed values, admittedly) on every `chezmoi apply`. It's pretty crude.

`chezmoi-modify-manager` is **almost** an option, but it doesn't support xml.

Writing a modify script should be reasonably possible, but having to translate the entire config file to a python data structure,
hard-coded into a custom script, and then implement all the regex/match/keep/replace logic from scratch, to then generate the whole config file with the right order and formatting and so forth… Well, we're getting farther and farther away from the convenience one would **ideally** expect a dotfiles manager to provide natively.

## Additional context

I am very much just getting to know chezmoi, and have very limited experience with `go`'s `text/template` language. So it's entirely possible there's already a way to do this that I don't know about, or that there are good reasons it's really hard to implement. I won't be offended if the answer turns out to be that my idea is hopelessly naive.

As far as I'm **aware**, though, chezmoi templates as it stands have access to chezmoi's database of local data values, but (unlike modify scripts) not the current ("before") state of the local destination file. I assume making that info available (whether it's as a big ol' string, or parsed into structured section/key/value data, or whatever) would be a necessary first step.

For my purposes, a literal string match (not counting whitespace) on the key, without regex capability, would be fine.

If I could check into chezmoi a template that's a direct line-by-line copy of my `geeqierc.xml` file, just with all the dynamic state entries replaced with template functions, conceptually like  `geequie-settings-window-pos-x = {{ preserveLocal "238" }}`, and have chezmoi handle the logic of "IF the local destination file exists AND contains key `geequie-settings-window-pos-x` THEN use the value defined there ELSE use this default of "238", I think that would be a way, **way** more convenient and accessible way to address the distressingly common case of needing to manage some lines and ignore others within a given config file.

**Comment by halostatue** [comment]
I understand your frustration with this and your request, but what you’re requesting is further from chezmoi's scope than managing non-$HOME directory files.

Chezmoi understands *nothing* about the structure of the files that are created or updated during `chezmoi apply`. To have a `local-preserving-default` would require that chezmoi understands the files that it manages. There are so many different *ways* of recording configuration that all of chezmoi's considerable code that already exists would be dwarfed by the code required to read, parse, and write those configuration files. Some configurations are relatively easy to parse (like XML, JSON, YAML, or TOML); others are themselves programming languages (Wezterm configuration is Lua scripts); others are bespoke formats that don't present themselves well as nested dictionaries (OpenSSH, others).

What you need is a `modify_` script that is either (1) aware of the Geeqie XML format or (2) can convert from XML to JSON and back to XML. If there is an external command which can be used to update the Geeqie XML stream, then you could do something like this:

``` title="modify_geeqie_config.xml"
{{/* modify_geeqie_config.xml */}}
{{- .chezmoi.stdin | output "echo" (.geeqie | toJson) -}}
```

`echo` would be replaced with a script that makes the changes you want. The first parameter would be the JSON representation of the Geeqie config and the second parameter would be the XML config itself.

**Comment by scruloose** [comment]
Thanks for your timely and informative answer! I see that I was indeed being quite naive.

A followup question, if I may.

Taking it as given that chezmoi does no **parsing** of the files, so any solution requiring awareness of structure like "keys" and "values" is way out of scope, would naive whole-line string matching be a reasonable possibility?

For example, my template for this specific case would be mostly the verbatim contents of `geeqierc.xml`, but a couple dozen lines (out of the total ~400) would make use of a function that does roughly "IF the current local file exists AND has a line that (ignoring leading whitespace) begins with `<key-string>`, THEN insert that entire line here, ELSE insert `<my-default-line>`.

So the invocation in context would look something along the lines of:
```
    <layout
        id = "lw1" 
        …
        {{- preserveLocal "main_window.x" "main_window.x = \"0\"" }}
        {{- preserveLocal "main_window.y" "main_window.y = \"27\"" }}
        tools_float = "false" 
        tools_hidden = "false" 
        …
    </layout>
```
(Example assumes `text/template`'s built-in chomping can be used to strip any leading whitespace, so the literal template contents **outside** the curly-brackets provide the indentation, while my "default" must be a self-contained string with the key and delimiter and quotation marks and everything so it can just be blindly dropped in as-is.)

Even nicer would be if "the dot" in this context can refer to just the string handed in as first parameter. If that's possible, it would tidy up the invocation to something like:
```
        …
        {{- preserveLocal "main_window.y" ." = \"27\"" }}
        …
```
(I don't know whether that's a legal way to concatenate `the value of dot` and `the string " = \"27\""` together, or if it would have to be `(print . " = \"27\"")` …or something.)

I may be mangling the quoting (at least) in my examples, but hopefully they illustrate the concept well enough to gauge whether there's any promise there.

If (and I recognize that it's a big "if") this level of format-agnostic whole-line match/keep/default granularity can reasonably be provided by chezmoi and `text/template`, I think that would make a night-and-day difference to the tractability of managing mixed config-and-state files **in general**, from an end-user perspective.

**Comment by halostatue** [comment]
> Taking it as given that chezmoi does no **parsing** of the files, so any solution requiring awareness of structure like "keys" and "values" is way out of scope, would naive whole-line string matching be a reasonable possibility?

Short answer: no. Chezmoi will detect that the file has *changed* since it was last written, but unless the source state has the `modify_` attribute, the only thing it does is *writes* the file. Also, Go `text/template` templates are executed as a whole (although conditionals can prevent entire sections from being executed at all).

Long answer: no, and that is why `modify_` exists, for those *extremely rare* cases where programs use the same file for current layout state and general configuration, or have other reasons that it is better to update what is present rather than to replace it as a whole. To use `modify_`, though, you *must* write something that can roundtrip the `geeqierc.xml` data with modifications. You can make such a thing a template `modify_geeqierc.xml.tmpl`, which means that you can place configuration data (`{{ . | toJson }}` ) inside your modify script.

I no longer use it, but I had a `private_modify_dot_netrc` file that did that:

https://github.com/halostatue/dotfiles/blob/e4d93d2f09e56581633a4195dd9d3c12bd294249/home/modify_private_dot_netrc.tmpl

> (Example assumes `text/template`'s built-in chomping can be used to strip any leading whitespace, so the literal template contents **outside** the curly-brackets provide the indentation, while my "default" must be a self-contained string with the key and delimiter and quotation marks and everything so it can just be blindly dropped in as-is.)

Be careful: `{{- -}}` is *greedy*, and will consume any and *all* whitespace before that. This was recently seen using a template like:

```
# foo
{{- "gpg" -}}
```

Which became `# foogpg` instead of `# foo\ngpg\n` (this is a simplification of the case).

> 
> Even nicer would be if "the dot" in this context can refer to just the string handed in as first parameter. If that's possible, it would tidy up the invocation to something like:

The dot as you refer to it, is the current context.  It’s worth reading the [text/template documentation](https://pkg.go.dev/text/template) in full, but note that in `{{with "output"}}{{printf "%q" .}}{{end}}`, the dot is the string `output`. There is no way for chezmoi to change that.

> I may be mangling the quoting (at least) in my examples, but hopefully they illustrate the concept well enough to gauge whether there's any promise there.

Sadly, there is not. What you want from chezmoi here is not possible — and this will be true of *any* home configuration management system that is unaware of the *interpretation* of specific configuration file formats.

In most cases like this, it would be better to open issues with the programs combining working state and pure configuration (`htop` is bad for this, IIRC) to fix their approach. chezmoi can't do this without a lot of fragile work that would be better spent figuring out how to manage #2273.
