### ISSUE TITLE
Difficult to figure out where changes are coming from

### ISSUE THREAD

**Issue by alper** [twpayne/chezmoi#4056]
Hi!

I didn't use chezmoi for 1-2 months and came back into it. So then when I run `chezmoi update` it tells me that there are a bunch of changes coming in and I can "overwrite" them. Honestly, I don't really know how or why these changes are coming in and whether or not I'm losing data like this.

I checked the usage guide and then saw this:
![CleanShot 2024-11-04 at 12 07 01@2x](https://github.com/user-attachments/assets/87cae3b8-45af-4850-864f-911fcc703e33)

Which explains it to say that: If there are four locations data can be in (and that's only for one machine!), then it's no wonder that it's very confusing.

Could it be possible to be clearer about where data is coming from and where it's going to? Would it be possible to remove entire layers of data here?

**Comment by KapJI** [comment]
If chezmoi tells you that files are going to be overwritten that means something externally changed them since the last time chezmoi touched them. E.g. you modified them manually without using `chezmoi edit` or some other tool. There should be a menu option to view the diff or skip the change.

**Comment by halostatue** [comment]
If you haven't run `chezmoi update` or `chezmoi apply` in a while and you or one of your tools may have modified files in your `$HOME`, I recommend running `chezmoi diff`.

My personal practice is to edit most files `in situ` (because my git configs are templated, it is easier to edit them in target, etc.) then run `chezmoi merge-all`, which lets me see (a) what is currently in target, (b) what is in source, and (c) what would be in target. For non-templated files, the diff between (a) and (b) tells you what differs; for templated files, it's (a) and (c), but you would need to edit (b) in order to incorporate changes that you wanted from (a).

**Comment by twpayne** [comment]
> Which explains it to say that: If there are four locations data can be in (and that's only for one machine!), then it's no wonder that it's very confusing.

Three of these layers are because of git.

> Could it be possible to be clearer about where data is coming from and where it's going to? Would it be possible to remove entire layers of data here?

Please read the [concepts in the reference manual](https://www.chezmoi.io/reference/concepts/). No, no layers can be removed.

**Comment by alper** [comment]
> f chezmoi tells you that files are going to be overwritten that means something externally changed them in home directory since the last time chezmoi touched them. E.g. you modified them manually without using chezmoi edit or some other tool. There should be a menu option to view the diff or skip the change

I know. I can work through it. Still no idea what is being changed or whether I may lose data.

My point is: You can explain it to me here and to everybody who comes after me but if the model is fundamentally this complicated… then this will keep happening.

There are way too many layers.

**Comment by twpayne** [comment]
Could you suggest some actual text that you would have found helpful?

**Comment by alper** [comment]
I can't really if the system is so muddy.

The major issue day to day is: When doing update, it's not clear with `diff` what is being diffed with what (from any of the 4+ possible locations) or if you do overwrite what is overwriting what in what direction.

I think things would be fixed by having two locations: "machine" and "repository" and making it abundantly clear what is going from machine to repo or the other way around. All the other locations should probably be plumbing that a normal user should never have to deal with.

**Comment by twpayne** [comment]
No, I'm not going to change the design of chezmoi.

**Comment by alper** [comment]
I'm not asking for the design to be changed, just the parts that a user has to deal with could be less focused on stuff that's plumbing.

**Comment by halostatue** [comment]
There are only two places that a user has to directly care about: the source path and the target (`working copy` and `home directory`, respectively). When chezmoi is performing `apply`, it *only*‡ cares about what's currently visible on disk in those two locations. When you run `chezmoi update`, it *effectively* does `cd "$(chezmoi source-path)" && git pull && chezmoi apply`. It does not read data from the parent repo for `apply`. One doesn't even *have* to have a parent repo for most chezmoi operations (and if one does, it doesn't have to be `git`).

When you ran `chezmoi update`, it updated your working tree from the parent repository and then applied them. It told you that you would be overwriting data because it found that the files had been modified in the target since the last time that `chezmoi apply` or `chezmoi update` had been run (this is all in the state database, `~/.config/chezmoi/chezmoi.boltdb`). 

I reiterate: if you regularly go some time between executions of `apply` or `update` and you regularly edit the files in your chezmoi target, you need to run `chezmoi diff` or `chezmoi merge-all` so you can see where the differences are so that you can reconcile them before you accidentally overwrite them.

If you have specific suggestions for documentation improvements, we can absolutely consider them.

‡ Modulo externals. Since those cache, the statement is "true enough".
