### ISSUE TITLE
template filename convention that doens't change file extension (i.e. `tmpl.filename.toml` over `filename.toml.tmpl`)

### ISSUE THREAD

**Issue by elkowar** [twpayne/chezmoi#4094]
## Is your feature request related to a problem? Please describe.

Having `.tmpl` be the file extension for templates means that now editors don't detect the filetype properly. If `tmpl` was a prefix, this would not be an issue. Yes, I'm aware there are a few editor plugins that solve this, and there are some other workarounds, but especially given the goal of setup-portability of chezmoi, _not_ changing the perceived file extension of template files would be great.

## Describe the solution you'd like

An option to configure chezmoi to name templates via `tmpl.<original filename>`, rather than `<original filename>.tmpl`

Given that I primarily use `{{ if ... }}` templates, those don't actually interfere with the regular language support of my editor as long as I keep them in comments, so this would be _very_ convenient.

## Describe alternatives you've considered

- chezmoi-specific Editor plugins (-> needs explicit setup in the editor, might not be available for all editors, inconsistent)
- explicit annotations for editors like `vim:set ft=toml:` (-> same as above, but _also_ editor specific)
- manually setting filetype every time I open the file (-> annoying)

## Additional context
--

**Comment by halostatue** [comment]
This isn't a bad idea, but it would be more likely to treat `tmpl` as a chezmoi attribute (`private_dot_ssh/private_tmpl_config`) than as something separated by dots, and I think it would be more likely to show up in preparation for the eventual chezmoi v3 than anything else.

Either way, it won't help with editor pattern matches that look *specifically* for certain filenames (`~/.ssh/config` is treated specially by most editors because of its full path name as there is no extension), and it would require the various editor plug-ins be updated to recognize this alternative approach.

**Comment by twpayne** [comment]
> Having `.tmpl` be the file extension for templates means that now editors don't detect the filetype properly. If `tmpl` was a prefix, this would not be an issue.

This is not correct. The filetype of a template is a Go template, and chezmoi's templates correctly have the `.tmpl` extension to indicate this to the editor so the editor can syntax highlight it correctly. The result of executing the template could be a bash script, TOML file, SSH config file, or whatever, but the template itself is a template, not a bash script, TOML file, or whatever.

Furthermore, adding `tmpl_` attribute would be break the 1:1 mapping between source names and target names.

So, this will not be implemented.
