### ISSUE TITLE
Question: sensitive data written on disk?

### ISSUE THREAD

**Issue by pawamoy** [twpayne/chezmoi#410]
If I understand correctly, `chezmoi` will render templates containing secrets and write them in the home directory. It means that even after removal, traces (if not the entirety) of these secrets can still be found on the disk, for example by searching for deleted files with special software. Am I right? If yes, do you plan to implement an "erase" or "wipe" mechanism for sensitive data?

**Comment by twpayne** [comment]
Yes, you're right, but there's not much chezmoi can do about this. "Erase" or "wipe" mechanisms do not help as at best they can only erase the secret where it is currently stored. Other copies of the secret might be present on the disk if the operating system has for, example, stored the file in different locations at different times. You should assume that any secret written to disk in plaintext is accessible to at least anyone with root access to that machine.

chezmoi helps because it only stores the secrets that must be present on the machine in plaintext on the machine. All other secrets are either stored in a (presumably secure) password manager or encrypted.

**Comment by pawamoy** [comment]
Of course we cannot expect `chezmoi` to take care of everything. But if I make sure I never write anything sensitive on the disk I'd like `chezmoi` to be able to follow the same rule!

Anyway, I guess I'll keep searching for a solution allowing to transparently decrypt files in RAM :)

Thanks for your answer!
