### ISSUE TITLE
`--follow` flag for `chezmoi apply`

### ISSUE THREAD

**Issue by leonfeng** [twpayne/chezmoi#4102]
## Is your feature request related to a problem? Please describe.

I use WSL on Windows 11. The vast majority of my dotfiles sit in my Linux home folder. However, there are a few Windows config files that I'd like Chezmoi to manage. 

So far, I have symlinked to and `chezmoi add --follow`ed these Windows config files. But when `apply`ing, Chezmoi overwrites the Linux symlinks instead of following them.

## Describe the solution you'd like

A `--follow` flag will allow `chezmoi apply` to selectively overwrite the target files of the symlinks and not the symlinks themselves.

## Describe alternatives you've considered

- Hardlinking doesn't work across file systems.
- `chezmoi add` requires the files to be in my Linux home folder so I can't add the Windows config files directly.
- Chezmoi's symlink mode isn't what I want, since most of my dotfiles are regular files.

## Additional context

Right now I'm copying these config files between Windows and Linux each time there's a change, and it gets old very quickly. Thank you for reading my feature request!

**Comment by KapJI** [comment]
You should be able to manage Windows configs with `.chezmoiignore` and templates, there is no need for symlinks.

**Comment by halostatue** [comment]
I believe that what @leonfeng is looking for is running `chezmoi` *once* from their WSL instance where they have placed symlinks of Windows configuration files somewhere in that instance.

I don't see this being implemented because this makes `chezmoi apply` even less predictable in behaviour:

- if you forget to specify `--follow`, any symlinks will be removed and the files will be written instead.
- if you do not have the symlinks, the files will be written.
- if you have *other* symlinks, the files will be overwritten.

Additionally, on Windows/WSL you have the fact that Windows files use CRLF newlines and Linux — even under WSL — uses LF newlines.

**Comment by twpayne** [comment]
> Right now I'm copying these config files between Windows and Linux each time there's a change, and it gets old very quickly. Thank you for reading my feature request!

The point of chezmoi is to **generate** the right set of dotfiles for the machine that you're using. By using symbolic links between your Windows and Linux dotfiles, you're trying to **share** dotfiles between machines. For the reasons that @halostatue gives, you're going to run into problems.

The solution is to stop sharing dotfiles via symlinks and instead put them in your dotfiles repo so chezmoi can generate them exactly for your Linux and Windows machines.
