### ISSUE TITLE
Shell history sync

### ISSUE THREAD

**Issue by thernstig** [twpayne/chezmoi#4147]
## Is your feature request related to a problem? Please describe.
I am currently using https://github.com/atuinsh/atuin to sync my shell history between machines. I wish to use one tool for all my machine syncing instead of having to rely on two.

It is frustrating having to use more than one tool for all syncing needs. Especially if you also account for devcontainers and similar.

## Describe the solution you'd like

- A functionality similar to atuin, see https://github.com/atuinsh/atuin.
- It should work across shells. sh, bash, fish, zsh, eleven, csh, tcsh, etc.
- Searching the command history (`ctrl+r`) should have a default fuzzy finder, but allow to hook in any of them such as https://github.com/junegunn/fzf.

## Describe alternatives you've considered

The Unix philosophy of _"Make each program do one thing well"_ could be interpreted in two ways. Either that having both chezmoi and atuin does this, but I feel that since chezmoi already does so much and the goal is to sync machines, implementing this into chezmoi could be good.

## Additional context

This feature would/should use live sync like atuin does, so that one does not have to do a `chezmoi update` each time you move between machines. The power of this is that if you work on a stationary computer often (due to its power) but have a laptop that you take "on the go" when leaving the house, you can leave where you left of immediately without any manual syncs.

**Comment by halostatue** [comment]
Short version: this is exceedingly unlikely to be considered as it veers *well* outside of chezmoi's lane and wants a centralized server. Do not expect this to happen.

> …since chezmoi already does so much and the goal is to sync machines, implementing [shell history sync] into chezmoi could be good.

This is a fundamental misunderstanding of chezmoi. The goal is *not* to sync machines, but to manage one's personal configuration home environment configuration. I used chezmoi for the first several years on a single machine because it provided me with a reproducible configuration and backup mechanism that was far simpler (but not simple) than what I had written myself for a decade.

In fact, now that I’m working on multiple machines, I am deliberately *not* replicating fairly large portions of my configuration between the personal and work machines.

> ## Additional context
> This feature would/should use live sync like atuin does, so that one does not have to do a `chezmoi update` each time you move between machines. The power of this is that if you work on a stationary computer often (due to its power) but have a laptop that you take "on the go" when leaving the house, you can leave where you left of immediately without any manual syncs.

Atuin is a complex beast that must interact with each shell to capture history correctly and store its data, and then it has a CRDT mechanism which it uses to privately communicate that data with a server running custom (atuin) software. Ellie Huxtable runs the standard atuin server for the community's benefit at her own cost (most of the cost may be paid by her sponsors, but there aren't that many). Chezmoi is intended to run comparatively infrequently (every few hours, not *every single command*) and has no server component.

chezmoi is amazing software, but if we were to take this on, we would not be able to do half as good a job as mcfly or atuin even *without* syncing and the quality of chezmoi for its primary purpose would suffer.

**Comment by twpayne** [comment]
As @halostatue says, this is the realm of [atuin](https://atuin.sh/), which you already use.

chezmoi stores all its shared state in a git repo, and a git repo is not suitable for storing state changes that occur every time you type a line of shell.

See previous discussions in https://github.com/twpayne/chezmoi/discussions/2313 and https://github.com/twpayne/chezmoi/discussions/3515.

You can use chezmoi to set up atuin across all of your machines.

So, cross-machine shell-history syncing will not be added to chezmoi.

**Comment by thernstig** [comment]
Fair points, I understand the dilema of implementing something like this.

> This is a fundamental misunderstanding of chezmo

The docs mentions "multiple machines" in almost every documentation, so even though your use case of using it for one machien is also sound and good, I am not sure I would consider this a _fundamental misunderstanding_ at all.

**Comment by halostatue** [comment]
> Fair points, I understand the dilema of implementing something like this.
> 
> > This is a fundamental misunderstanding of chezmoi
> 
> The docs mentions "multiple machines" in almost every documentation, so even though your use case of using it for one machien is also sound and good, I am not sure I would consider this a _fundamental misunderstanding_ at all.

The fundamental misunderstanding is not that chezmoi can be used for multiple machines, but that chezmoi is a syncing system. If chezmoi only synced, it would have very little utility. The strength of chezmoi is that it can be configured to make decisions based on configuration, operating system, etc. to configure two different machines *differently* from similar original data.

Chezmoi is definitely built to be used on multiple machines — but it isn't a sync engine by any definition.
