### ISSUE TITLE
Remove  non-git VCS support

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#459]
chezmoi currently includes support for plugging in your own VCS through the `sourceVCS.command` configuration value. However, this is hard to maintain without expert support for non-`git` version control systems as chezmoi moves towards closer integration with the underlying VCS, for example as required to implement #413.

This issue is a concrete proposal to remove non-git support from chezmoi. Doing so would simplify the implementation (e.g remove the [`VCS interface`](https://github.com/twpayne/chezmoi/blob/master/cmd/vcs.go)) and allow chezmoi to provide a consistent set of features to all users.

cc @mgeisler who might have a different perspective.

**Comment by mgeisler** [comment]
Hey Tom, thanks for mentioning me :-)

My first reaction when reading that chezmoi can use other tools was that chezmoi must be a very well-designed and flexible tool. Clearly, thought was put into making this more than a thin hack on top of Git, which is very encouraging to me as a user. Unix philosophy and all that...

Put differently, I felt it somehow showed "good taste" by the project, similarly to how I like to see projects releasing their software for multiple distributions instead of just focusing on, say, Ubuntu. I can probably get an Ubuntu package working on my system, but if I see that the project already tackles this problem, well then I trust them much more.

However, supporting only a single VCS will of course allow for deeper integration, so this is a trade off — as with everything in engineering.

Personally, I don't use `chezmoi update` at all. I much prefer to do this myself since it's more familiar to me to push/pull using my usual Git workflow. I'm sure people using Mercurial and similar would find it quite easy to go to the source directory and push/pull from there.

**Comment by 3v1n0** [comment]
As per this, could may be revised the choice of using `<prefix>_` to handle the file permissions and the dot itself?

I find it creates a quite cluttered and harder to read three, while I assume that using git it can manage the file permissions natively. 

The only cases it would still make sense would probably be for the encrypted and templated symlinks, no?

**Comment by twpayne** [comment]
Thanks for the suggestion @3v1n0 :)

I just added an FAQ entry for this in #776 [here](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md#can-i-change-how-chezmois-source-state-is-represented-on-disk) which hopefully answers your questions.
