### ISSUE TITLE
Support for running a script based on changes to another file

### ISSUE THREAD

**Issue by karlwbrown** [twpayne/chezmoi#468]
I'm wondering if you've considered enhancing the run_once vs run_ scripts semantics.

I'd like to use brew bundler, which has a "Brewfile" for which the `brew bundle` command should be run if it changes, but there is no way today to tell chezmoi to run that command based on some other file changing. Do you have any suggestions on how to make this work (besides just running the script every time)?

**Comment by twpayne** [comment]
This is indeed a tricky problem. Running commands when files change is typically the job of a build system like make or Bazel, and it quickly becomes very complex.

Have a look at issue #401, and I'll also add an entry to the FAQ.

**Comment by erdii** [comment]
FWIW i just discovered that a `run_once_*.tmpl` script is re-executed when the **templated** content changes.
This means, that you can rerun a script when another file changes as long as you include that file in your templated script.

Thus you can do something like:

`.chezmoiignore`:
```
ignored_files/
```

`ignored_files/Brewfile`:
```
# Brewfile
brew "openssl"
# a comment
tap "homebrew/dupes"
```

`run_once_apply_brewfile.sh.tmpl`
```bash
#!/bin/sh

# include the hash of the file we want to 'watch' so that this script is re-executed when the referenced file changes
# hash: {{ include "ignored_files/Brewfile" | sha256sum }}

brew bundle --file "$(chezmoi source-path)/ignored_files/Brewfile"
```

Disclaimer: I didn't do it with brew but with `dconf dump/load` and the script here is not tested - i just wrote them for the sake of demonstration

This is the script i use:

```bash
#!/bin/sh

{{ $dconfIniRelPath := "ignored_files/dconf.ini" }}

# this script is re-executed every time it's content changes (after templating)

echo "loading changed dconf/gnome settings"
echo "hash: {{ include $dconfIniRelPath | sha256sum }}"

dconf load / < "$(chezmoi source-path)/{{ $dconfIniRelPath }}"
```

**Comment by twpayne** [comment]
That's a really neat solution @erdii, thank you!

I'll re-open this issue as a reminder to add this to the FAQ.

**Comment by flyxi121** [comment]
There is one small problem with only including the hashed file contents. Chezmoi will run the `run_once` script for every possible hash of the file, that means that it will not run the script again when you ever revert the contents, because hashing the file will result in an already known hash.
One possible approach to avoid this problem is to not include the hashed contents of the file in the template but its last modified date with for example `stat --format=%Y`.

**Comment by twpayne** [comment]
> There is one small problem with only including the hashed file contents. Chezmoi will run the `run_once` script for every possible hash of the file, that means that it will not run the script again when you ever revert the contents, because hashing the file will result in an already known hash.

Good point! I think this is a bug in chezmoi: chezmoi should run `run_once_` scripts when their contents have changed since the last time that chezmoi ran the script. Would you mind [opening a new bug](https://github.com/twpayne/chezmoi/issues/new?assignees=&labels=&template=03_bug_report.md&title=) for this, as this comment on a closed issue is easily lost.
