### ISSUE TITLE
Unsupported Filetype with oh-my-zsh

### ISSUE THREAD

**Issue by Jesse-Millwood** [twpayne/chezmoi#479]
#### Description of issue

I have added oh-my-zsh as a submodule by
```
/opt/chezmoi/chezmoi cd
git submodule add https://github.com/robbyrussell/oh-my-zsh dot_oh-my-zsh
git commit -m "Added oh my zsh"
/opt/chezmoi/chezmoi apply
```
After this a file is flagged as unsupported. 

I know oh-my-zsh is specifically given as an example with the `import` command but I wanted to use it as a submodule to ease initializing and syncing. 

I tried adding that file to my `.chezmoiignore` too and that didn't seem to help

Great tool though, handles just about everything I have wanted so far. 

#### Command that failed

```
boxtoo% /opt/chezmoi/chezmoi apply
chezmoi: /home/jesse/.local/share/chezmoi/dot_oh-my-zsh/plugins/fedora/fedora.plugin.zsh: unsupported file type
```

#### Output of command with `--verbose`

```
boxtoo% /opt/chezmoi/chezmoi apply --verbose
chezmoi: /home/jesse/.local/share/chezmoi/dot_oh-my-zsh/plugins/fedora/fedora.plugin.zsh: unsupported file type
```

#### Output of `chezmoi doctor`

```
boxtoo% /opt/chezmoi/chezmoi doctor
     ok: version 1.7.2, commit 41c4fdc2faf1bf9f0ded922d1ea7724a838bca3f, built at 2019-10-17T00:29:01Z
     ok: /home/jesse/.local/share/chezmoi (source directory, perm 700)
     ok: /home/jesse (destination directory, perm 755)
warning: /home/jesse/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/zsh (shell)
     ok: /usr/bin/emacs (editor)
warning: vimdiff (merge command, not found)
     ok: /usr/bin/git (source VCS command, version 2.24.0)
     ok: /usr/bin/gpg (GnuPG, version 2.2.17)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
     ok: /usr/bin/keepassxc-cli (KeePassXC CLI, version 2.5.0)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

#### Output of `chezmoi --version`

```
boxtoo% /opt/chezmoi/chezmoi --version
chezmoi version 1.7.2, commit 41c4fdc2faf1bf9f0ded922d1ea7724a838bca3f, built at 2019-10-17T00:29:01Z
```

**Comment by Jesse-Millwood** [comment]
I looked at the file type and it looks like it is a symbolic link: 
```
file dot_oh-my-zsh/plugins/fedora/fedora.plugin.zsh                   
dot_oh-my-zsh/plugins/fedora/fedora.plugin.zsh: symbolic link to ../dnf/dnf.plugin.zsh
```

Is this an issue and why it was suggested to use the import archive command? 
Are symlinks not allowed in directories in the source state?

**Comment by twpayne** [comment]
chezmoi supports symbolic links, but they're not stored as symbolic links in the source state. Instead, they're stored as regular files with the `symlink_` prefix. Consequently, including oh-my-zsh as a submodule in the source state does not work because the submodule is not in chezmoi's format.

You can import a snapshot of oh-my-zsh with these commands:

    curl -s -L -o oh-my-zsh-master.tar.gz https://github.com/robbyrussell/oh-my-zsh/archive/master.tar.gz
    chezmoi import --strip-components 1 --destination ${HOME}/.oh-my-zsh oh-my-zsh-master.tar.gz

Be sure to add `oh-my-zsh-master.tar.gz` to `.chezmoiignore` if you run these commands in your source directory so that chezmoi doesn't try to copy the tarball anywhere. Also, disable oh-my-zsh auto-updates by setting `DISABLE_AUTO_UPDATE="true"` in your `~/.zshrc` as oh-my-zsh's updates cause your `~/.oh-my-zsh` directory to drift out of sync with chezmoi's source state.

I have a [`Makefile` in my source directory](https://github.com/twpayne/dotfiles/blob/master/Makefile#L87-L89) with targets to update oh-my-zsh and other third party code that I pull into my dotfiles.

Hope this helps!

**Comment by Jesse-Millwood** [comment]
@twpayne thank you so much. It was actually very informative to look at your source directory. I guess I was thinking that I'd have to run the import on all of my machines. Your source directory also cleared up a few other small things I was wondering about.
