### ISSUE TITLE
broken links on https://www.chezmoi.io/ page

### ISSUE THREAD

**Issue by pwright** [twpayne/chezmoi#483]
#### Troubleshooting
- [x] I ran `chezmoi doctor` and fixed as many issues as possible and retried my command.
- [x] I have double checked the instructions for [Installation](https://github.com/twpayne/chezmoi/blob/master/docs/INSTALL.md) and the [Quickstart Guide](https://github.com/twpayne/chezmoi/blob/master/docs/QUICKSTART.md).
- [x] I have search for previous issues that have been reported/opened, and none of them relate to my problem.

Failure to follow the troubleshooting steps (and to report information requested below), may make it difficult to provide the proper support required. Furthermore, your issue may be closed without reply, if the instructions were not properly followed.

---

#### Description of issue

A lot of links in the "How do I start with chezmoi?" section are broken.
Altho I had no problem finding the 'proper' files in the github repo

#### Command that failed

```
{{replace this}}
```

#### Output of command with `--verbose`

```
{{replace this}}
```

#### Output of `chezmoi doctor`

```
{{replace this}}
```

#### Output of `chezmoi --version`

```
{{replace this}}
```

**Comment by twpayne** [comment]
Thanks very much for reporting the bug. I think this is because of an incompatibility between the way that anchors are generated from Markdown between the GitHub-flavored Markdown used in the docs and the HTML generated from it by Hugo, the static site generator that generates chezmoi.io. I will do some further investigation and come up with a fix.
