### ISSUE TITLE
Wish: Add file fetching support from password managers

### ISSUE THREAD

**Issue by rcorrear** [twpayne/chezmoi#501]
Hi,

For background, the way I deal with SSH key pairs is by keeping them in 1Password, mainly because in 1Password adding data with newlines is not possible in regular item fields, so
I'd like to have a way to retrieve files from 1Password without parsing them (`op get document id` instead of `op get item id`).

I've done some prototyping in code as to how this could work so I came up with a `file` template function which can be parameterized with the password manager you use, since I noticed at least Bitwarden supports this, so in the end it looks like `file onepassword id` in the templates.

I'm wondering if you have plans for this already and if you don't if this is something you'd like to integrate.

BTW, I tried adding this `file` function as a parameter of the already existing `onepassword` function but noticed it might have a significant impact to the codebase (might be that my Go skills are non-existant) if it's even possible.

**Comment by twpayne** [comment]
Thanks for the suggestion - this is a good idea that I'd like to add.

Rather than making the password manager a parameter to the `file` function, I'd make separate functions for retrieving files from each password manager, as this keeps everything more separated. It also allows the password manager template functions to better reflect the vocabulary of the specific password managers, rather than enforcing a single unified vocabulary. This helps users as typically they will one have one password manager that they use and are familiar with.

In this case, I think there should be `openpasswordDocument` function that calls `op get document id`.

I should be able to implement this quite quickly now.

**Comment by twpayne** [comment]
OK, this is now in and I've tagged version 1.7.5. It should take about 30 minutes for the release process to run and upload new packages.
