### ISSUE TITLE
Emptying out a file with chezmoi edit leaves file in source state

### ISSUE THREAD

**Issue by Rubonnek** [twpayne/chezmoi#530]
**Describe the bug**
Say `myfile.config` was already populated, added to the source directory and applied to the target state. Then user empties out `myfile.config` on the source state using `chezmoi edit`. Then `chezmoi apply` 

**To reproduce**
````shell
touch "$(chezmoi source-path)/myfile.config"
touch $HOME/myfile.config
chezmoi apply # removes myfile.config on the target state but not on the source state
ls "$(chezmoi source-path)/myfile.config" # file still exists
````

**Expected behavior**
Since the source state of `myfile.config` was empty and it does not have an `empty_` prefix, I expected `chezmoi apply` to also remove the file at the source.

Perhaps `chezmoi edit` should check if the source state is an empty file when the editor subprocess finishes and then simply show the same prompt `chezmoi rm` shows for removing files.

**Output of command with `--verbose` and `--debug`**
````shell
$ chezmoi apply --verbose --debug 
rm -rf /home/wilson/myfile.config
````

**Output of `chezmoi doctor`**
```
$ chezmoi doctor
warning: version 1.7.9
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/wilson/.local/share/chezmoi (source directory, perm 700)
     ok: /home/wilson (destination directory, perm 710)
     ok: /home/wilson/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/zsh (shell)
     ok: /usr/bin/vim (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.24.1)
     ok: /usr/bin/gpg (GnuPG, version 2.2.19)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: /usr/bin/gopass (gopass CLI)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
     ok: /usr/bin/pass (pass CLI, version 1.7.3)
     ok: /usr/bin/vault (Vault CLI, version 1.2.0)
```

**Comment by twpayne** [comment]
Thank you very much for your thorough testing of chezmoi!

This is an interesting case.

Note that, by default, `chezmoi edit` does not apply the changes made in the edit. You need to explicitly pass the `--apply` flag if you want the changes to be applied after editing.

An empty file in the source state without an `empty_` prefix has a valid use case: telling chezmoi that it should remove the file in the target state. Removing the empty file from the source state would instead cause chezmoi to ignore the file completely.

Currently `chezmoi apply` only reads the source state. I think having `apply` modify the source state in some cases (e.g. by deleting empty files) would be confusing.

My gut feel is that chezmoi's current behavior is reasonable. Specifically, if you `chezmoi edit` a config file so that it becomes empty in the source state, subsequent calls to `chezmoi apply` will remove the config file from the target state.

Does this seem reasonable?

**Comment by Rubonnek** [comment]
You are welcome!

At first I thought this behavior was simply duplicating what `.chezmoiremove` stood for, but that doesn't seem to be the case.

I agree, the behavior does seem reasonable now.

However, from my perspective this issue prompts for a new `remove_` source state attribute that simply makes it clear to the user that if this file is found on the target directory it will be removed on a subsequent call to `chezmoi apply`.

This way when the user does `chezmoi cd` it will be obvious which files will be removed just by looking at the prefix.

Does this seem reasonable to you?

**Comment by twpayne** [comment]
Yes, this seems reasonable. At the same time a `remove_` prefix is also a repetition of information. An empty file called `foo` in the source state will cause chezmoi to remove `foo` in the target state. Adding a `remove_` prefix certainly makes the source state easier to read, but is a duplication of information: `foo` being empty already indicates "remove", and any `remove_` prefix does not add anything.

One possibility would be to automatically add a `remove_` prefix to all empty files in the source state, and signal errors if there is an empty file in the source state without a `remove_` prefix. Without the error signaling, any `remove_` prefix is purely optional and adds nothing. There also needs to be a migration path here, for people who've already added empty files to indicate removal. There's also an orthogonality case to consider where the source file is a template: what's the difference between `foo.tmpl`, `empty_foo.tmpl`, `remove_foo.tmpl`, and `remove_empty_foo.tmpl`?

Thank you again for this discussion - you're raising really interesting cases :)
