### ISSUE TITLE
Possible to ignore file extension in all sub-directories?

### ISSUE THREAD

**Issue by jlucktay** [twpayne/chezmoi#621]
## What exactly are you trying to do?

Trying to ignore some text files under a directory and all of its children sub-directories.

## What have you tried so far?

In one of my `.chezmoiignore` files, I have tried setting a line as `*/*.txt` and `**/*.txt` but it still shows text files from sub-directories in `chezmoi diff` and `chezmoi apply --dry-run --verbose`.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
  * the FAQ [explicitly states](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md#if-theres-a-mechanism-in-place-for-the-above-is-there-also-a-way-to-tell-chezmoi-to-ignore-specific-files-or-groups-of-files-eg-by-directory-name-or-by-glob) that this is possible
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
  * the reference has [a note](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#chezmoiignore) that it will be "interpreted as a list of globs to ignore" but maybe I'm doing the syntax wrong
* [x] Other, please give details.
  * had a quick browse through the code using GitHub search but couldn't find much without a proper deep dive in an IDE

## Output of any commands you've tried with `--verbose`

```
$ chezmoi apply --dry-run --verbose
<contents of various text files>
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor 
     ok: version 1.7.15, commit a7b560750eb7002286515d494c5d6592e0c053da, built at 2020-02-26T08:00:13Z
     ok: runtime.GOOS darwin, runtime.GOARCH amd64
     ok: /Users/jameslucktaylor/.local/share/chezmoi (source directory, perm 700)
     ok: /Users/jameslucktaylor (destination directory, perm 755)
     ok: /Users/jameslucktaylor/.config/chezmoi/chezmoi.json (configuration file)
     ok: /usr/local/bin/bash (shell)
     ok: /usr/local/bin/nano (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/local/bin/git (source VCS command, version 2.25.0)
     ok: /usr/local/bin/gpg (GnuPG, version 2.2.17)
     ok: /usr/local/bin/op (1Password CLI, version 0.7.1)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

## Additional context

The ignore syntax doesn't have a lot of documentation, so some examples of globs in action would really help.
Also, thank you for `chezmoi`! I just finished migrating from my previous dotfiles manager as this is much more featureful and powerful.

**Comment by twpayne** [comment]
Thank you for the clear and comprehensive request, and for your kind words :)

chezmoi's ignore file uses [`filepath.Match`](https://pkg.go.dev/path/filepath?tab=doc#Match) from the Go standard library under the hood (chezmoi's use of this can be found in [`patternset.go`](https://github.com/twpayne/chezmoi/blob/master/internal/chezmoi/patternset.go)). As far as I can tell, `filepath.Match` doesn't support arbitrary depth directories (e.g. it doesn't support `**` as a wildcard).

As a workaround, you should be able to explicitly specify ignores at multiple depths, e.g.:

```
*.txt
*/*.txt
*/*/*.txt
*/*/*/*.txt
# ...and as many more as needed
```

This is very ugly - sorry - but should work and allows chezmoi to continue to use the Go standard library function and won't break any existing `.chezmoiignore` files. I'll improve chezmoi's documentation around ignore files.

If this is acceptable to you, please close this issue, otherwise we can discuss more options :)

**Comment by jlucktay** [comment]
I tried the approach with
```
*.txt
*/*.txt
*/*/*.txt
# etc
```
but `chezmoi apply` still wanted to create the empty directories without any text files inside.
I will leave it with the text files under their own directory and just keep that directory in `.chezmoiignore`; it's cleaner that way.
Thanks for your help and for the links and doc updates! 👍
