### ISSUE TITLE
Conditionally render parts of a template based on key existence

### ISSUE THREAD

**Issue by remi-gelinas** [twpayne/chezmoi#628]
## What exactly are you trying to do?
I'm trying to build portions of templates to conditionally render based on data included in `.data`.

## What have you tried so far?
I've consulted the official Golang template docs, and so far I've tried several ways of determining nested key existence, primarily:

```
{{ if .object.nested.field }}
{{  .object.nested.field }}
{{ end }}

{{ if and .object.nested .object.nested.field }}
{{ .object.nested.field }}
{{ end }}

{{ if .object.nested }}
{{ if .object.nested.field }}
{{ .object.nested.field }}
{{ end }}
{{ end }}
```

In each instance of the above, the conditional should be determining whether the arg is nil (non-existence should be evaluating as nil) and rendering its output appropriately - instead, Chezmoi panics and exits due to `nested` not being a key in `object`.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to
  guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not
  found the answer.
* [x] I have read [chezmoi's
  FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not
  found the answer.
* [x] I have searched [chezmoi's reference
  guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and
  not found the answer.
* [x] Searched [Golang's official template docs](https://golang.org/pkg/text/template/) and found no concrete examples of determining the existence of a key or conditionally rendering

## Additional context

@twpayne Is this a use case that you've run into before, and if so, is there a recommended way of conditionally rendering parts of templates cleanly?

**Comment by twpayne** [comment]
Thank you for your precise and comprehensive statement of the problem :)

There are a few possibilities here. Please note that I haven't tried these exactly, so I might not have got these quite right, but the principles should work.

1. You can use `text/template`'s `index` function to look up a key in a dictionary. It will return an untyped `nil` if the key does not exist. Importantly, `index` looks up the key dynamically, rather than statically, so does not trigger template execution errors. You should be able to do:

    {{ if (and (index .object "nested") (index .object "nested" "field")) }}
    {{ index .object "nested" "field" }}
    {{ end }}

2. chezmoi includes all of the hermetic `Masterminds/sprig` template functions, including `hasKey` that works on dicts. See http://masterminds.github.io/sprig/dicts.html for documentation. This might be another avenue to explore.

3. chezmoi currently uses the `text/template` option `missingkey=error` which was added to help users find errors in templates early. However, this might be a bit strict, especially for cases where the structure of the template data varies.

I've added an `execute-template` command in #629 which should make it easier to experiment with chezmoi's template execuion.

I'm not sure exactly what the right approach is here. What are your thoughts?

**Comment by remi-gelinas** [comment]
Thanks for the quick response! Both `hasKey` and `index` work (I'll be using `hasKey` for the time being, as it's ever so slightly cleaner).

As for #3, I think it's an interesting problem. There will be cases where users will want Chezmoi to fail at execution time if data required for the template is not present, if they would rather that data be required for initialization. In that case, we can manage required/optional data with normal templating and use of `hasKey`.

It could be worth introducing a configuration option to change the `missingkey` response, as I can see the value in failing on execution if a user requires certain data - but I can also see liberal use of `hasKey` getting extremely verbose and hard to maintain as `.data` gets more and more complex and nested.

What do you think?

**Comment by remi-gelinas** [comment]
@twpayne After further testing, `hasKey` still throws an error if the key does not exist, however it correctly looks them up if they do.

Using `index` results in an error (`error calling index: index of nil pointer`) at the second expression in your example, and fails at execution time regardless (instead of allowing the conditional to fail silently)

**Comment by twpayne** [comment]
Ah. Thank you for testing and reporting this.

The errors occur because chezmoi uses the `missingkey=error` option when executing templates. See the [`text/template.Template.Option` documentation`](https://pkg.go.dev/text/template?tab=doc#Template.Option).

#630 adds an option to override this option (e.g. with `missingkey=zero` or `missingkey=invalid`). For example, if you're using TOML for your config file, you can include:

```toml
[template]
  options = ["missingkey=zero"]
```

Note that `options` is an array of strings.

This should allow you to persuade chezmoi to stop complaining :)

**Comment by twpayne** [comment]
I realize that you might have quite a lot going on right now :)

Please re-open this bug if the above is a sufficient fix for you.

**Comment by remi-gelinas** [comment]
That fix should make it easy for me, thanks! I’ll re-open it if it’s still an issue.
