### ISSUE TITLE
Get Chezmoi data from current environment variables

### ISSUE THREAD

**Issue by ihommani** [twpayne/chezmoi#655]
## Is your feature request related to a problem? Please describe.

As I run chezmoi inside containerized dev environment, my control over the environment variable is complete. 
Template currently watch data values from the one defined in .config/chezmoi/chezmoi.toml. 

## Describe the solution you'd like
I would like `Chezmoi  apply` to expose a new flag to override or mix data values from the defined environement variables. By defaul it would be the value from the chezmoi config file. 

## Describe alternatives you've considered

Stick to the config file.

## Additional context

Developement inside a container is eased by the VSCode remote -containers extension. 
https://code.visualstudio.com/docs/remote/containers
It would be neat to not have to create chezmoi.toml file to set template values and just rely on what is defined as env variables in the docker-compose.yml file. 
@twpayne , what do you think? I a willing to implement it once we agree on something.

**Comment by twpayne** [comment]
This will make templates non-hermetic, but there're non-hermetic anyway because all the password manager-related functions are non-hermetic.

We can include the non-hermetic functions from [Sprig](http://masterminds.github.io/sprig/), including [`env` and `expandenv`](http://masterminds.github.io/sprig/os.html) which I think meet your requirements. chezmoi already includes all hermetic functions from Sprig.

How does this sound?

**Comment by twpayne** [comment]
Note that default handling can be done in the template using [Sprig's default functions](http://masterminds.github.io/sprig/defaults.html).
