### ISSUE TITLE
Run script as admin

### ISSUE THREAD

**Issue by mniak** [twpayne/chezmoi#661]
Before anything, I found this tool two days ago and I'm already addicted. Very good and full of features.

## Is your feature request related to a problem? Please describe.

Yes, I'm trying to use some `run_` scripts to set some windows registry settings.
But in order to write some registry entries I need elevated privileges

## Describe the solution you'd like

I thought of adding a `admin_`/`su_` prefix for script files, so it would ask for admin credentials or confirmation and then run the script with elevated privileges.
It also should ask only once per _apply_.

## Describe alternatives you've considered

Well, I'm currently checking if the user is admin and if not recalling the same script with elevated privileges, but is is very non-elegant.
```
#Check if is admin
net session >nul 2>&1
if %errorLevel% == 0 (
	goto :ADMIN	
) else (
	goto :ELEVATE
)

:ELEVATE
REM Recurse as admin
PowerShell start -verb runas -wait %~0
GOTO :END

:ADMIN
echo I AM ADMIN!

:END
```

## Additional context
nothing

**Comment by mniak** [comment]
Now I see that this should be a _feature_ request instead of _enhancement_.

**Comment by twpayne** [comment]
Thank you for the kind words about chezmoi, I'm happy that it's useful for you :)

chezmoi allows you to include re-usable templates, for example if you create a file in a `.chezmoitemplates` subdirectory in your source directory then you can reuse it in templates elsewhere, for example:

`.chezmoitemplates/run_as_admin`:
```bat
#Check if is admin
net session >nul 2>&1
if %errorLevel% == 0 (
	goto :ADMIN	
) else (
	goto :ELEVATE
)

:ELEVATE
REM Recurse as admin
PowerShell start -verb runas -wait %~0
GOTO :END

:ADMIN
echo I AM ADMIN!

:END
```

You can then use this in your scripts, for example:

`run_my_thing.bat.tmpl`:
```
{{ template "run_as_admin" }}

# run my thing as admin
```

I don't have a Windows machine to test this on, but the above should be roughly correct.

I'm a little hesitant to add an `su_` prefix or similar to scripts because the way that people get admin privileges varies a lot (it could be `PowerShell start -verb runas -wait` or `sudo` or `su` or something else) and it's probably hard to detect the correct method reliably. Given that the same can be achieved inside the script itself, I would rather hold off adding such a feature until it is well understood.

I know that the template suggestion isn't quite what you asked for, but maybe it's enough for now?

**Comment by twpayne** [comment]
Just looking at your scripts in https://github.com/mniak/dotfiles/blob/master/_scripts/windows/run_registry-machine.cmd I see that the template I've suggested isn't quite right, but I think it should still be possible to do this with a template.

**Comment by mniak** [comment]
Well, it certainly would make my scripts look less ugly.

**Comment by felipecassiors** [comment]
This is the Powershell version:

```powershell
# Self-elevate the script if required
if (-Not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] 'Administrator')) {
  if ([int](Get-CimInstance -Class Win32_OperatingSystem | Select-Object -ExpandProperty BuildNumber) -ge 6000) {
    $CommandLine = "-NoExit -File `"" + $MyInvocation.MyCommand.Path + "`" " + $MyInvocation.UnboundArguments
    Start-Process -FilePath PowerShell.exe -Verb Runas -ArgumentList $CommandLine
    Exit
  }
}
```
https://github.com/felipecassiors/dotfiles/blob/windows/scripts/setup-everything-windows.ps1#L3-L10

Also, take a look at the awesome [gsudo](https://github.com/gerardog/gsudo).
