### ISSUE TITLE
Running chezmoi upgrade with a compiled binary downgrades to latest release

### ISSUE THREAD

**Issue by sandorex** [twpayne/chezmoi#705]
## Describe the bug

Running `chezmoi upgrade` with a latest dev version downgrades it to `1.8.0` without any warning

## To reproduce

Steps to reproduce the behavior.

1. Have `dev` version installed
2. Run `chezmoi upgrade`

## Expected behavior

It should rebuild dev version from master

**Comment by twpayne** [comment]
Thanks for reporting!

This is definitely a bug. I think the current behavior comes from me testing `chezmoi upgrade` and is not correct for general use.

Rebuilding the dev version from master is hard goal to achieve. chezmoi cannot reasonably know which directory it was built in, with what command exactly, whether the local working copy has modifications, and so on.

I think that `chezmoi upgrade`, when run on a `dev` version should simply refuse to upgrade.

Does this sound reasonable?

**Comment by sandorex** [comment]
I was thinking of it doing something like this
```
cd $(mktemp -d)
git clone --depth=1 https://github.com/twpayne/chezmoi.git
cd chezmoi
go install
```
but that may not work for everyone, maybe ask to build it ? a flag like `chezmoi upgrade --git` ?

**Comment by twpayne** [comment]
Ah, that makes sense. I think we can condense this to:

    go get -u github.com/twpayne/chezmoi

but I need to double check that this works.

**Comment by sandorex** [comment]
Would making the CI build every commit possible?

**Comment by twpayne** [comment]
Yes, it would be possible to build a release binary on every commit, but I am hesitant to do this for several reasons:

* Although chezmoi has a reasonable test suite, bugs and oversights do creep in to master from time to time. I don't want to encourage people to run bleeding-edge chezmoi because occasionally things do break. I consider the barrier to entry to running master as safety feature for chezmoi's users.
* The support load is significantly increased if you have to reason about chezmoi's behavior at every individual commit rather than occasional tagged versions.
* I think chezmoi is already reasonably fast releasing versions. The current cadence is about every two weeks when things are changing quickly. Although nice features are being continuously added and bugs are being squashed (many thanks to you for reporting all that you find - I really appreciate it and it really does make chezmoi better - thank you), releasing any sort of new version does have an impact on people who maintain chezmoi packages downstream. I don't want to overwhelm them with too many updates.

I would have a different opinion on the above if chezmoi had a comprehensive black box test suite that exercised most of its functionality, but right now chezmoi doesn't have that.

**Comment by twpayne** [comment]
Thinking more about this, chezmoi thinks it's a `dev` version if no version number is set. If no version number is set, then equally chezmoi might not have been packaged correctly (for an example, see https://github.com/twpayne/chezmoi/pull/697#issuecomment-618550711). The sequence of shell commands to build chezmoi from master might work on POSIX-like systems, but are unlikely to work on Windows or Termux or similar. Therefore, I think mose reasonable course of action is to refuse to upgrade `dev` versions.

**Comment by sandorex** [comment]
I totally understand the reasoning, i am running master cause of #691 and #701, i am truly thankful for making this software and well responding to issues this quickly!
