### ISSUE TITLE
Add option: use symlink to replace destination

### ISSUE THREAD

**Issue by BSDxxxx** [twpayne/chezmoi#726]
## Describe the solution you'd like

If the dotfile is a symlink file to sourceDir, after I edit the file, it will be 'auto-updated' and 'auto-applied'.

Just like a neat way to accomplish [Handle configuration files which are externally modified](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#handle-configuration-files-which-are-externally-modified).

**Comment by twpayne** [comment]
You can achieve this with the `--apply` flag to `chezmoi edit`.

**Comment by BSDxxxx** [comment]
> You can achieve this with the `--apply` flag to `chezmoi edit`.

Not really, I need something like `chezmoi add --symlink settings.json` to achieve

1. Copy settings.json to your source/symlink/ directory:
2. Tell chezmoi that `~/.config/Code/User/settings.json` should be a symlink to the file in your source directory.

I like to use the symlink, it's a neat way to manage dotfiles. But the solution [Handle configuration files which are externally modified](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#handle-configuration-files-which-are-externally-modified) is kind of complex

**Comment by twpayne** [comment]
Ah, I see. Thank you for the clarification.

This also needs to update `.chezmoiignore` to ignore the copied `settings.json`.

**Comment by BSDxxxx** [comment]
> Ah, I see. Thank you for the clarification.
> 
> This also needs to update `.chezmoiignore` to ignore the copied `settings.json`.

@twpayne 
**For reference:**
1. For convenience, I put all my symlink file & dir in the `sourceDir/symlink/` directory, and I just have to put `symlink` in the `.chezmoiignore` file manually once and for all.
So I think it could be a cmd option or configurable in chezmoi.toml to control whether add to symlink file & dir to .chezmoiignore.
2. According to 1, I suggest the location (in sourceDir) of file & dir which need to be symlinked should also be configurable and have a default value. 
etc. I put them in the `sourceDir/symlink/` dir.

**Comment by 3v1n0** [comment]
> chezmoi add --symlink --apply settings.json

I second this, and maybe something to apply everything that is non-encrypted/templated as symlinks by default.

I really like many features of chezmoi, but the fact of handling symlinks manually for such cases is a bit unfortunate.

There are multiple cases where this can be wanted, as many apps just create files and then you want manage them through the app itself, and so it's not easy to keep things in sync.

Tools lik [dotdrop](https://github.com/deadc0de6/dotdrop/wiki/symlinked-dotfiles) handles them in a way that could be used by chezmoi as well, as [templated and encrypted files](https://github.com/deadc0de6/dotdrop/wiki/symlinked-dotfiles#templating-symlinked-dotfiles) would be perfect, so having a directory ) are just pointing the files in the target dir.

However...

Since I was missing this, together with what @Lilja was mentioning in #753, I wanted to keep my dotfiles in a separate path in my default setup, and [organized differently](https://github.com/3v1n0/ellipses/tree/chezmoi/private_dot_ellipses), so I've written some bash scripts that are running every time you `apply` (or manually) to allow to have a [GNU `stow`-like](https://www.gnu.org/software/stow/) structure with chezmoi, and making sure that any `~/.dotted` file points to the actual chezmoi file (if not templated or encrypted), by generating "native" chezmoi link files. So that when you use `chezmoi diff` you get some diffing.

So for example:

```bash

# Make a directory where to keep the managed files and add to chezmoi
❯ mkdir -m700 -p ~/.ellipses/vscode/.config/Code/User/
❯ mv ~/.config/Code/User/keybindings.json ~/.ellipses/vscode/.config/Code/User/
❯ tree -R ~/.ellipses/vscode -a
~/.ellipses/vscode
└── .config
    └── Code
        └── User
            └── keybindings.json

# Adding to chezmoi, as the symlink sources
❯ chezmoi add -r ~/.ellipses/vscode/
❯ tree private_dot_ellipses
private_dot_ellipses
└── vscode
    └── private_dot_config
        └── private_Code
            └── User
                └── keybindings.json

# Add the "repo" directory to chezmoi, so that will be the symlink target dir
❯ chezmoi add ~/.config/Code/User/

# Launch the tooling
❯ bash $(chezmoi source-path)/ellipses-tools/generate-chezmoi-links.sh

# And this will generate:
❯ tree private_dot_config/ 
private_Code
└──private_dot_config
   └── User
       └── symlink_keybindings.json.tmpl

# So that diff will be:
❯ chezmoi diff
chmod 755 ~/.config/Code/User
ln -sf ~/.local/share/chezmoi/private_dot_ellipses/vscode/private_dot_config/private_Code/User/keybindings.json ~/.config/Code/User/keybindings.json
chmod 755 ~/.ellipses/vscode
chmod 700 ~/.ellipses/vscode/.config
chmod 700 ~/.ellipses/vscode/.config/Code
chmod 755 ~/.ellipses/vscode/.config/Code/User
chmod 644 ~/.ellipses/vscode/.config/Code/User/keybindings.json


# And once applied, the file points to the actual one:
❯ chezmoi apply
❯ ls ~/.config/Code/User/keybindings.json -lh 
lrwxrwxrwx 1 marco marco 114 mag 30 19:42 ~/.config/Code/User/keybindings.json -> ~/.local/share/chezmoi/private_dot_ellipses/vscode/private_dot_config/private_Code/User/keybindings.json
```

However, some configurations where we've a mix of auto-generated files we don't want to handle and other we actually want to keep track may be a bit more complicated such as shown in these examples:

<details>
<summary>my neovim config structure</summary>

```
❯ tree -L 2 ~/.ellipses/vim
~/.ellipses/vim
├── .config
│   └── nvim
│       ├── autoload
│       ├── ftplugin
│       ├── init.vim
│       ├── keybindings.vim
│       ├── pack
│       ├── pager.vim
│       ├── plugged
│       ├── theming.vim
│       ├── viminfo
│       └── wildignores.vim
├── .vim
│   ├── autoload
│   │   └── plug.vim
│   ├── init.vim -> ~/.ellipses/vim/.config/nvim/init.vim
│   ├── keybindings.vim -> ~/.ellipses/vim/.config/nvim/keybindings.vim
│   ├── .netrwhist
│   ├── pager.vim -> ~/.ellipses/vim/.config/nvim/pager.vim
│   ├── plugged
│   ├── .stignore
│   ├── theming.vim -> ~/.ellipses/vim/.config/nvim/theming.vim
│   ├── viminfo
│   ├── .viminfo
│   └── wildignores.vim -> ~/.ellipses/vim/.config/nvim/wildignores.vim
└── .vimrc -> .config/nvim/init.vim

# Generating
❯ tree -L 1 ~/.vim
~/.vim
├── autoload
├── init.vim -> ~/.ellipses/vim/.config/nvim/init.vim
├── keybindings.vim -> ~/.ellipses/vim/.config/nvim/keybindings.vim
├── pager.vim -> ~/.ellipses/vim/.config/nvim/pager.vim
├── plugged
├── theming.vim -> ~/.ellipses/vim/.config/nvim/theming.vim
├── viminfo
└── wildignores.vim -> ~/.ellipses/vim/.config/nvim/wildignores.vim

❯ tree -L 1 ~/.config/nvim
~/.config/nvim
├── init.vim -> ~/.local/share/chezmoi/private_dot_ellipses/vim/private_dot_config/private_nvim/init.vim
├── keybindings.vim -> ~/.local/share/chezmoi/private_dot_ellipses/vim/private_dot_config/private_nvim/keybindings.vim
├── pager.vim -> ~/.local/share/chezmoi/private_dot_ellipses/vim/private_dot_config/private_nvim/pager.vim
├── theming.vim -> ~/.local/share/chezmoi/private_dot_ellipses/vim/private_dot_config/private_nvim/theming.vim
└── wildignores.vim -> ~/.local/share/chezmoi/private_dot_ellipses/vim/private_dot_config/private_nvim/wildignores.vim
```
</details>

<details>
<summary>or my weechat structure, notice that `irc.conf` is encrypted and so pointing to the target dir</summary>

```
tree -L 2 ~/.ellipses/weechat ~/.ellipses/weechat/.config -a
~/.ellipses/weechat
├── .config
│   └── weechat
└── data
    ├── .ellipses-ignore
    ├── logs
    ├── urls.log
    ├── weechat.log
    └── xfer
~/.ellipses/weechat/.config
└── weechat
    ├── alias.conf
    ├── aspell.conf
    ├── autosort.conf
    ├── buffer_autoset.conf
    ├── buffers.conf
    ├── buflist.conf
    ├── charset.conf
    ├── colorize_nicks.conf
    ├── exec.conf
    ├── fifo.conf
    ├── fset.conf
    ├── irc.conf
    ├── logger.conf
    ├── logs -> ../../data/logs
    ├── lua
    ├── lua.conf
    ├── perl
    ├── perl.conf
    ├── plugins.conf
    ├── python
    ├── python.conf
    ├── relay.conf
    ├── ruby
    ├── ruby.conf
    ├── script
    ├── script.conf
    ├── sec.conf
    ├── spell.conf
    ├── trigger.conf
    ├── urlgrab.conf
    ├── urls.log -> ../../data/urls.log
    ├── weechat.conf
    ├── weechat.log -> ../../data/weechat.log
    ├── xfer -> ../../data/xfer
    └── xfer.conf

# Generates

❯ tree -L 1 ~/.weechat
~/.weechat
├── alias.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_alias.conf
├── aspell.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_aspell.conf
├── autoset.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_buffer_autoset.conf
├── autosort.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_autosort.conf
├── buffer_autoset.conf
├── buffers.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_buffers.conf
├── buflist.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_buflist.conf
├── charset.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_charset.conf
├── colorize_nicks.conf
├── exec.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_exec.conf
├── fifo.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_fifo.conf
├── fset.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_fset.conf
├── irc.conf -> ~/.ellipses/weechat/.config/weechat/irc.conf
├── logger.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_logger.conf
├── logs -> ~/.ellipses/weechat/.config/weechat/logs
├── lua -> ~/.ellipses/weechat/.config/weechat/lua
├── lua.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_lua.conf
├── nicks.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_colorize_nicks.conf
├── perl -> ~/.ellipses/weechat/.config/weechat/perl
├── perl.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_perl.conf
├── plugins.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_plugins.conf
├── python -> ~/.ellipses/weechat/.config/weechat/python
├── python.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_python.conf
├── relay.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_relay.conf
├── ruby -> ~/.ellipses/weechat/.config/weechat/ruby
├── ruby.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_ruby.conf
├── script -> ~/.ellipses/weechat/.config/weechat/script
├── script.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_script.conf
├── sec.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_sec.conf
├── spell.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_spell.conf
├── trigger.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_trigger.conf
├── urlgrab.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_urlgrab.conf
├── urls.log -> ~/.ellipses/weechat/.config/weechat/urls.log
├── weechat.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_weechat.conf
├── weechat_fifo
├── weechat.log -> ~/.ellipses/weechat/.config/weechat/weechat.log
├── xfer -> ~/.ellipses/weechat/.config/weechat/xfer
└── xfer.conf -> ~/.local/share/chezmoi/private_dot_ellipses/weechat/private_dot_config/private_weechat/private_xfer.conf
```
</details>

The basic idea is:
 - Files are structured (like in `stow`) in the `~/.ellipses/package/<path>`
      -  So if you add a `~/.ellipses/foopackage/.bardotfile`  it creates a `~/.bardotfile` link pointing to `$(chezmoi source-path)/.bardotfile`
 - If a file is a template or encrypted we just use the one in target (and so ~/.ellipses/foopackage/.bardotfile in the above example)
 - if the package contains a directory, we symlink it if there are no real files in your `$HOME`
   -  So if you add a `~/.ellipses/foopackage/.bardodir` it creates a `~/.bardotdir` link to the `~/.ellipses/foopackage/.bardodir`
- If the package contains a directory and we've it our `$HOME` and it's tracked in chezmoi we symlink all its children.
   -  So if you add a `~/.ellipses/foopackage/.bardodir/file_{1...n}` with various children, will link all the children to `$(chezmoi source-path)/.bardotdir/file_{1...n}`

So, while it implies moving the files a bit at first (but maybe another script could be to automatize the files importation), this makes things working as expected

**Comment by Gabirel** [comment]
> chezmoi add --symlink --apply settings.json
I vote for this one as well.

I really like the way to manage in one place via system link instead of syncing them.

**Comment by 3v1n0** [comment]
> > chezmoi add --symlink --apply settings.json
> 
> I vote for this one as well.
> 
> I really like the way to manage in one place via system link instead of syncing them.

@Gabirel try [my ellipses-tools](https://github.com/3v1n0/ellipses/tree/chezmoi/ellipses-tools) for chezmoi, in the mean time, they may help you for this.

**Comment by jsravn** [comment]
I really agree with this issue. It's by far my biggest pain point with chezmoi. To the point that I've given up on using chezmoi now except for templated files (which are a very small percentage of my dotfiles - just stuff with passwords). My prior home grown dotfile system, as well as pretty much all other dotfile management I've looked into use symlinks. This makes it so much easier to update files and keep changes in sync - you edit the actual file, then just commit to git from your favorite code editor. It also prevents accidentally deleting changes - many times I've accidentally overwritten an edit because I forgot to sync beforehand.

**Comment by Legion2** [comment]
Without symlinks the two configurations ($HOME and the git repo) are completely separated, which is good, because you can not break thinks by just do a git pull.

**Comment by jsravn** [comment]
@Legion2 git already handles this - it fails if you have local changes when you do a git pull. That lets the user know they need to sync their changes before updating. With chezmoi, you have no idea - you do a chezmoi update, and all your local changes are wiped out.

**Comment by Legion2** [comment]
If you use symlinks into the git repository, the config gets changed as soon as you do a git pull. But maybe the new configuration you just pulled require more symlinks which are not created by git pull, so your configuration in $HOME is now in an inconsistent state. Some changed configuration files may link (by file name in the configuration) to some new file which is not jet symlinked in your home directory.

@jsravn i also don't like that chezmoi overrides configuration files without warning. To solve this chezmoi had to store the last applied state somewhere. So, it could identify which files were changed in the local home dir. Another option would be to store only a hash of the state and compare it before applying a new state and warn the user. It then would be the responsibility of the user to identify the changes he/she made.

**Comment by twpayne** [comment]
> @jsravn i also don't like that chezmoi overrides configuration files without warning. To solve this chezmoi had to store the last applied state somewhere. So, it could identify which files were changed in the local home dir. Another option would be to store only a hash of the state and compare it before applying a new state and warn the user. It then would be the responsibility of the user to identify the changes he/she made.

This is happening in the `v2` branch (#654), see #423 and #424 for a similar request.

**Comment by vergenzt** [comment]
I'd just like to echo my support for this. I'm syncing my `~/.atom/config.cson`, and it'd be nice to have it auto-update the chezmoi source repo (via a symlink or otherwise). 😬

**Comment by shiftgeist** [comment]
Is this still a scope for chezmoi?

**Comment by twpayne** [comment]
Yes, #1292 has the beginning of an implementation.

**Comment by twpayne** [comment]
OK, so if you're interested in chezmoi creating symlinks like GNU Stow then please have a look at #1292 and try out the experimental symlink mode by putting `mode = "symlink"` in your config file. You can [download binaries from the CI run](https://github.com/twpayne/chezmoi/actions/runs/1102967692#artifacts). Please do read the limitations of using symlinks in the [doc diffs](https://github.com/twpayne/chezmoi/pull/1292/files).

**Comment by dbent** [comment]
Is there a way to use the symlink mode for a single file? I would prefer to use symlinks only when necessary (for externally modified files) and use the normal mode otherwise. Or, is the only way to do that still the [manual process](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#handle-configuration-files-which-are-externally-modified)?

**Comment by twpayne** [comment]
At the moment the only way to do it is with the manual process you link to. symlink mode is otherwise a global setting.
