### ISSUE TITLE
`error calling pass: pass: pass show foo/bar: exit status 2` in ssh shells

### ISSUE THREAD

**Issue by Grimler91** [twpayne/chezmoi#784]
First of all, thanks for chezmoi. This is the third dotfile handling system I try and it is more flexible and less complex than what I previously tried (a homemade solution and dotdrop).

## Describe the bug

`chezmoi apply` or `chezmoi diff` gives an error 

```
/usr/bin/pass show foo/bar: exit status 2
chezmoi: template: /home/grimler/.local/share/chezmoi/dot_foo.tmpl:6:25: executing "/home/grimler/.local/share/chezmoi/dot_foo.tmpl" at <pass "foo/bar">: error calling pass: pass: pass show foo/bar: exit status 2
```

if run from a terminal without Xorg/wayland running, so for example in an ssh shell (without the -X option).

## To reproduce

Create a dotfile.tmpl with `{{ pass foo/bar }}`, create a `foo/bar` file in pass and then ssh into localhost to get a ssh shell `ssh localhost`, and then try `chezmoi diff`.

I also run into this problem when running chezmoi on my phone, in [termux](https://termux.com/).

## Expected behavior

`chezmoi diff` show show me pending changes instead of giving the `/usr/bin/pass show foo/bar: exit status 2` error.

## Output of command with `--verbose`

Exactly the same output
```
$ chezmoi diff --verbose
/usr/bin/pass show foo/bar: exit status 2
chezmoi: template: /home/grimler/.local/share/chezmoi/dot_foo.tmpl:6:25: executing "/home/grimler/.local/share/chezmoi/dot_foo.tmpl" at <pass "foo/bar">: error calling pass: pass: pass show foo/bar: exit status 2
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
warning: version dev
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/grimler/.local/share/chezmoi (source directory, perm 700)
     ok: /home/grimler (destination directory, perm 710)
     ok: /home/grimler/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/bash (shell)
     ok: /usr/bin/vi (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.27.0)
     ok: /usr/bin/gpg (GnuPG, version 2.2.20)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
     ok: /usr/bin/pass (pass CLI, version 1.7.3)
warning: vault (Vault CLI, not found)
```

## Additional context

A workaround, which I have been using so far, is to run `pass foo/bar` manually before `chezmoi apply`/`chezmoi diff`. The chezmoi command then works since the gpg password is cached (or something like that).

**Comment by twpayne** [comment]
Thanks for reporting this. From a bit of experimenting on my macOS machine and reading the pass documentation, I think the problem is as follows:

chezmoi needs either a reliable non-interactive way to get a password out of pass, or at least a predictably interactive way to get a password, and pass provides neither.

pass invokes gpg to decrypt passwords. When the passphrase is cached in memory, pass prints the decrypted password to stdout, which chezmoi can read. When the passphrase is not cached in memory, then gpg will prompt for the passphrase, and the method that gpg uses varies widely from installation to installation. For example, gpg might invoke an interactive terminal program, a GUI, or something else. chezmoi cannot reasonably handle all of these possibilities, and any output that the gpg's passphrase reader writes to stdout gets mixed in with the printed password.

The workaround of invoking `pass foo/bar` before running chezmoi works by ensuring that the passphrase is cached so pass just writes the password to stdout.

Ideally, pass would provide a specific command, say `pass unlock`, to prompt for and cache the passphrase, and do nothing else. chezmoi could then run this before invoking `pass show` for the first time, but you will need to reach out to the pass developers to ask for this.

There may also be a way to work around pass's random interactivity using the `PASSWORD_STORE_` environment variables that pass reads. However, these environment variables are typically set in your dotfiles, so they are not available when you run chezmoi for the first time.

**Comment by m-rey** [comment]
After asking about this in the #pass channel on freenode, it was suggested that maybe this could be useful to cache the password. After all, pass uses the gpg agent to decrypt the files:
https://linux.die.net/man/1/gpg-preset-passphrase

**Comment by twpayne** [comment]
Thanks for investigating further @m-rey, `gpg-preset-passphrase` looks like a good candidate.

Note that:
* `gpg-preset-passphrase` is not installed in a directory in `$PATH` (at lease when gpg is installed on Ubuntu 20.20 or on macOS with Homebrew) so we'll need to add a line to chezmoi's config file so that chezmoi can find it.
* You will have to specify the cache-id identifying the key to unlock.
* `gpg-preset-passphrase` will, by default, store the passphrase indefinitely.

Therefore, to use this, we'd need to add something like the following variables to chezmoi's config file:

```toml
[pass]
    cacheId = "foo:12346"
    gpgPresetPassphraseCommand = "/usr/lib/gnupg/gpg-preset-passphrase"
```

If both these config variables are found, then chezmoi can call `gpg-preset-passphrase` the first time the `pass` function is used in a template.

It is not clear to me whether chezmoi should invoke `gpg-preset-passphrase --forget` after each run. If chezmoi does call `--forget` then you'll have to retype the passphrase every time you run `chezmoi apply`. If chezmoi doesn't call `--forget` after then your passphrase will be cached indefinitely (which may not be desirable from a security point of view) and you will probably still be prompted for it anyway the next time you run `chezmoi apply` as I don't think there's a way for chezmoi to know if the passphrase is already cached.

This all said, I'm hesitant to add this to chezmoi because it tightly couples chezmoi to the internals of how pass stores its passwords. I still think this should pass should have an `unlock` command or similar to keep pass and chezmoi as decoupled as possible.

**Comment by m-rey** [comment]
If I have understood the people from #pass and the documentation correctly, pass basically wraps itself around gpg. Therefore I think running commands that interact with gpg directly is fine. After all, people often interact with gpg directly and pass can handle it.
However, I understand that doing it this way doesn't cover the edge cases you mentioned.

As an alternative to `pass unlock`, you could try using something like `pass grep '$^'`.
`pass grep` searches through the decrypted database, thus prompting the user for the password. The regex `$^` never matches anything, so it will always return nothing at all.
All in all, this would basically be a `pass unlock`.

**Comment by twpayne** [comment]
> As an alternative for `pass unlock`, you could try using something like `pass grep '$^'`.

This is a really nice idea and seems to work in my testing. PR coming up.
