### ISSUE TITLE
https://git.io/chezmoi stopped working

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#858]
Problem:

```sh-session
$ curl -L https://git.io/chezmoi
No url found for chezmoi
```

Workaround:

```sh-session
$ curl -L https://raw.githubusercontent.com/twpayne/chezmoi/master/scripts/install.sh
👍
```

**Comment by twpayne** [comment]
Sorry about that, I wanted to update the short url to point to https://github.com/twpayne/chezmoi/blob/master/assets/scripts/install.sh instead of https://github.com/twpayne/chezmoi/blob/master/scripts/install.sh, and there was a bit of downtime as GitHub deleted the link (in the US timezone) so I could re-create it and me creating the link the European time zone.

Anyhow, it's fixed now.

**Comment by twpayne** [comment]
@felipecrs this is now fixed, please use https://github.com/twpayne/chezmoi/blob/master/assets/scripts/install.sh as the work-around.

The reason for updating the location is to keep all assets in the same directory and reduce the number of top level directories.

**Comment by felipecrs** [comment]
@twpayne I wonder, how did you update the URL that your custom short link points to? Every time I try to update mine, (by running the same command I used for creating it) it says `but "existing" already is!`.

**Comment by twpayne** [comment]
You need to ask GitHub to delete the old short URL, you can then re-create it. If an existing short URL already points to the URL you want to shorten then GitHub returns the existing short URL instead of creating a new short URL.

**Comment by felipecrs** [comment]
> You need to ask GitHub to delete the old short URL, you can then re-create it. If an existing short URL already points to the URL you want to shorten then GitHub returns the existing short URL instead of creating a new short URL.

Awesome, thank you very much!
