### ISSUE TITLE
Regenerate chezmoi.toml in chezmoi apply automatically if a chezmoi.toml.tmpl is found on source folder

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#865]
## Why

I often adjust my `chezmoi.toml.tmpl`. Each time I adjust it, I have to remember to run `chezmoi init`, because `chezmoi apply` does not regenerate it by default.

Apart from the `chezmoi.toml` not being on the _default target directory_, is there a reason for not doing that by default in case a `chezmoi.toml.tmpl` is found on the source folder? If it's the only reason, I think it worth it to consider turning it an exception for the rule.

## Solution

The PR's title says all:

Regenerate `chezmoi.toml` in `chezmoi apply` automatically if a `chezmoi.toml.tmpl` is found on source folder.

## Alternatives

Because of this, I prefer to run `chezmoi init --apply` instead of `chezmoi apply`, and `chezmoi update --apply=false && chezmoi init --apply` instead of `chezmoi update`. A bunch of unnecessary complexity in my point of view.

**Comment by sersorrel** [comment]
For templates which use the `prompt*` functions, this would presumably mean that every single `chezmoi apply` results in prompting for input. Would it be worth caching the answers to prompts somewhere, in order to avoid asking the same things over and over?

Alternatively, if existing config was available when running the config template, templates could be written like this:

```
{{- $email := get . "email" -}}
{{- if not $email -}}
{{- $email = promptString "email" -}}
{{- end -}}

[data]
email = "{{ $email }}"
```

Currently this seems to not work, as `.` doesn't contain data from existing configuration when running `chezmoi init` (in contrast to `chezmoi execute-template --init`, where it does contain data from the config file).

**Comment by twpayne** [comment]
This is mostly fixed in #1032 and #1033. Rather than automatically regenerating the config file if the template has changed, you now get a warning that you should run `chezmoi init` to regenerate the config file, but when regenerating the file you do get access to existing template data so @sersorrel's example works.

The reason for not automatically regenerating the config file in `chezmoi apply` right now is is that it would require some code gymnastics. Specifically, after regenerating the config file, chezmoi would have to reread the new config file (while ensuring that no data from the old config file remains) and then restart the `chezmoi apply` operation. On UNIX systems, chezmoi could `execve(2)` itself with its original arguments, but the story on Windows is less obvious.

**Comment by felipecrs** [comment]
I wonder why something simpler as

```
{{ $email := default (promptString "email") .email -}}
```

Doesn't work.

**Comment by twpayne** [comment]
Yeah, Go's `text/template` package is quite eager in its evaluation. As I understand it, `text/template` evaluates each `{{ ... }}` statement individually, but when a statement is evaluated then it is evaluated exhaustively (e.g. there's no boolean short circuiting). This is reasonable behavior.

That said, In this example:

    {{ $email := default (promptString "email") .email -}}

all eager languages would need to evaluate both `promptString "email"` and `.email`, unless they had some magical insight into the logic semantics of `default` (which `text/template` doesn't have).

**Comment by felipecrs** [comment]
You are totally right.

default is not any builtin operator as `||` would have a similar effect in JavaScript but a regular function which accepts 2 parameters, so both needs to be resolved before starting the function.

Got it. Thanks!
