### ISSUE TITLE
Build and distribute RedHat packages

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#9]
`chezmoi` should be easily installable on RedHat systems. We should build and distribute a `.rpm` package.

**Comment by twpayne** [comment]
Wow, thank you. goreleaser looks really nice and a PR adding support for it would be fantastic. I don't have a packagecloud.io repo, and the lowest price plan is $75/month, so let's start initially with Github releases.

I've tagged the current version as `v0.0.1` so you have a valid semantic version tag to start with.

If you don't have time to make a PR then please say and I'll have a look.

**Comment by joemiller** [comment]
@twpayne working on it now

**Comment by joemiller** [comment]
@twpayne I have a work in progress here: https://github.com/twpayne/chezmoi/compare/master...joemiller:goreleaser

Before sending a PR I wanted to ask if you had a preference on the release workflow. There are two different workflows I've used with goreleaser:

**Automated tagging and releasing.**  Combine autotag (https://github.com/pantheon-systems/autotag) with goreleaser for automated releases. In this mode, the workflow for releases goes something like this:
- a successful `master` build generates a new release: Autotag will increment the patch version automatically and push the tag back to github, eg: `v0.0.1` -> `v0.0.2`
- To create a new MINOR release: include `[minor]` or `#minor` in the git commit message. eg: `v0.0.1` -> `v0.1.0`
- To create a new MAJOR release: include `[major]` or `#major` in the git commit message. eg: `v0.0.1` -> `v1.0.0`

**Manually push tags to generate releases.** In this model, in order to create a new release you would create a tag locally and push to github, eg:
```
$ git tag -a v0.1.0 -m "First release"
$ git push origin v0.1.0
```

My team tends to prefer the autotag method since it conforms to the "what is on master is what is released" philosophy. The second method gives you a bit more control over when to release.

Let me know if you have a preference and I'll update the WIP and send the PR. I'm also testing on my own travis-ci account to ensure the releases work all the way through.

**Comment by joemiller** [comment]
example releases here: https://github.com/joemiller/chezmoi/releases

**Comment by twpayne** [comment]
In the short term, let's start with manual releases - `chezmoi` isn't quite settled yet, and I want to make internal changes (e.g. improved testing, doc fixes) without bumping the point release on each one. Once things are more stable, we can switch to the autotag approach.

Thanks for your work on this @joemiller - much appreciated.
