### ISSUE TITLE
Add support for `--cache` arg to 1password-cli

### ISSUE THREAD

**Issue by zb140** [twpayne/chezmoi#935]
## Is your feature request related to a problem? Please describe.

Starting in version 1.8.0, the 1password CLI supports (on Linux and macOS only ☹️) a new argument called `--cache` that opts in to using locally cached secret data instead of fetching it from the network every time.  It would be nice to enable this feature in `chezmoi`.

## Describe the solution you'd like

I made a prototype over here: https://github.com/zb140/chezmoi/commit/71380b405eba25c629479ba28ed4baf9596e0ae7

If you have a new enough `op` version, it will automatically add the `--cache` option.  I've also made it configurable so anyone who for some reason _doesn't_ want this feature can set `onepassword.disableCache` in their `chezmoi.toml`.

Notably, even though the new feature doesn't actually cache anything on Windows, the `op` executable still accepts the argument and returns the correct values.  So, in this implementation I'm adding the `--cache` arg even on Windows. That way, if they ever do implement actual caching (🤞), it will just work.

## Additional context

If this seems like a reasonable thing to do, I'll clean it up a bit and add some docs, then submit a PR.

**Comment by twpayne** [comment]
Thanks for this. I'm now also using 1Password on my work machines and its slowness is evident. One question, one comment.

Question: how is the 1Password cache invalidated? I use `chezmoi apply` to update my dotfiles when I update my secrets and obviously don't wan stale cached secrets.

Comment: for config file, please make it `onepassword.cache` (rather than `disableCache`) with a default of `true`. This makes the logic positive (`if c.onepassword.cache`) and avoids double negatives (`if !c.onepassword.disableCache`).

**Comment by zb140** [comment]
It's not super clear how the cache is invalidated.  The release announcement says that `op` has the ability to know when data it got from the cache is out of date and request a new copy from the server, but I don't know how it would know without doing a network request.  In any case, I haven't done much experimenting with the new feature yet.

I switched the sense of the config option, and I'll submit a PR shortly.  I originally chose `disableCache` because I wasn't sure how to make the default `true`, but on a second look it was actually easy 😄

**Comment by twpayne** [comment]
Fixed by @zb140 in #936.
