### ISSUE TITLE
Add bottles for Homebrew tap

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#939]
Homebrew now supports bottles from GitHub Releases, would be great if this tap could support it too. It would accelerate the installation and require fewer dependencies.

https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

**Comment by twpayne** [comment]
I think chezmoi is already available as a bottle. Reasoning:

chezmoi has been [part of homebrew/core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/chezmoi.rb) since https://github.com/Homebrew/homebrew-core/pull/53431 and I think bottle support was added in [Apr 23, 2020](https://github.com/Homebrew/homebrew-core/commit/6fad8508472e1506d379472268ffe89c3158acd8#diff-60c15d970ac28cbd9a9bed0abc696d91dd003a2f29d90b78e203fabcee43cc4d). The chezmoi-specific homebrew tap was removed on [Jun 27, 2020](https://github.com/twpayne/chezmoi/commit/c5bbee3226e7777563a5aed5ba12dc1ee552fa27).

Please re-open if the above is not correct.

**Comment by felipecrs** [comment]
That's correct. Awesome!
