### ISSUE TITLE
`chezmoi edit` fails on empty files

### ISSUE THREAD

**Issue by covercash2** [twpayne/chezmoi#942]
## To reproduce

now that i'm getting used to chezmoi, a natural workflow for me has emerged:

```
$ touch config.file
$ chezmoi add config.file
$ chezmoi edit config.file
chezmoi: file does not exist
```

## Expected behavior

add a new empty file to chezmoi and edit it.

## Output of command with `--verbose`

```
$ touch test
$ chezmoi add test
$ chezmoi --verbose source-path test
chezmoi: file does not exist
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
warning: version 1.8.9
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/chrash/.local/share/chezmoi (source directory, perm 700)
     ok: /home/chrash (destination directory, perm 710)
     ok: /home/chrash/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/bin/fish (shell)
     ok: /usr/bin/nvim (editor)
warning: vimdiff (merge command, not found)
     ok: /usr/bin/git (source VCS command, version 2.29.2)
     ok: /usr/bin/gpg (GnuPG, version 2.2.23)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
     ok: /usr/bin/keepassxc-cli (KeePassXC CLI, version 2.6.2)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

**Comment by zb140** [comment]
`chezmoi add` actually does not add empty files unless you explicitly say it's ok for a file to be empty.  Likewise, empty files will not be created in your target (home) directory unless they have the `empty_` attribute set in the source state.  So, in this case the error is actually correct: the file `test` actually does not exist in your source tree, because it was empty when you tried to add it.

You can make your workflow work by adding the `-e` option to `chezmoi add`:
```bash
$ touch foo
$ chezmoi add -e foo
$ chezmoi edit foo
```
but any file you add this way will have its `empty_` attribute set, meaning you lose the benefits of automatically pruning empty files (which can be useful, for example, when sharing configurations across multiple machines).  In the end, I would suggest it's probably better to create and edit the file first before adding it, but of course you should do whatever works best for you :smile:

Incidentally, there is actually a bug in this functionality on Windows, such that your expected workflow actually does work.  This should probably be fixed.  (Nerd note: I haven't tested this theory yet but looking at the code, the most obvious way I could see this failing is that maybe the size of an empty file on Windows is not actually 0, weird as that sounds.  See: https://github.com/twpayne/chezmoi/blob/master/internal/chezmoi/targetstate.go#L245)

**Comment by covercash2** [comment]
i thought it may be something like this. my workaround was

```
$ echo empty > test
$ chezmoi add test
...
```

just wanted to make sure this wasn't a bug. great work and carry on
