### ISSUE TITLE
template action in .chezmoi.yaml.tmpl

### ISSUE THREAD

**Issue by Lomendil** [twpayne/chezmoi#957]
## What exactly are you trying to do?

I would like to use `{{ template "my-specific-config" }}` in .chezmoi.yaml.tmpl
This behaviour is possible ?

## What have you tried so far?

I try this way:
```
{{ if eq .chezmoi.hostname "mylaptop" }}
{{ template "laptop.chezmoi.yaml" . }}
{{ end }}
```
It works with `execute-template` but not in `init`

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [x] Other, all 

## Output of any commands you've tried with `--verbose`
```
$  chezmoi execute-template --verbose < .chezmoi.yaml.tmpl
data:
   is_laptop: true
```
```
$ chezmoi init --verbose
chezmoi: template: chezmoi.yaml:2:12: executing "chezmoi.yaml" at <{{template "laptop.chezmoi.yaml" .}}>: template "laptop.chezmoi.yaml" not defined
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
     ok: version 1.8.9, commit 4fd06fa089912eb833bc6dc33fd50c0129a0e6ae, built at 2020-11-20T03:48:19Z, built by goreleaser
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/user/.local/share/chezmoi (source directory, perm 700)
     ok: /home/user (destination directory, perm 755)
     ok: /home/user/.config/chezmoi/chezmoi.yaml (configuration file)
     ok: /usr/bin/zsh (shell)
     ok: /usr/bin/nvim (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.17.1)
     ok: /usr/bin/gpg (GnuPG, version 2.2.4)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
     ok: /usr/bin/keepassxc-cli (KeePassXC CLI, version 2.3.1)
warning: lpass (LastPass CLI, not found)
     ok: /usr/bin/pass (pass CLI, version 1.7.1)
warning: vault (Vault CLI, not found)

```

**Comment by twpayne** [comment]
This currently isn't possible: `.chezmoi.yaml.tmpl` is executed by `chezmoi init` which has a slightly different set of template variables and functions available, mainly because the source state is not available yet.

It would be possible to add the feature, but I would like to ensure that it's needed first. Specifically, it would require `chezmoi init` to parse the source state to find `.chezmoitemplate` directories, and I need to think through the implications of this.

It might be helpful to look at [my personal `.chezmoi.toml.tmpl`](https://github.com/twpayne/dotfiles/blob/master/.chezmoi.toml.tmpl) which handles variation across machines with a set of boolean tags. It's not quite what you requested, but it may be a more scalable approach than one config file per machine, especially if you have a lot of diverse machines.

**Comment by Lomendil** [comment]
Thanks for this explanation. It's really clear.
I will try your way :)
