### ISSUE TITLE
Apply only a predefined list of dotfiles rather than all of them

### ISSUE THREAD

**Issue by reputet** [twpayne/chezmoi#958]
Hi, thanks for developing and maintaining such an outstanding tool!

## Is your feature request related to a problem? Please describe.

I'm trying to [apply](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#apply-targets) only a subset of managed dotfiles, not all of them. And I'm looking for an option to define these sets beforehand so that they can be used later while applying with a single command.

Let' say there is a following list of dotfiles:

- .bashrc
- .htoprc
- .vimrc
- .vlc/vlcrc
- .zshrc

And I have two machines: a home PC and a workstation.

My goal is to apply only **a few** of these files on a particular machine. E.g. I want `.bashrc`, `.htoprc` and `.vimrc` to be applied on workstation and only `.vimrc`, `.vlc/vlcrc` and `.zshrc` on my home PC.

## Describe the solution you'd like

From my perspective, it might look like
```bash
$ chezmoi apply --profile workstation
```
to add the abovementioned files (`.bashrc`, `.htoprc` and `.vimrc`) to the home directory on the workstation.

## Describe alternatives you've considered

I believe here is an example of how a similar feature is implemented in another dotfiles manager as a concept of [profiles](https://github.com/deadc0de6/dotdrop#getting-started). It keeps a `config.yaml` file with defined profiles:
```yaml
profiles:
  home:
    dotfiles:
    - f_vimrc
    - f_xinitrc
    - d_polybar
  office:
    dotfiles:
    - f_xinitrc
    - d_polybar
```

And you're allowed to choose which profile you want to deploy the files from:
```
$ dotdrop install --profile=office
```

**Comment by twpayne** [comment]
Short (wrong) answer: `chezmoi apply` takes a list of targets, so you can run

```
chezmoi apply ~/.bashrc ~/.htoprc ~/.vimrc
```

on workstation and

```
chezmoi apply ~/.vimrc ~/.vlc/vlcrc ~/.zshrc
```

on your home PC. But this isn't the right answer.

Long (correct) answer: with chezmoi the idea is that you can run `chezmoi apply` on different machines and get the right set of dotfiles for the machine you're running on. Instead of profiles, chezmoi uses [templates](https://github.com/twpayne/chezmoi/blob/master/docs/TEMPLATING.md) and files like [`.chezmoiignore`](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#use-templates-to-manage-files-that-vary-from-machine-to-machine) to ensure that the right set of dotfiles get installed on each machine.

In the specific case you give, I would recommend creating a template variable called `workstation` (for example) that you set in your config file and then use in `.chezmoiignore` and in your dotfile templates. #957 is relevant.

**Comment by twpayne** [comment]
Thank you very much for the very clear description of the problem - much appreciated!

**Comment by twpayne** [comment]
FYI my personal `.chezmoiignore` is [here](https://github.com/twpayne/dotfiles/blob/master/.chezmoiignore).

**Comment by reputet** [comment]
Tom, thanks so much for your instant and detailed reply!

Template approach is not as straightforward as the configuration one in the example I gave, but I got the idea looking at your .chezmoiignore. It's clear now 👍
