### ISSUE TITLE
install.sh: return code 1 (EXECARGS empty)

### ISSUE THREAD

**Issue by jericdeleon** [twpayne/chezmoi#967]
First of all, thanks for this tool, been using it to great effect!

My Ansible role for installing `chezmoi` just failed recently, and the issue's coming from this line:
https://github.com/twpayne/chezmoi/blob/9a5831860bf3f18bd429da6a5ed41ad71c38202d/assets/scripts/install.sh#L80

Previously, `install.sh` returned `0`.
Now, by the time this line is hit, `EXECARGS` is empty. And so, `test -n "$EXECARGS"` returns `1`.
Since `chezmoi` is installed already at this point, I can just temporarily accept `1` as a passable return code, but having it return `0` would be best.

I got these results while running on a Vagrant box (`opensuse/Tumbleweed.x86_64`).

I'm still trying to understand the reasoning of this line, so I'll just file this issue while grokking the script.
Thanks!

**Comment by twpayne** [comment]
Thanks for reporting the bug. I re-wrote the install script in #937 and obviously missed this.

The reason for the line is so that you can invoke chezmoi after it is installed by passing extra arguments to the install script. This should make it possible to install chezmoi and your dotfiles with one line:

    curl -fsL https://git.io/chezmoi | sh -s -- init --apply https://github.com/username/dotfiles.git

Note that this isn't quite working yet.

**Comment by jericdeleon** [comment]
Thanks for the fix, that's a cool enhancement, will try that out too once it's done!
